### ISSUE TITLE
[UI] Scrollbar overlapping ADD button - Images Tab

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1102]
### Rancher Desktop Version

0.7.0-beta.1-87-g75d747d

### Rancher Desktop K8s Version

1.21.7

### What operating system are you using?

macOS

### Operating System / Build Version

Monterey 12.0.1

### What CPU architecture are you using?

x64

### Windows User Only

N/A

### Actual Behavior

On Images tab, the scrollbar overlaps the `add` button partially.

### Steps to Reproduce

1. Navigate to `Images` tab
2. Select `Image Namespace: k8s.io`
3. Should see the scrollbar overlapping the `ADD` btn.

### Result

![Screen Shot 2021-12-14 at 10 38 39 AM](https://user-images.githubusercontent.com/37411123/146041303-a2051e3e-18a6-43dc-9e0c-efe512d2a6cb.png)

### Expected Behavior

Scrollbar should not overlap the btn component.

**Comment by rak-phillip** [comment]
There are two things that I can see contributing to this behavior

1. We have set the entire `body` class to scroll, which would be fine if it weren't for item 2
2. The table has a minimum width of 400px, which will cause the container to start overflowing when the window width goes below the threshold

We might be able to address this on in a few ways

1. Introduce a collapsible nave menu; we might be able to auto-collapse when the window width goes below a certain threshold and give more space to the `body` here
2. Separate the title area so that its width can be relative to the window instead of its sibling.. I think we can do this through some clever CSS, but it might be better to review our grid areas first to see if can get a layout that better fits our use case
