### ISSUE TITLE
Unable to reach company registry despite certs added to trust store

### ISSUE THREAD

**Issue by cazzoo** [rancher-sandbox/rancher-desktop#1138]
### Rancher Desktop Version

0.7.0

### Rancher Desktop K8s Version

1.21.7

### What operating system are you using?

Windows

### Operating System / Build Version

10 Enterprise Version 20H2

### What CPU architecture are you using?

x64

### Windows User Only

Using Cisco VPN, a lot a firewall rules (that I don't manage) that would let us pass to internet.
Company is quite large, I need to register to docker.io, then authenticate in WSL distro to get builder image to be fetch (otherwise I have docker pull rate issue).
Regarding VPN, the current version I use doesn't pass properly the DNS to the WSL, I need to manually update the /etc/resolv.conf file to specify company DNS.

### Actual Behavior

After all initial setup as been done (see above), I just try to authenticate to company image registry (gitlab) that has its own certificate and chain (signed by Digicert Root and intermediate). When running the command, the CLI just reports "TLS handshare timeout"`
Sample output
```
cat mypass | nerdctl login -u myuser --password-stdin gitlab-registry.company-domain.com
INFO[0010] Error logging in to endpoint, trying next endpoint  error="Get \"https://gitlab-registry.company-domain.com/v2/\": net/http: TLS handshake timeout"
FATA[0010] Get "https://gitlab-registry.company-domain.com/v2/": net/http: TLS handshake timeout
```

### Steps to Reproduce

Setup the env as previously explained
Start rancher-desktop
Try to authenticate to registry

### Result

Some more research while connected to the distro:
```
/usr/bin # cat /etc/resolv.conf
search lan company-domain
nameserver 10.231.215.20
nameserver 10.232.215.20
nameserver 192.168.1.254
```

```
/usr/bin # nslookup gitlab-registry.company-domain.com
Server:         10.231.215.20
Address:        10.231.215.20:53

Non-authoritative answer:
gitlab-registry.company-domain.com      canonical name = gitlab-registry-pr.company-domain.com
gitlab-registry-pr.company-domain.com   canonical name = gitlab-pr.company-domain.com
Name:   gitlab-pr.company-domain.com
Address: 10.225.83.11

Non-authoritative answer:
gitlab-registry.company-domain.com      canonical name = gitlab-registry-pr.company-domain.com
gitlab-registry-pr.company-domain.com   canonical name = gitlab-pr.company-domain.com
```

```
/usr/bin # /usr/bin/curl https://gitlab-registry.company-domain.com
curl: (6) Could not resolve host: gitlab-registry.company-domain.com
```

```
cd /usr/local/share/ca-certificates/ && certutil.exe -dump rd-0.crt | grep company-domain
    CN=*.company-domain.com
        DNS Name=*.company-domain.com
        DNS Name=company-domain.com
```

### Expected Behavior

Authentication works.
TLS handshare doesn't fail

**Comment by mook-as** [comment]
Given that it's `TLS handshake timeout`, I wonder if the actual cert doesn't matter, and it just failed to contact the registry?

You've already tried curl; but:
- The `nameserver` entries in `/ets/resolv.conf` are _not_ a priority list; it's undefined which server's response will be used.  Perhaps remove enough of them so that only servers that have the same response remain? (I don't expect a network to contain both `10.*` and `192.168.*`.)

But TLS handshake timeout means that it's already managed to finish the DNS lookup; there's some sort of connection error to the host.  Perhaps we can try `curl` again, after DNS has been fixed? Alternatively, try something like:
```sh
curl --resolve gitlab-registry.company-domain.com:443:10.225.83.11 https://gitlab-registry.company-domain.com
```

Additionally, I see that you're showing information about the cert; is that certificate (`rd-0.crt`) a certificate authority? I believe the infrastructure expects CAs to be there, not certificates for individual sites.  But then, if the server's cert is chained up to Digicert, it probably doesn't need a custom CA cert to be there in the first place.

**Comment by cazzoo** [comment]
I didn't try already, I plan to do by Monday. In the meantime I was just wondering if we might think using https://github.com/moby/vpnkit to solve VPN/Networking issues

**Comment by jandubois** [comment]
> I was just wondering if we might think using https://github.com/moby/vpnkit to solve VPN/Networking issues

We have looked at it, but unfortunately had to reject it for various reasons, including:

* it is still under (sporadic) heavy development, but the documentation hasn't been updated in 5 years
* it is written in OCaml, which few people know how to change or debug, if the need arises
* some of the guest-side code is either not open-source, or only available from some obscure location that we haven't been able to find. Or maybe this is a misunderstanding due to the lack of open source examples that show how to actually use it.

We will probably need something like it, but in a form that can be maintained by a community and not just by a single person (you'll see that over 90% of the commits on `vpnkit` are from a single author, including almost 100% of the commits from the last 4 years).

**Comment by Nino-K** [comment]
@cazzoo please upgrade to 1.9 release and enable our new https://github.com/rancher-sandbox/rancher-desktop/issues/3810network which should address this issue. You can simply enable the new network using:

```
rdctl set --experimental.virtual-machine.networking-tunnel=true
```
