### ISSUE TITLE
package workflow: Rancher Desktop-linux.zip contains the actual content - not another zip-file.

### ISSUE THREAD

**Issue by tullo** [rancher-sandbox/rancher-desktop#1205]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently the result of executing unzip 'Rancher Desktop-linux.zip' is another zip-file; not the actual content.

This is observed by downloading and unzipping the artifact produced by the `package` GH-Action. 

### Proposed Solution

The result of executing `unzip 'Rancher Desktop-linux.zip'` is the actual content; not another zip-file.

**Comment by mook-as** [comment]
This is partly due to a known issue with the [GitHub Actions artifact uploader](https://github.com/actions/upload-artifact#zipped-artifact-downloads).  We could work around this by unzipping the file first and then recreating it with just the contents, but haven't done so yet as that affects downstream automation.

**Comment by tullo** [comment]
Never mind. I wasn't aware of the limitations of the uploader. Learned something new. Thanks!
