### ISSUE TITLE
On Windows, switching to images tab flashes a command terminal for a fraction of a second.

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#1248]
I tried with the latest build from here (https://github.com/rancher-sandbox/rancher-desktop/actions/runs/1695857809) 

**Steps:**
- Open RD app
- Switch to Images tab. You will see a command windows flashing for a fraction of a second. This behavior wasn't there in earlier versions.

**Comment by jandubois** [comment]
I see this too: every time RD runs a subprocess, a console window is shown:

<img width="825" alt="Screen Shot 2022-01-14 at 8 05 17 PM" src="https://user-images.githubusercontent.com/78947/149608188-0b431585-472a-4c1e-bd30-75d9e80177ba.png">

I've added this issue to the 1.0.0 milestone expecting this to be an easy fix (just setting some flag on the call). If it turn out to require significant research or work, please move to 1.1.0 instead!

**Comment by evertonlperes** [comment]
I did replicate the extra pop up showing up during the Rancher Desktop start up.
It seems the `wsl` binary pops an extra console window, if you have a distro selected/enabled on WSL Integration tab. 
Even trying to manually closing the window, it will keep appearing. 
In order to disable the extra console pop up, the existing distro at WSL Integration tab should be disabled/unchecked.

Here s short video about the issue:

https://user-images.githubusercontent.com/37411123/149818397-ee14951a-ec51-4989-b9e8-1ed6e9a01015.mov

**Comment by mook-as** [comment]
There's a [`windowsHide` flag](https://nodejs.org/docs/latest-v16.x/api/child_process.html#child_processspawncommand-args-options) when spawning child processes.  I thought we didn't need it, but I guess I'm wrong (must be because `npm run dev` has a console window).  Just need to set it.

**Comment by gunamata** [comment]
another observation is that, on switching to Images tab, the command window flashes only when `containerd` is selected as the runtime. Not sure the `dockerd` mode takes a different codepath or approach to populate the images list.

**Comment by schoeppi5** [comment]
I am not sure, if this is already known or not.

After some digging, I found, that the window opened is the *docker-proxy* started [here](https://github.com/rancher-sandbox/rancher-desktop/blob/8c613269e68bb5ff9c4812d0ec853d8e9e627129/src/k8s-engine/wsl.ts#L1374) when enabeling the integration. (I was wondering, why my docker cli couldn't communicate with the daemon, since I disabled the integration to avoid the window opening up).

I would suggest some improvements here:
* the text in the UI (Expose Rancher Desktop's Kubernetes configuration to Windows Subsystem for Linux (WSL) distros) doesn't clearly reflect, that the docker proxy is coupled with this integration.
* Would it also be possible to proxy the containerd.sock (/run/docker/containerd/containerd.sock)?
* The docker.sock isn't getting cleaned up, if the integration is disabled. This would also clearify, that the socket isn't proxied, if the socket doens't exist
