### ISSUE TITLE
Suggestion for documentation - Hello World example

### ISSUE THREAD

**Issue by stephanwesten** [rancher-sandbox/rancher-desktop#1310]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It was not clear to me how to try-out Rancher Desktop. I m familiar with Kind and MiniKube and looked for getting started documentation to try it out on macOS Montery with m1.

### Proposed Solution

Document something like this - I know for sure there is room for improvement as containers are not my expertise:

Have Docker Desktop running because we will use docker to build the image.
(although the website says that you cannot have Docker Desktop and RD running)
Below, replace "username" with something of your choice.

Create a folder with a Dockerfile and the following content:
FROM alpine
CMD ["echo", "Hello username!"]

Build and run the image for verification purposes:
$ docker build -t username/hello:1_0 .
$ docker run --rm username/hello:1_0

$ docker images
should produce:

REPOSITORY                       TAG                    IMAGE ID       CREATED              SIZE
username/hello                    1_0                    cc0aa0f78337   About a minute ago   5.33MB

Also the UI of RD will show the images 

Deploy to RD:
$ kubectl create deployment hello-server --image=username/hello:1_0

Fetch logs
$ k logs hello-server-xyz -n default

**Comment by cnmade** [comment]
I suggest no more complex. just open a powershell windows or terminal windows  running 
```
docker run hello-world
```

Is it print hello world?


![image](https://user-images.githubusercontent.com/278153/150922992-5ae46b9f-f08c-4c6a-88aa-37f987b069b2.png)

**Comment by stephanwesten** [comment]
I created my own hello-world dockerfile. Using an existing one is of course easier but less insightful.

**Comment by cnmade** [comment]
I agree with you .  but for new user ,  learn a b c is very basic and easy to verify if the system up and running. 

For advance user , build image from Dockerfile will be easy, but for entry level user , not that easy.

How about put building image to an advance usage like: " How to Building image from Dockerfile "

**Comment by stephanwesten** [comment]
Sounds good. 

Just fyi - with Docker Desktop becoming a paid solution for large enterprises, some people are looking for alternatives. It is the building part that is the culprit. With Minikube people could already deploy.

**Comment by jtravee** [comment]
Need confirmation that the steps documented are correct and complete as is or should be updated?

**Comment by ericpromislow** [comment]
I'd say the steps in the Proposed Solution are close, but I'll propose a tweak in the next comment:

**Comment by ericpromislow** [comment]
This document shows how to get started with Rancher Desktop, pushing
an app to a local Kubernetes cluster.

Rancher Desktop works with two separate container engines, 
`containerd` and `Moby` (the open-sourced components of the Docker
ecosystem).

First, let's use Moby mode to create a container image and push it
to the cluster. In the text below,
replace "USERNAME" with something of your choice.

Create a folder with a Dockerfile and the following content:
```
FROM alpine
CMD ["echo", "Hello, USERNAME!"]
```

Build and run the image for verification purposes:

```
$ docker build -t USERNAME/hello:1.0 .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
latest: Pulling from library/alpine
59bf1c3509f3: Pull complete
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Downloaded newer image for alpine:latest
 ---> c059bfaa849c
Step 2/2 : CMD ["echo", "Hello snorpy"]
 ---> Running in f3860fdc4c4b
Removing intermediate container f3860fdc4c4b
 ---> 220f12cc2fbe
Successfully built 220f12cc2fbe
Successfully tagged USERNAME/hello:1.0

$ docker images | grep USERNAME

USERNAME/hello     1.0    220e12cc2fbe   32 seconds ago   5.59MB

$ docker run --rm USERNAME/hello:1.0

Hello, USERNAME
```

Also the UI of RD will show the new image (you could have built it there as well,
but since you're doing everything else at the command-line we might as well stay there).

This Dockerfile isn't really appropriate for Kubernetes, as it will start up,
run the echo command, and then shut down.
Most containers are designed for long-lived processes. So let's switch the UI to `containerd` mode and 
build a different image, suitable for Kubernetes. Note that if you are only interested in Docker,
you can stay in `Moby` mode and type the appropriate command in the following.

Switch the `Container Runtime` setting in the `Kubernetes Settings` panel from `dockerd (moby)` to `containerd`.

Now let's define our own nginx image, in a new directory:

```
$ mkdir ../test2
$ cd ../test2
$ cat > Dockerfile <<EOT
FROM nginx
EOT

$ nerdctl build -t USERNAME/nginx:1.0 .
[+] Building ...
...
=> => sending tarball                                                                                          2.5s
unpacking docker.io/morspin/nginx:1.0 (sha256:f129dcbc2038c8ad0f8d1a82e9111780327fb67c9e27f2c85dc7c9d7220ef0e1)...done
$ nerdctl images
REPOSITORY       TAG    IMAGE ID        CREATED           PLATFORM       SIZE         BLOB SIZE
morspin/nginx    1.0    f129dcbc2038    29 seconds ago    linux/amd64    149.1 MiB    54.1 MiB

$ nerdctl run -d -p 8080:80 USERNAME/nginx:1.0
$ nerdctl ps
CONTAINER ID    IMAGE                          COMMAND                   CREATED          STATUS    PORTS    NAMES
fd869b8e08c5    docker.io/morspin/nginx:1.0    "/docker-entrypoint.…"    8 seconds ago    Up                 nginx-fd869

```

Now point your web browser to `localhost:8080` and you should see the nginx intro screen. If you prefer to stay at the command-line, you can type `curl localhost:8080` and gaze at the classic HTML code.

To shut down:
```
$ nerdctl stop fd869b8e08c5 # the container ID has most likely changed
$ nerdctl ps
# Nothing should be running
```
