### ISSUE TITLE
Lima: resolve host.docker.internal

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#1316]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

We should be able to resolve `host.docker.internal` (and `host.minikube.internal`) on lima / macos.

### Proposed Solution

Something to do with the lima guest agent?

### Additional Information

See [docker documentation](https://docs.docker.com/desktop/mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host).

**Comment by jandubois** [comment]
This issue is about resolving the name from inside containers running inside the VM. The names are already resolved in the VM itself because they are added to `/etc/hosts`, but the Lima host-resolver doesn't know about them. Since coredns just picks the nameserver from `/etc/resolv.conf` and doesn't use a glibc resolver, it will not read `/etc/hosts`.
