### ISSUE TITLE
VSCode devcontainer "Clone Repository in Container Volume" not working

### ISSUE THREAD

**Issue by jonathaneckman** [rancher-sandbox/rancher-desktop#1318]
### Rancher Desktop Version

1.0.0-beta.1

### Rancher Desktop K8s Version

1.21.5

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2 19044.1466

### What CPU architecture are you using?

x64

### Windows User Only

No

### Actual Behavior

When launching a VS Code devcontainer using "Clone Repository in Container Volume", the clone step hangs. This occurs with a public repo from GitHub or a private AzDo repo. The same process works fine in Docker Desktop. Logs showing where it hangs:

```cmd
Start: Run in container: git clone --depth 1 https://github.com/microsoft/vscode-remote-try-node .
Cloning into '.'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 15 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (15/15), 13.92 KiB | 13.92 MiB/s, done.
```

When I kill RD or the container, I get the following error which may have more useful info:

![image](https://user-images.githubusercontent.com/11893200/150838879-43dff98c-08b1-4b45-8eda-c3b7c6a7b95b.png)

### Steps to Reproduce

With only Rancher Desktop running (not Docker Desktop), run the following (condensed steps from this quick start: https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume)

1. Start VS Code and run **Remote-Containers: Clone Repository in Container Volume...** from the Command Palette (F1).
2. Enter microsoft/vscode-remote-try-node (or one of the other "try" repositories), a Git URI, a GitHub branch URL, or a GitHub PR URL in the input box that appears and press Enter.
3. The VS Code window (instance) will reload and begin to clone the source code.
4. The clone never completes. The process hangs forever. 

### Result

The clone never completes. The process hangs forever. 

### Expected Behavior

The clone completes. The devcontainer is built.

**Comment by mook-as** [comment]
I believe this is fixed by #1374; I can successfully clone the repository (and `yarn install` succeeds).

Closing this; please let us know if this is still an issue and we can reopen! (Either using a [CI build](https://github.com/rancher-sandbox/rancher-desktop/actions/workflows/package.yaml?query=is%3Acompleted+branch%3Amain) or waiting for the next release, of course.)

**Comment by kamalrayaguru** [comment]
**Issue**

Tried out with Rancher Desktop 1.2.1 & Kubernetes 1.22.7(stable) on my Windows 10 laptop and tried opening the git repository in VS Code in a named container volume.  Cloning hangs forever.

![image](https://user-images.githubusercontent.com/94606107/162454143-e112a4b6-b4d4-474f-8b64-1e346f7c3fb6.png)

**Result**
The clone never completes. The process hangs forever.

**Expected Behavior**
The clone completes. The devcontainer is built.

**Comment by BitFis** [comment]
@kamalrayaguru check the vscode extension version, i had some issues about getting stuck with the DevContainers plugin aswell, downgrade maybe to an older version and check. Following worked for me: 
- Remote-Containers v0.231.5
- Rancher Desktop 1.2.1
- kubernetes 1.23.3
Also give it a try with the vscode example devcontainers

**Comment by jonathaneckman** [comment]
@BitFis thanks for the tip. Installing version 0.224.3 of the Remote - Containers extension resolved this for us. Note that the latest version of the extension works fine in Docker Desktop. It only fails when using Rancher Desktop and version 0.231.X of the Remote - Containers extension, so its possible there is still a Rancher Desktop related issue involved. 

https://github.com/microsoft/vscode-remote-release/issues/6590
