### ISSUE TITLE
[CI] Smoke Tests - Cross platform

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#1319]
POC only (probably, only opening and rendering the app on Windows and macOS will be possible - there's no kvm for those runners yet).
- [ ] Create simple smoke test (similar main.spec.ts)
- [ ] Update cirrus yaml, including cross platform matrix (Windows and macOS)

**Comment by jandubois** [comment]
We do have a `smoke-test` workflow on GitHub that will install the release artifacts for Linux, macOS (Intel), and Windows, starts Rancher Desktop and verifies that the backend will become ready. It also verifies the code signatures on macOS and Windows.

The same checks are done for macOS on M1, except the app cannot be started because the GitHub runners don't support nested virtualization.
