### ISSUE TITLE
[Issue] Very slow execution time of kubectl commands

### ISSUE THREAD

**Issue by avodaqstephan** [rancher-sandbox/rancher-desktop#1340]
### Rancher Desktop Version

1.0.0

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.2

### What CPU architecture are you using?

x64

### Actual Behavior

Hi folks, 

for some days I fought with the issue, that kubectl commands have been exectued really slow. I'd say 8-15sec for a `kubectl get po` or `kubectl get ns`. Additionally I get this messages every time I execute a kubectl command:

`I0126 15:59:57.903678    6956 versioner.go:56] Remote kubernetes server unreachable`
Sometimes as well
`Unable to connect to the server: dial tcp: lookup XYZ.hcp.germanywestcentral.azmk8s.io on 192.168.178.1:53: read udp 192.168.178.98:0->192.168.178.1:53: i/o timeout`

I used kubectl which was shipped with Rancher Desktop. Until today, I ran Rancher Desktop 0.7 but upgraded immediately to v1 after the release. However the problem still persists.

Today I just installed kubectl from the official [kubernetes.io](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/) page and used that binary to execute my `kubectl` commands. Way faster, no weird messages. Everything works like expected. Something seems to be off with the binary which gets shipped with Rancher Desktop or Rancher Desktop somehow interferes here. 

This does not apply to the local rancher desktop cluster!

### Steps to Reproduce

1. Make sure to not have kubectl installed: `which kubectl` should return something like `kubectl not found`
2. Install Rancher Desktop, go to the `Supporting Technologies` and tick `/usr/local/bin/kubectl`
3. Authenticate against any of your clusters (not the rancher desktop one! this one works fine)
4. Run a basic command like `kubectl get ns` and stop the time.

### Result

![image](https://user-images.githubusercontent.com/58725083/151234431-eca425d7-b183-46a9-9ac0-dfc790e58845.png)

With the shipped binary 14s

![image](https://user-images.githubusercontent.com/58725083/151234568-5b9ae4c0-b7d1-4654-a59b-aa9af5cdca12.png)

With the kubernetes.io one 6s.

### Expected Behavior

I expect a fast and reliable execution time of `kubectl` commands.

### Workaround

To solve this issue, I unticked the `kubectl` in the Rancher Desktop settings, which automatically removes the binary in `/usr/local/bin` and manually installed the kubectl-cli from kubernetes.io. Works like a charm. Much faster.

### Additional Information

I just want to add a big *Thank you* to the whole time, for providing us such a great tool as the perfect alternative for Docker Desktop!

Cheerio, 
Stephan

**Comment by jandubois** [comment]
The root cause for the delay is that Rancher Desktop ships with the [kuberlr](https://github.com/flavio/kuberlr) wrapper for `kubectl`. Officially `kubectl` only supports one version older and one version newer than its own version. E.g. `kubectl` 1.20 can talk to 1.19, 1.20, and 1.21. It is possible that it doesn't work for 1.18,  or 1.22 (although in practice for most use cases it still works fine).

Anyways, so `kuberlr` connects to the api server to query the current server version, and then downloads a compatible `kubectl` version, if there isn't one in the cache already. So this can sometimes introduce a delay when an additional download needs to happen, but most of the time should be unnoticeable.

But of course a problem occurs when the current cluster (as configured in your kube context) is not reachable. Then you wait until the `kuberlr` version check times out, and just uses the latest local version anyways.

So it sounds like your cluster is actually reachable by `kubectl` itself, so this seems to be a bug in the way `kuberlr` tries to connect. It uses the upstream library to do so (same as `kubectl`), so this is somewhat surprising. Can you look at your cluster configurations, and see if there is something different about them, that could be causing this?

**Comment by avodaqstephan** [comment]
@jandubois Thank you for looking into this. I'm happy to provide more information.

I tested it with 2 different clusters again.

- 1x AWS with a public API endpoint, v1.18
- 1x Azure with a private API endpoint, v1.22.2

Azure: It doesn't matter which `kubectl` I'm using, for Azure both are responding in pretty much the same time (6-9s for a simple `get ns`). Still, "native" `kubectl` is always a tick faster.

AWS: Takes a noticeable amount of time longer compared to Azure, around 12-15sec. But again, it doesn't matter which `kubectl`. Really weird that EKS is that slow, I'll need to look into this.

So with these information I'm down to say, it was either a network issue on my side / cooperate VPN or the Rancher Desktop v1.0.1 shipped an update for `kubectl` but I can't find anything in the release notes.

I'll close the issue because I can't reproduce it anymore. Thanks again @jandubois

**Comment by jandubois** [comment]
> Still, "native" `kubectl` is always a tick faster.

Yes, because it save the first network round-trip when kuberlr queries the cluster version before delegating to the kubectl binary. So the wrapper will always be slightly slower, but the difference should be pretty small.
