### ISSUE TITLE
nerdctl version still v0.16.0 on Rancher Desktop 1.0.1

### ISSUE THREAD

**Issue by ciechonp** [rancher-sandbox/rancher-desktop#1474]
### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Big Sur 11.4 

### What CPU architecture are you using?

x64

### Actual Behavior

After upgrading Rancher Desktop from 1.0.0 to 1.0.1 there is still nerdctl version v0.16.0 which is having issues login in to nexus.

### Steps to Reproduce

Install Rancher Desktop 1.0.1

### Result

```
nerdctl version
Client:
 Version:	v0.16.0
 Git commit:	0ddaffd2ce304dd917267470883898feff9463dc

Server:
 containerd:
  Version:	v1.5.9-k3s1
  GitCommit
```

### Expected Behavior

nerdctl version v0.16.1

**Comment by ciechonp** [comment]
I have manually removed~/Library/Application Support/Rancher Desktop and ~/Library/Application Support/rancher-desktop after that I have reinstalled Rancher Desktop 1.0.1 and now I can see that nerdctl version is v16.0.1.

**Comment by jandubois** [comment]
Thank you for reporting this issue. It is actually a bug that `nerdctl` isn't updated when you already have an existing VM, so I'm going to re-open the bug.

The underlying issue is that `nerdctl` is stored under `/usr/local/bin`, which is migrated to the persistent data volume on first boot. Any changes to `/usr/local/bin` in the ISO image should be copied over to the volume, but currently aren't.
