### ISSUE TITLE
Don't allow running as root

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1560]
There has been some misleading advice in some of the comments, suggesting to run Rancher Desktop as `root` (on macOS) to avoid having to make `/usr/local/bin` writable by the current user.

This can create all manner of problems because now other files and directories will be created as `root` and no longer be accessible when not running as `root` any more, see e.g. https://github.com/rancher-sandbox/rancher-desktop/issues/932#issuecomment-1034048619.

I think Rancher Desktop should check very early (before creating directories or log files) if it is running as `root`, and displaying an error dialog, and then aborting.

**Comment by jandubois** [comment]
See #2135 for an example that this affects Windows as well

**Comment by adamkpickering** [comment]
An update regarding Linux: it appears that it is not possible to run RD with `sudo` on the command line. I tried `sudo rancher-desktop`, which failed with the following message:
```
[0817/110827.913682:FATAL:electron_main_delegate.cc(292)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```
I also tried `sudo rancher-desktop --no-sandbox`, which gets partway to a successful startup and then hangs. All that is produced is a blank window.

So, I think it's safe to say that we don't need to make changes for this issue for Linux. I will include the same check as for macOS anyways, because it is easy and something may change in the future.

**Comment by wordscode** [comment]
linux root用户不能运行 RD，虽然命令行启动是有提示的，但是我点击图标启动好像无响应？GUI也应该添加这个提示
![image](https://github.com/rancher-sandbox/rancher-desktop/assets/75980075/f32d150d-43ba-4165-bcbd-83b0f28e870e)

**Comment by jandubois** [comment]
>The linux root user cannot run RD. Although there is a prompt to start the command line, it seems that there is no response when I click the icon to start? The GUI should also add this hint

@dpmerrill Can you please check if the dialog is not displayed when you start the app via the app icon instead of from the commandline?

**Comment by dpmerrill** [comment]
Created issue #5211 to be specific to starting RD from the Linux desktop as root.  Starting from the command line, the dialog works as designed so I doubt this is a regression.
