### ISSUE TITLE
Running nerdctl build with Rancher Desktop fails to pull base images from a private registry with self-signed cert

### ISSUE THREAD

**Issue by Elektronenvolt** [rancher-sandbox/rancher-desktop#1572]
### Actual Behavior

Follow up to: https://github.com/rancher-sandbox/rancher-desktop/issues/909

Using `nerdctl build` with Rancher Desktop on Windows + WSL involves pulling a base image from a private registry which uses a self-signed corporate cert, and the error is x509: certificate signed by unknown authority. I have the root CA certs on the Windows host machine as well at the rancher-desktop WSL under `/usr/local/share/ca-certificates`. 

![image](https://user-images.githubusercontent.com/6702311/153576959-d172b022-9e62-4343-a135-09ff94824c33.png)

At image pull I can use as workaround `nerdctl pull --insecure-registry <private-registry>/<image-name>` but at image build this doesn't help.
![image](https://user-images.githubusercontent.com/6702311/153577465-b997d243-3a9b-4f7f-a580-7eb5d1fd8239.png)

### Steps to Reproduce

Install Rancher Desktop on Windows 10 (21H2) + WSL and pull an image from an private registry with a self signed certificate.

### Result

Can't pull image without `--insecure-registry`

### Expected Behavior

Allow to use self signed root CA certificates.

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.22.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

21H2

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
> I have the root CA certs on the Windows host machine 

What does that mean? Does your certificate show up in this list:

<img width="976" alt="Screen Shot 2022-02-11 at 12 15 12 PM" src="https://user-images.githubusercontent.com/78947/153663752-253912b9-26fe-4857-b8dd-b39ee1ca05ee.png">

is the "Intended Purpose" set to "All" or at least include "Server Authentication"?

I've shown in https://github.com/rancher-sandbox/rancher-desktop/issues/909#issuecomment-1032070478 that things worked for me as soon as I installed the cert (and restarted Rancher Desktop), so I can't tell what is different in your situation.

For my test I used [distribution](https://github.com/distribution/distribution) to set up the private registry with a self-signed cert. Maybe you have a different implementation with additional requirements, but I obviously can't know about that.

The simplest explanation is still that you did not install the correct root certificate.

**Comment by Elektronenvolt** [comment]
@jandubois - I'm not sure if there is a need to care about the installed root CA certs at the Windows host. In our case these certs are distributed by a group policy - if they are not installed, the same error would show up on many other places.

The image pull happens in WSL - I've imported now all certs I've found at the rancher-desktop WSL. And yes, your right - a missing root certificate.
My steps:
`wsl -d rancher-desktop`
`cd /usr/local/share/ca-certificates`
`get all root CA certs>`
`chmod 755 root-ca-cert.crt`
`update-ca-certificates`
and restart Rancher Desktop

Thanks for checking this again.

**Comment by jandubois** [comment]
> @jandubois - I'm not sure if there is a need to care about the installed root CA certs at the Windows host. In our case these certs are distributed by a group policy - if they are not installed, the same error would show up on many other places.

@Elektronenvolt That's why I've asked how/where those certs are installed in Windows. If they are installed as trusted root certs, they are automatically installed inside WSL as well, and everything works.

So maybe your policy installs them as 3rd party certs, and RD doesn't pick them up. So maybe there is some other location certs should be picked from. But unless somebody actually says how/where they installed the certs, there isn't really anything we can do beyond saying: "If you install them as trusted root certs, it works!".

**Comment by Elektronenvolt** [comment]
@jandubois Thanks - was not aware that root CA certs already get installed inside the WSL as well. 

I did a lot of tests now, and the issue I have comes from an intermediate cert.
![image](https://user-images.githubusercontent.com/6702311/153873945-ec9c1b25-70a5-48a9-8525-f6d786e12134.png)

If I export the intermediate cert and import it to trusted root certs - everything works fine.
![image](https://user-images.githubusercontent.com/6702311/153874743-dc9fc58e-a5f9-48fb-8014-bdfa3fd08988.png)

**Comment by jandubois** [comment]
@Elektronenvolt Was the intermediate cert installed by policy into "Intermediate Certification Authorities"?

Maybe those certs should be imported into the VM automatically as well.

**Comment by jandubois** [comment]
> Maybe those certs should be imported into the VM automatically as well.

@mook-as I think we need to import the `CA` trust store instead of `ROOT`:

https://github.com/ukoloff/win-ca/blob/add29e8ab74649627831d7cccd9fd75c833457b1/n-api/crypt32.cpp#L37-L40

The module seems to support this:

>* store - which Windows' store to use. Default is Root (ie Trusted Root Certification Authorities).
>
>  Windows has a whole lot of Certificate stores (eg Root, CA, My, TrustedPublisher etc.) One can list certificates from any of them (knowing its name) or several stores at once (using array for store parameter).
>
>   ```
>     var list = []
>     require('win-ca/api')({store: ['root', 'ca'], ondata: list})
>   ```

I would have expected `ca` to be a superset of `root`, so specifying both shouldn't be necessary: [CertOpenSystemStore](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certopensystemstorea#parameters), but that needs verification.

Re-opening this because I think this is a bug.

**Comment by mook-as** [comment]
Checking on my Windows install (using PowerShell, since I can interactively browse `cert:` there), it looks like `ca` is _just_ the _Intermediate Certification Authorities_ list, and not a superset, so we'll need both.

I also notice a cert in there (_Microsoft TPM Root Certificate Authority 2014_) that is self-signed, so I have no idea why it's listed under _Intermediate_…

Anyway, I believe that means we need to include both.

**Comment by Elektronenvolt** [comment]
@jandubois - yes, installed by a group policy into "Intermediate Certification Authority Certificates"

![image](https://user-images.githubusercontent.com/6702311/154094455-6d09fff9-c55e-4b66-8941-437f87127020.png)

**Comment by crumdev** [comment]
I can confirm, our company also uses an intermediate CA that gets installed in the Intermediate Certification Authorities>Certificates directory by group policy. This is why the default import RD performs did not work for us.

**Comment by jandubois** [comment]
@crumdev Since 1.1.0 started importing the intermediate CAs too, has this problem been fixed for you now?

**Comment by crumdev** [comment]
@jandubois I just made sure to remove my manually added certs, closed and reopened the app and it appears to be working after the upgrade. Thanks for all the improvements your team keeps making.
