### ISSUE TITLE
After installing Rancher Desktop on Apple M1 with containerd, nerdctl is not available

### ISSUE THREAD

**Issue by jcaporossi-ledger** [rancher-sandbox/rancher-desktop#1597]
### Actual Behavior

nerdctl --help
zsh: command not found: nerdctl

### Steps to Reproduce

Install Rancher Desktop
Launch Rancher Desktop
Open terminal
nerdctl --help

### Result

zsh: command not found: nerdctl

### Expected Behavior

Display nerdctl help

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.22.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

mac os monterey 12.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by adamkpickering** [comment]
Can you please do a couple of sanity checks:
- What does the `Supporting Utilities` tab look like? Are you able to check the `nerdctl` checkbox? If it is grayed out, that means that RD sees something called `nerdctl` somewhere in RD's `PATH`.
- Is `/usr/local/bin/` (which is where RD installs `nerdctl` on macOS) in your `PATH`?

Note that `PATH` may differ between RD and your shell due to how it is set. Are you doing any atypical things with your `PATH` variable?

**Comment by jcaporossi-ledger** [comment]
Hi,

 I have finally managed to use nerdctl. I have deleted the link in /usr/local/bin/nerdctl and reset kubernetes. Now it works...
