### ISSUE TITLE
SSH forward in nerdctl build on Windows 11

### ISSUE THREAD

**Issue by ahjulstad** [rancher-sandbox/rancher-desktop#1649]
### Actual Behavior

`nerdctl build --ssh default` on Windows 11 is not able to look at `SSH_AUTH_SOCK` to locate ssh-agent, nor is it able to access the socket if I specify it manually. 

 

### Steps to Reproduce

On Windows 11, starting ssh-agent, then
```
nerdctl build --ssh default
```

### Result

Error message about `SSH_AUTH_SOCK` not set

### Expected Behavior

Make ssh-agent available to image build process. 

### Additional Information

The purpose is to check out a git repository during build that is protected by a ssh deploy key. I first asked a question [here](https://github.com/containerd/nerdctl/discussions/829), but got pointed in this direction. 

### Rancher Desktop Version

1.0.1

### Rancher Desktop K8s Version

1.23.3

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 21H2, 22000.493

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
Random hypothesizing: we actually have to translate the command line and launch `nerdctl` in the WSL container instead (done via [`nerdctl-stub`](https://github.com/rancher-sandbox/rancher-desktop/tree/main/src/go/nerdctl-stub)); in this process we're not sending `SSH_AUTH_SOCK` over (we need to add `SSH_AUTH_SOCK/up` to `WSLENV`).  Note that wouldn't _actually_ work, because your `SSH_AUTH_SOCK` is probably `npipe://something` or `\\.\pipe\something`, or anything else that isn't a Unix socket on the Windows file system (I'm not even sure if that's a thing).

So there's 2 parts:
- Windows (cmd.exe / powershell.exe): what is your `SSH_AUTH_SOCK` set to? That is, how should we attempt to translate it?
- Linux (WSL container): we need to treat `SSH_AUTH_SOCK` as a file path (and to a bit of bind mounting magic).

**Comment by ahjulstad** [comment]
Not sure if it helps, but: on windows, my SSH_AUTH_DOCK is for example /tmp/ssh-ZsH2s7pux6is/agent.291


-------------------------------------------------------------------
The information contained in this message may be CONFIDENTIAL and is
intended for the addressee only. Any unauthorized use, dissemination of the
information or copying of this message is prohibited. If you are not the
addressee, please notify the sender immediately by return e-mail and delete
this message.
Thank you

**Comment by mook-as** [comment]
Wait, on _Windows_ (that is, via `cmd.exe` or `powershell.exe`, and not a WSL bash or whatever) it contains a path to `/tmp`?

That's… odd, but okay? I'm not sure how to interpret that as a Windows path.

**Comment by ahjulstad** [comment]
I am confusing myself, sorry. The environment variable is indeed in windows, and appears when running 'start-ssh-agent', which comes from git (I have it in `C:\Program Files\Git\cmd\start-ssh-agent.cmd`), whereas the windows 11 openssh install is in `C:\Windows\System32\OpenSSH\ssh.exe`

Looks like I am not the first struggling with this: https://github.com/docker/for-win/issues/167


-------------------------------------------------------------------
The information contained in this message may be CONFIDENTIAL and is
intended for the addressee only. Any unauthorized use, dissemination of the
information or copying of this message is prohibited. If you are not the
addressee, please notify the sender immediately by return e-mail and delete
this message.
Thank you

**Comment by mook-as** [comment]
Oh, well, in that case I don't think there's much we can do: that's a path for the git bundled msys2 distribution. (Which actually mounts `%TEMP%`, i.e. `C:\Users\<>\App\Local\Temp`, into `/tmp`).  That set of emulated Unix mounts is completely unrelated to the WSL paths, and even if we _did_ try to map it, it wouldn't be recognized as a Unix socket inside WSL (so the ssh agent wouldn't work).

It looks like [Stack Overflow](https://stackoverflow.com/questions/23086038/) has a description of the msys Unix socket emulation format.  That's totally not doable in our case, I believe.

So I think that:
- there's nothing we can do here (because we can't fake the msys socket in any way); so I'll close this issue.
- I filed https://github.com/rancher-sandbox/rancher-desktop/issues/1667 to handle the Windows-native ssh agent (that is, the Win32 service talking to `\Device\NamedPipe\openssh-ssh-agent`).  However, ① this isn't what you're reporting, and ② we probably wouldn't implement this any time soon.
