### ISSUE TITLE
Produce SUSE signed images for Windows

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#166]

**Comment by evrardjp** [comment]
Hey. I am helping @alfsuse on building a SUSE image for AI. I think we might benefit from collaboration. I already spoke to our WSL folks on how to build an WSL image, but I didn't produce one with kiwi yet.
Where are you in your progress, as it doesn't seem to be shown here?
Do you want to collaborate on this? I am happy to transfer my work to you, so that we are not building expertise in silos, but instead make sure the `rd` team is the best at dealing with those WSL images.
