### ISSUE TITLE
Rancher Desktop doesn't show up after it's closed

### ISSUE THREAD

**Issue by cdivita** [rancher-sandbox/rancher-desktop#1677]
On Man OS (Monterey 12.2.1) I would close Rancher Desktop in order to stop the cluster and the related resources (like the Lima VM, etc) but after I close Rancher Desktop it's not possible to open it again.

While everything continue to work, while my goal is to stop everything, after closing Rancher Desktop is not possible to restart it: the only way is rebooting.

**Comment by evertonlperes** [comment]
Thanks for filing the issue @cdivita 
If you close the RD app throught the UI ("X" button), it will keep running in the background. In order to open the UI again, you need to navigate to your system tray, right-click `Preferences` and then the UI will open again.

We are improving the UX along the way and I encourage you to open a [Feature Request ](https://github.com/rancher-sandbox/rancher-desktop/issues/new?assignees=&labels=kind%2Fenhancement&template=feature_request.yml)(using the pre-filled template)
Closing this for now.
