### ISSUE TITLE
`Supporting Utilities` doesn't offer `docker-compose` 

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#1707]
### Actual Behavior

There's no:

- [ ] docker-compose
- [ ] docker-buildx

### Steps to Reproduce

1. Let Rancher Desktop upgrade from 1.0.1 to 1.1.0
2. Open Rancher Desktop
3. Go to Supporting Utilities
4. Look for `docker-compose`
5. Note that if `docker-compose` is in path (`/usr/local/bin`), naive shell completion will find it

### Result

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/2119212/156625382-d929db2a-99f7-42c0-9673-b4bfcdf768a1.png">

### Expected Behavior

Allow managing the `docker-compose` symlink

#### Basic introspection

```sh
jsoref@IEUsers-MacBook-Pro bin % cd /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin
jsoref@IEUsers-MacBook-Pro bin % ls
docker		docker-buildx	docker-compose	helm		kubectl		kuberlr		nerdctl		steve
jsoref@IEUsers-MacBook-Pro bin % ls -l /usr/local/bin|grep ancher
lrwxr-xr-x  1 jsoref  admin     80 Jan 28 09:55 docker -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker
lrwxr-xr-x  1 jsoref  admin     81 Jan 28 09:55 kubectl -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl
lrwxr-xr-x  1 jsoref  admin     81 Jan 28 09:55 nerdctl -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/nerdctl
jsoref@IEUsers-MacBook-Pro bin % ls -l ~/.docker/cli-plugins
total 0
lrwxr-xr-x  1 jsoref  staff  83 Mar  3 09:01 docker-buildx -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/docker-buildx
lrwxr-xr-x  1 jsoref  staff  88 Mar  3 09:01 docker-compose -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-compose
```

#### Installing docker completion helps once I start a new terminal
```sh
jsoref@IEUsers-MacBook-Pro bin % brew install docker-completion
```

### Rancher Desktop Version

1.1.0

### Rancher Desktop K8s Version

(Off)

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Big Sur 11.6.4

### What CPU architecture are you using?

x64

**Comment by ericpromislow** [comment]
Actually, the `docker-compose` and `docker-buildx` plugins go in to `~/.docker/cli-plugins` on macOS and Linux. And they tag along with whatever choice is made for `docker`.  There's also a bug on `docker-buildx` with a workaround at https://github.com/rancher-sandbox/rancher-desktop/issues/1708

We didn't include separate checkboxes for the two plugins in order to keep the UI simpler.

Also we didn't put the plugins in `/usr/local/bin` because the new ("docker V2") way of using the plugins is to use the plugin form `docker compose` or `docker buildx`  and not the V1 `docker-compose` or `docker-buildx` respectively. From my experience on working on a CLI with a plugin architecture, this way leads to more consistency for both users and plugin developers, but that's an aside.

I'm going to close this issue because we're actually in the process of discussing a more consistent way of handling symlinks going forward. The current system has just evolved ad hoc, and it's time to revisit it.

**Comment by jsoref** [comment]
The reason I filed this is that some portion of my users still somehow managed to have a thing where when I asked them to try `docker compose`, they said it didn't work, whereas `docker-compose` did work for them, and thus all of our documentation still has to say `docker-compose` as it's the lowest-common denominator.

I suppose I can go try to figure out which user that was and why it was that `docker compose` didn't work (which is probably roughly equivalent to _Where did you get your `docker` from?_).

**Comment by ericpromislow** [comment]
I'm reopening this as part of our re-review of this area.

It sounds like the `docker-compose` plugin should go into both the path and the plugin dir.

I haven't looked at the internals, but the only way I can see a standalone `docker-compose` failing to run one day is if Docker completely changes the API the CLI backend uses. But that sounds fairly drastic. Maybe they'll simply notch the URLs of the API by one version and stop supporting the earlier one that legacy clients would be using. But that still seems fairly drastic to spite a small number of pseudo-plugins (my term for a directly runnable `docker-compose` implementation, for example).

**Comment by jandubois** [comment]
I believe this is all done. Please file bugs if it doesn't work.
