### ISSUE TITLE
Research what other CLIs require if they have a plugin path

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#1716]
### Problem Description

Per discussion from https://github.com/rancher-sandbox/rancher-desktop/discussions/1512, we need to handle cases where another CLI has a plugins path into Rancher Desktop. This may mean another symlink.

### Proposed Solution

TBD

**Comment by ericpromislow** [comment]
I'm just going to discuss the Docker CLI for now, which caused a few problems when we started to build in support for the `docker-compose` plugin.

V1 of the Docker CLI supported standalone "plugins", that aren't exactly plugins. They're standalone executables that users run directly, as in:
```
$ docker-compose up ARGS...
```

The most convenient way to access a plugin is by putting it on the path.

V2 of the Docker CLI supports discoverable plugins that the CLI finds by scanning a specific directory, `~/.docker/cli-plugins` on macos/linux, and something similar on Windows, and adds the commands that any plugins there implement to the core UI, so now the user would type:

```
$ docker compose up ARGS...
```

Notice the space after `docker`. I would expect this is done so plugin providers can give their users the same CLI experience they get from the core Docker commands. 

## Docker symlinks and Rancher Desktop Integrations

### On a new system - establishing the desired case

Create a symlink from `RESOURCE/PLATFORM/bin/docker-{compose,buildx}` into `~/.docker/cli-plugins`.

We can also consider symlinking each file into `/usr/local/bin/` (or something like `~/.rd/bin` moving forward) because although the docker specs don't suggest this, it looks like you can directly execute them using the old command name, like `docker-compose`.

### On existing systems

When integrations are off, and there are symlinks in the above directories pointing to `RESOURCE/PLATFORM/bin/SELF`, they can be safely deleted. Otherwise, they should be left as is, assuming some other app owns them.

When integrations are on, we do more or less the same as in the above case. If the target symlink exists, do nothing. Either it's a link pointing into our own `RESOURCE` area and wasn't deleted earlier, or it points elsewhere, meaning we don't own it and shouldn't control it. If the target symlink doesn't exist, simply create it.

### A note on command-line completion:

Command-line completion and Docker plugins:
- In the `docker-compose` world, users would download and install a shell script from github and install it in `/etc/bash_completion.d` on Linux, `/usr/local/etc/bash_completion.d/` on macOS, and get command-line completion on the `docker-compose` command.
- I haven't found any docs on how to get command-line-completion to work for plugins.
-

**Comment by adamkpickering** [comment]
Closing since we've addressed what we need for #1732. If we need to consider plugins for other CLIs we can reopen this or create a new issue.
