### ISSUE TITLE
Investigate ~/.config/environment.d

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#1718]
### Problem Description

Based on https://github.com/rancher-sandbox/rancher-desktop/discussions/1512, we should look into relying on `~/.config/environment.d` to help manage paths and symlinks.

@colstrom to research. @adamkpickering is curious to follow

### Proposed Solution

TBD

**Comment by colstrom** [comment]
# Test System Information

```
❯ awk '/^(NAME|VERSION_ID)=/' /etc/os-release
NAME="Clear Linux OS"
VERSION_ID=35970

❯ uname -a
Linux clr-cc70b736cb04447891e67d43c4336971 5.16.12-1129.native #1 SMP Wed Mar 2 04:03:46 PST 2022 x86_64 GNU/Linux

❯ systemctl --version
systemd 249 (249)

❯ ssh -V
OpenSSH_8.9p1, OpenSSL 1.1.1m  14 Dec 2021

❯ getent passwd (whoami) | awk -F: '{ login_shell=$7; print login_shell }'
/usr/bin/fish

❯ fish --version
fish, version 3.3.1

❯ tmux -V
tmux 3.2a
```

# Scenario:

```
❯ cat /etc/environment
ETC_ENVIRONMENT_LOADED=true

❯ cat /etc/environment.d/00-etc-environment-d.conf
ETC_ENVIRONMENT_D_LOADED=true

❯ cat /usr/lib/environment.d/02-usr-lib-environment-d.conf
USR_LIB_ENVIRONMENT_D_LOADED=true

❯ cat ~/.config/environment.d/04-home-config-environment-d.conf
HOME_CONFIG_ENVIRONMENT_D_LOADED=true

❯ systemctl set-environment --user SYSTEMCTL_SET_ENVIRONMENT__USER_LOADED=true

> sudo systemctl set-environment SYSTEMCTL_SET_ENVIRONMENT_LOADED=true

```

- `/run/environment.d/01-run-environment-d.conf` is omitted from these results, because does not persist across reboots, and I didn't bother to recreate it.

# Results:

## Logging in over SSH:

Is the environment configured?

```
❯ env | fgrep LOADED | wc -l
0
```

Nope.

Is systemd noticing the files?

```
❯ /usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator | fgrep LOADED
ETC_ENVIRONMENT_D_LOADED=true
USR_LIB_ENVIRONMENT_D_LOADED=true
HOME_CONFIG_ENVIRONMENT_D_LOADED=true
```

Yep.

Is systemd passing any of these around?

```
❯ systemctl show-environment | fgrep LOADED
SYSTEMCTL_SET_ENVIRONMENT_LOADED=true
```

Just that one? Maybe the others are bound to the systemd user instance?

```
❯ systemctl show-environment --user | fgrep LOADED | wc -l
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
0
```

Aha! `sshd` does not use a systemd user instance. This is mentioned in a note under "applicability" in `man 5 environment.d`.

## Logging in to a local console:

Starting from where there was a userful error over SSH...

```
❯ systemctl show-environment --user | fgrep LOADED
SYSTEMCTL_SET_ENVIRONMENT__USER_LOADED=true
ETC_ENVIRONMENT_D_LOADED=true
USR_LIB_ENVIRONMENT_D_LOADED=true
HOME_CONFIG_ENVIRONMENT_D_LOADED=true
```

Looks good. Where's `SYSTEMCTL_SET_ENVIRONMENT_LOADED`? Does that not propagate to the user instance?

```
❯ systemctl show-environment | fgrep LOADED
SYSTEMCTL_SET_ENVIRONMENT_LOADED=true
```

Ah, there it is.

Wait, that wasn't in the generator output before... is it now?

```
❯ /usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator | fgrep LOADED
ETC_ENVIRONMENT_D_LOADED=true
USR_LIB_ENVIRONMENT_D_LOADED=true
HOME_CONFIG_ENVIRONMENT_D_LOADED=true
```

Nope.

Takeaway: `system-environment-d-generator` just deals with the files. Good to know.

Also observed, without captured output:
  - Setting things with `systemctl set-environment` propagates across new and existing console sessions. For the specific variables used here:
    - `SYSTEMCTL_SET_ENVIRONMENT_LOADED` persists until reboot.
    - `SYSTEMCTL_SET_ENVIRONMENT__USER_LOADED` persists as long as at least one session exists. This is important, because if something like `tmux` or `screen` is detached within the systemd user instance, the environment will persist.

# Bonus Round: dotfiles and profiles

Let's try something similar with all the various profile/rc/dotfiles for these shells.

`fish` is different, and it seems unreasonable to expect anything else to read `$XDG_CONFIG_HOME/fish/config.fish`.

## Relevant Additional Test System Information

```
❯ zsh --version
zsh 5.8.1 (x86_64-generic-linux-gnu)

❯ bash --version | head -n1
GNU bash, version 5.1.16(1)-release (x86_64-generic-linux-gnu)

❯ realpath /bin/sh
/usr/bin/bash
```

## Scenario

Created similar entries to the `environment.d` entries above, in all the places where shells read from. Creation steps omitted, but you can infer from variable names that follow the same pattern as above.

- `/etc/profile`
- `/etc/profile.d/testcase`
- `$HOME/.bash_profile`
- `$HOME/.bashrc`
- `$ZDOTDIR` is unset, and thus `$HOME`.
- `$ZDOTDIR/.zshenv`
- `$ZDOTDIR/.zprofile`
- `$ZDOTDIR/.zshrc`
- `$ZDOTDIR/.zlogin`
- `$ZDOTDIR/.zshenv`
- `$ZDOTDIR/.zprofile`
- `$ZDOTDIR/.zshrc`
- `$ZDOTDIR/.zlogin`

## Non-Login Shells

```
❯ env -i fish -c env | fgrep LOADED | wc -l
0

❯ env -i zsh -c env | fgrep LOADED
ETC_ZSHENV_LOADED=true
ZDOTDIR_ZSHENV_LOADED=true

❯ env -i bash -c env | fgrep LOADED | wc -l
0

❯ env -i /bin/sh -c env | fgrep LOADED | wc -l
0
```

## Login Shells

```
❯ env -i fish --login -c env | fgrep LOADED | wc -l
0

❯ env -i zsh --login -c env | fgrep LOADED
ETC_ZSHENV_LOADED=true
ZDOTDIR_ZSHENV_LOADED=true
ZDOTDIR_ZPROFILE_LOADED=true
ETC_ZLOGIN_LOADED=true
ZDOTDIR_ZLOGIN_LOADED=true

❯ env -i bash --login -c env | fgrep LOADED
ETC_PROFILE_D_LOADED=true
ETC_PROFILE_LOADED=true
HOME_BASH_PROFILE_LOADED=true

❯ env -i /bin/sh --login -c env | fgrep LOADED
ETC_PROFILE_D_LOADED=true
ETC_PROFILE_LOADED=true
HOME_PROFILE_LOADED=true
HOME_BASHRC_LOADED=true
```

## Other Variations

Does `--restricted` affect which files are read?

```
❯ env -i zsh --login --restricted -c env | fgrep LOADED
ETC_ZSHENV_LOADED=true
ZDOTDIR_ZSHENV_LOADED=true
ZDOTDIR_ZPROFILE_LOADED=true
ETC_ZLOGIN_LOADED=true
ZDOTDIR_ZLOGIN_LOADED=true

❯ env -i bash --login --restricted -c env | fgrep LOADED
ETC_PROFILE_D_LOADED=true
ETC_PROFILE_LOADED=true
HOME_BASH_PROFILE_LOADED=true
```

Nope.

`bash` also has some additional options.

```
❯ env -i bash --login --norc -c env | fgrep LOADED
ETC_PROFILE_D_LOADED=true
ETC_PROFILE_LOADED=true
HOME_BASH_PROFILE_LOADED=true

❯ env -i bash --login --noprofile -c env | fgrep LOADED | wc -l
0

❯ env -i bash --login --posix -c env | fgrep LOADED | wc -l
0
```

# Year of the Linux Desktop

So, everything up to this point has been either SSH, or local consoles. No desktop environment. This part is at the bottom, so it's easier to find instead of scrolling through the wall of text above.


## Relevant Additional Test System Information

```
❯ Xorg -version
X.Org X Server 1.21.1.3

❯ gdm --version
GDM 41.3

❯ gnome-shell --version
GNOME Shell 41.4

❯ gnome-terminal --version
# GNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD
```

## Scenario

Log in and open the default terminal.

## Results

```
❯ env | fgrep LOADED
HOME_BASHRC_LOADED=true
HOME_CONFIG_ENVIRONMENT_D_LOADED=true
HOME_PROFILE_LOADED=true
SYSTEMCTL_SET_ENVIRONMENT_LOADED=true
ETC_PROFILE_D_LOADED=true
SYSTEMCTL_SET_ENVIRONMENT__USER_LOADED=true
USR_LIB_ENVIRONMENT_D_LOADED=true
ETC_ENVIRONMENT_D_LOADED=true
ETC_PROFILE_LOADED=true
```

Everything works as expected.

However... this is where the big wall of text becomes relevant. I'm using `fish` as my login shell. `fish` doesn't load those things, so something else is in play. 

Armed with the variations above, we can infer that `/bin/sh --login` was somewhere in the ancestry of that `gnome-terminal` instance.

Even when explicitly told not to launch a login shell, and to launch a specific command instead. 

I also tested with a different terminal (Alacritty), and found the same thing. So it's likely something in the process tree prior to the terminal emulator itself.

This means that launching a new shell does **not** pick up changes to the profile files. Logging out appears to. That's not ideal.

Changes to the `environment.d` files are **available** via either `systemctl show-environment --user`, or `systemd-environment-d-generator`, but the environment is not updated  in place, nor is it when launching a new shell, for the same reasons as the profile files.

# Conclusion

It's complicated, there's no file that is actually read by all shells. Whether this is a login shell or not, connected via SSH or Local Console or Desktop Terminal Emulator... all of these things play a role.

There's a lot of flexiblity in how we approach this, but I don't see a silver bullet here. The most **reliable, cross-shell, desktop-neutral** approach is to dump a file in `~/.config/environment.d` and tell the user to reboot. This will work every time, on every distro (that uses `systemd`), in every shell, under every desktop environment (probably, haven't confirmed that).

It will not work if the user is connecting via `ssh`. It will not work if the user has custom stuff in their shell config that **overwrites** the path passed in via environment.

Logging out may not be sufficient, because the systemd user instance persists if there is a detached/background process. Something like... a container runtime.

How do we feel about this?

**Comment by jandubois** [comment]
@colstrom One question we had was if it was possible to use this mechanism to prepend or append a directory to the `PATH`. According to the documentation this should work, but neither @adamkpickering nor me could make it do that.

Did you manage to figure out how to make it do that? If this isn't possible, then this mechanism is not going to help us anyways.
