### ISSUE TITLE
Document Windows provisioning scripts.

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#1771]
We added provisioning scripts for Windows in #1576; we should document them.  I'm filing this as a staging area for working out the details we should document.

---

#### Windows
On Windows, scripts can be written to override some of the Rancher Desktop internals; for example, this can be used to provide certain command line parameters to k3s.  To do so, please do the following:
- Run Rancher Desktop at least once to let it create its configuration.
- Open the `%AppData%\rancher-desktop\provisioning` directory (e.g. `C:\Users\Joe\AppData\Roaming\rancher-desktop\provisioning`).
- Any files with a file extension of `.start` (e.g. `k3s-overrides.start`) will be executed when Rancher Desktop starts its Kubernetes backend; this runs within the Rancher Desktop WSL context.
- Any files with a file extension of `.stop` (e.g. `wipe-data.stop`) will be executed after Rancher Desktop shuts down its Kubernetes backend, running within the same Rancher Desktop WSL context.
- **Note**: Scripts will need to be saved with Unix line endings; line ending conversion is not done, and files with DOS line endings may produce unexpected effects.

Applicability: This only applies to Rancher Desktop on Windows, version 1.1.0 or later.

**Comment by byjrack** [comment]
Since being clued in yesterday things I have been trying to figure out as I went

- Windows editing best practices (which you tagged with the line endings note)
- What and where are the launches of each script recorded in logs for Troubleshooting
   - Best practices around using exits to help flag problem scripts
- Which shell to use based on WSL distribution roadmap
- Where it sits in the flow in the whole start and stop procedure
- Example use cases w scripts
   - Private DNS
   - Environment variables
      - Directly setting variables may not work because of script scope, but can it update files that feed features doing init after

**Comment by mook-as** [comment]
Fixed in https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/51.
