### ISSUE TITLE
It is possible to save images on an external driver (HDD/SSD)?

### ISSUE THREAD

**Issue by joaothallis** [rancher-sandbox/rancher-desktop#1828]

**Comment by jandubois** [comment]
I don't know what you are asking.

You can save images on any filesystem using `docker save`, but not sure if that is what you mean.

**Comment by joaothallis** [comment]
I want to store the images in an external hard drive because I do not have space in my principal ssd. With `docker save` it only saves a tar archive of the image, I can not use this as an image, right?

**Comment by adamkpickering** [comment]
@jandubois I think what they are asking is whether they can change the location that docker images are stored in. I believe that docker images are stored in the VM, and the data for the VM is stored in the data directory (`~/.loca/share/rancher-desktop/lima/0` on Linux, not sure what it is on other platforms). Please correct me if I'm wrong.

@joaothallis if that's what you're asking, that isn't configurable at the moment. If there is enough interest in making it configurable, I'm sure that's something we can take a look at.

**Comment by jandubois** [comment]
It depends on the platform. On macOS you can move the directory where the VM is store; see https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877 for an example.

I would think that this should work on Linux too.

I'm not sure if it is possible on Windows. I have never tried it there because we don't have the socket path length limitation on that platform.

**Comment by joaothallis** [comment]
I am using macOS and https://github.com/rancher-sandbox/rancher-desktop/issues/797#issuecomment-996510877 worked.  Thank you @jandubois and @adamkpickering! 

I tested moving to another folder like the comment because I'm currently without usb c external driver to test.
