### ISSUE TITLE
Don't update /etc/resolv.conf until init is running in the background

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1843]
On a slow machine it is possible that Windows will suspend the VM while RD still prepares all the data. If that happens, the IP address can change, and /etc/resolv.conf would no longer point to the VM itself, breaking the connection to dnsmasq.

**Comment by mook-as** [comment]
More details:
- Jan managed to see a Rancher Desktop run where `/etc/resolv.conf` pointed to an IP address that is _not_ the address of the VM (as seen entering the `rancher-desktop` WSL distribution after everything is up).
- Suspected problem:
  - We write the `resolv.conf` here: https://github.com/rancher-sandbox/rancher-desktop/blob/79e0c5379e116800e80ba56d9272f8dda2f00362/src/k8s-engine/wsl.ts#L1173-L1180
  - Which is actually executed here: https://github.com/rancher-sandbox/rancher-desktop/blob/79e0c5379e116800e80ba56d9272f8dda2f00362/src/k8s-engine/wsl.ts#L1191
  - Then we terminate the distribution, potentially shutting down the VM: https://github.com/rancher-sandbox/rancher-desktop/blob/79e0c5379e116800e80ba56d9272f8dda2f00362/src/k8s-engine/wsl.ts#L1202-L1205
  - We then run init: https://github.com/rancher-sandbox/rancher-desktop/blob/79e0c5379e116800e80ba56d9272f8dda2f00362/src/k8s-engine/wsl.ts#L1236
- This means that there's a chance that the IP address of the VM when we wrote `resolv.conf` is _different_ than the IP address of the VM when we run init.
- This is more likely on a slow system (since, AIUI, WSL will automatically shut down the VM if it's unused for some time).

In the associated PR, we move the `resolv.conf` writing into a service (run by the same init, but before `dnsmasq`), to ensure that matches.
