### ISSUE TITLE
Rancher Desktop - Silent installation in Windows

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1858]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/1857

<div type='discussions-op-text'>

<sup>Originally posted by **abcarcol** March 21, 2022</sup>
Dear developers,

Is it possible to install Rancher Desktop for Windows in "silent" mode? I tried the following without success:

.\Rancher.Desktop.Setup.1.1.1.exe /?
.\Rancher.Desktop.Setup.1.1.1.exe /s
.\Rancher.Desktop.Setup.1.1.1.exe /silent</div>

**Comment by wiruzman** [comment]
It works with capital s for silent parameter. Reference: https://nsis.sourceforge.io/Docs/Chapter4.html#silent
So `.\Rancher.Desktop.Setup.1.1.1.exe /S` works, but the output for different versions is different.

I prefer to use powershell to install and start Rancher Desktop due to wait option when installing, here are my steps:
`Start-Process -FilePath .\Rancher.Desktop.Setup.<version>.exe -ArgumentList /S -Wait`
`Start-Process -FilePath "C:\Users\<user name>\AppData\Local\Programs\Rancher Desktop\Rancher Desktop.exe"`

1.0.1
Installation works fine
Starting works fine

1.1.1
Installation works fine
Starting works fine

1.2.1
Installation works fine
Getting an error when starting
Error:
![image](https://user-images.githubusercontent.com/7511734/160090091-115c7f77-9f20-4670-8f18-065562f44a75.png)

**Comment by wiruzman** [comment]
My system is already wsl enabled and updated. It does not ask for reboot when I install it manually.

**Comment by vtmx** [comment]
I think Rancher use NSIS System:
https://silentinstallhq.com/nullsoft-scriptable-install-system-nsis-silent-install-how-to-guide

Examples:
```
setup.exe /S # silent
setup.exe /D="C:\Program Files\Rancher" # local of file
setup.exe /ALLUSERS=1 /S # all users
```

**Comment by mape2k** [comment]
Rancher Desktop MSI works perfectly for silent installation on Windows
