### ISSUE TITLE
Add `rdctl api` command

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#1903]
This command provides a convenient way to call an rd-engine API, like [gh api](https://cli.github.com/manual/gh_api) for the Github API.

For example `rdctl api list-settings` would perform the same function as:

```console
USER=$(jq -r .user ~/Library/Application\ Support/rancher-desktop/rd-engine.json)
PASS=$(jq -r .password ~/Library/Application\ Support/rancher-desktop/rd-engine.json)
PORT=$(jq -r .port ~/Library/Application\ Support/rancher-desktop/rd-engine.json)
curl -u $USER:$PASS localhost:$PORT/v0/list-settings
```

If the argument specifies an absolute path (like `/v0/list-settings`), then it will not be prefixed with the API version.

We should use the `-f/--raw-field` and `-F/--field` parameter semantics from `gh api` to switch to the `POST` method and add the fields to the request body.

We can add additional options later; just `-f` and `-F` should be enough for the initial version. Maybe support `--input` if time allows.

In a later version it would also take care of mTLS as well.

**Comment by ericpromislow** [comment]
I want to add `rdctl api /` and `rdctl api /vX` to list all the endpoints globally, and in the specified version respectively.

**Comment by ericpromislow** [comment]
Given that the PR for the finished work from the original story is over 300 lines, I'm going to move both items (`GET /` and output formats) to new issues.

**Comment by ericpromislow** [comment]
I'm going to put the fields (both raw and cooked) on hold, because looking at the `gh api` documentation, they're for named parameters, and we don't really have any of those yet. For now I'm going to assume that the `PUT /settings` endpoint will continue to take a JSON request body as its input, and will support that.

Later we can add these fields. Otherwise it's too loosely specified.
