### ISSUE TITLE
Image scan not showing any vulnerablities of application in UI

### ISSUE THREAD

**Issue by FrankAnk** [rancher-sandbox/rancher-desktop#2002]
### Actual Behavior

Scanning images from the RD UI seems not to show any vulnerabilties of the application parts in the image.
When i run the scan within WSL i do get a complete list of vulnerabilities.

### Steps to Reproduce

```
docker pull ituv0018/artikel
```

In Rancher-Desktop select Images and scan the pulled image.
Now compare the Results with 
```
wsl --distribution rancher-desktop trivy -q image ituv0018/artikel
```

### Result

![image](https://user-images.githubusercontent.com/51815224/162424086-e516e85f-3334-4c1f-9151-06749d6fcc0e.png)

### Expected Behavior

I would expect to have the same results.

### Rancher Desktop Version

1.2.1

### Rancher Desktop K8s Version

v1.20.15

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Pro Version 21H1

### What CPU architecture are you using?

x64

**Comment by rak-phillip** [comment]
Thanks for raising the issue and providing a clear example 😁 

I can clearly see what the issue is here; trivy json output returns a collection of different targets in the results, for this example:

* `ituv0018/artikel (alpine 3.15.0)`
* `Java`

It looks like we only consider the first.. it should be a simple fix to get all the results, but we might want to consider better grouping our results for any given target.
