### ISSUE TITLE
Add `rdctl shell` command

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#2063]
On Linux and macOS, running `rdctl shell` is the same as:
```
export LIMA_HOME=<path to lima dir, (currently) parent of 0 and _config>
export PATH=<path to resources/PLATFORM/lima/bin>
limactl shell 0
```

If args are passed to `rdctl shell`, they're passed on to `limactl shell 0`. If an arg `'abc def'` is quoted like here, the quotedness is passed on to `limactl`. Note that this might require a `--` after the `rdctl` flags to prevent `rdctl` from processing them.

On Windows, running `rdctl shell` is the same as running `wsl`, and until we find a reason to do otherwise,
it takes the same arguments as `wsl`. In effect, it's the opposite of an abbreviation alias of `wsl`. Same caveat that if the first wsl argument starts with a `-`, it will most likely need to be preceded by a `--` argument to avoid being processed by `rdctl`.

**Comment by jandubois** [comment]
> If an arg `'abc def'` is quoted like here, the quotedness is passed on to `limactl`.

It is not implemented yet, but we really want to use `limactl exec` instead of `limactl shell`, which will do shell expansion inside the VM again: https://github.com/lima-vm/lima/issues/251

For for now `limactl shell` is all we have, so that's what we are going to use...

> Note that this might require a `--` after the `rdctl` flags to prevent `rdctl` from processing them.

It is also possible to include `DisableFlagParsing: true` in the command definition, but that means `rdctl shell --help` is not going to work unless we implement it ourselves.

Not sure if this is worth it. Using `--` is a well established pattern, but needing to use it for all commands requiring options seems cumbersome.

Opinions?

**Comment by jandubois** [comment]
> On Windows, running `rdctl shell` is the same as running `wsl`

It should be the same as running `wsl -d rancher-desktop` instead.

**Comment by ericpromislow** [comment]
I added the `DisableFlagParsing: true` option for `rdctl shell`, along with bringing in the global server flags
only for those commands that need to hit the server.
