### ISSUE TITLE
Improve `rdctl shell` error message when the Rancher Desktop is not running

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2103]
Right now it produces a confusing error message, referencing `limactl` and the instance name `0`, which may be meaningless to the user:

```console
$ rdctl shell
FATA[0000] instance "0" is stopped, run `limactl start 0` to start the instance
Error: exit status 1
```

The command should run something like this:

```console
$ limactl ls 0 --json | jq -r .status
Stopped
```

and then suggest `rdctl start` instead when the status isn't "Running" (or the instance doesn't exist at all).

**Comment by ericpromislow** [comment]
I can detect the problem and give a friendlier message, but if I buffer the stderr output from `limactl` in order not to emit the default error message (which comes from `lima-vm/limactl`), we could end up buffering a very large amount of output. This also prevents interactive shells from working correctly, as users wouldn't see anything written to stderr in the shell, because the pipes are duped.

So my suggestion is to not do anything with the shell output, but recommend running `rdctl start` at the end of all the output if there was an error condition and the status isn't `Running`

**Comment by jandubois** [comment]
@ericpromislow You missed my point. You first call `limactl ls 0 --json` and check the `status` field. If it isn't running, you don't invoke `limactl shell` at all, but just display our own error message. There is no point in trying to create a shell when the instance is not running.

If the `status` is `Running` and you then call `limactl shell` then get an error from `limactl`, then you will just display it as before. There is no buffering of output involved at all, just a simple pre-condition check.
