### ISSUE TITLE
Change "restart" to "VM restart"

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2119]
```console
PS C:\Users\Jan\Downloads> rdctl start --container-engine containerd
Status: triggering a restart to apply changes.
```

"Restart" is alarming because it could mean a reboot of the host, but it really is just a reboot of the VM. The message should make that clear.

**Comment by mook-as** [comment]
But `VM` is an implementation detail (most users don't _need_ to be aware of it).

Bikeshedding: how about `Restarting Rancher Desktop to apply changes.`?

**Comment by ericpromislow** [comment]
But it doesn't restart the app, just one part of it. This is a more trivial change (hardly any change is totally trivial -- currently no test depends on this text, but there should be such a test), but I'll wait for the discussion to resolve.

Currently I don't like either of the proposals, and think we can stick with what we have because it's good enough at suggesting what's happening without being incorrect or overly specific, not revealing unnecessary details.

**Comment by jandubois** [comment]
I don't like keeping the unspecific "restart" here. I obviously care enough that I filed an issue for it. 😄 

I would be fine with "reconfiguring Rancher Desktop (this may take a while)", or anything else that cannot be misunderstood as rebooting the computer.

**Comment by ericpromislow** [comment]
+1 on "reconfiguring Rancher Desktop (this may take a while)"

**Comment by rak-phillip** [comment]
I'd like to update the messages used in the modal with whatever we land on for consistency. Another +1 for `reconfiguring Rancher Desktop (this may take a while)`.
