### ISSUE TITLE
Determine the future of cri-dockerd

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#2162]
We are uncertain about the future of cri-dockerd (see #2022); we need to determine how we need to proceed on ensuring that our features continue to function.

(This is more to ensure we have the conversation during the milestone; there will likely not be any pull requests directly associated here.)

**Comment by jandubois** [comment]
> we need to determine how we need to proceed

We do, but I don't think there is any urgency to making a decision yet.

We use `cri-dockerd` for all versions of `k3s`, including 1.24, and it seems to be working fine (after applying the fix for the metrics server performance). There should be no reason why it would suddenly stop working for those same older releases in the future.

So the one case to worry about is if `cri-dockerd` stops working for a future release, let's say 1.25.

We then have multiple options:

1. Don't support `k3s` 1.25+ on the `moby` runtime, but only on `containerd`. This is trivial to implement. Users who need the docker socket need to stay on `k3s` 1.24 or earlier.

2. Enable running **both** `containerd` and `moby` at the same time; allow `k3s` to connect to either (or just `containerd` when using 1.25+).

    This way a user can run `k3s` 1.25 on `containerd` and still have a `docker.sock` for applications that only work with the `moby` runtime. Of course this means that `docker build` artifacts are not automatically available to `k3s`; we will need to provide an internal registry (which may not be a bad idea anyways).

    This option provides the most flexibility, at additional complexity and development effort.

We can always implement (1) at first, and add (2) later, if necessary.

So I don't see any need to determine the path forward until cri-dockerd actually breaks. Or did I miss anything?

**Comment by jandubois** [comment]
I'm going to close this issue, as I don't think it is actionable right now. We can always re-open when it becomes necessary to do something.
