### ISSUE TITLE
List which legacy symlinks rancher was unable to remove

### ISSUE THREAD

**Issue by GSvensk** [rancher-sandbox/rancher-desktop#2192]
### Problem Description

I have gotten the permission denied popup implemented in https://github.com/rancher-sandbox/rancher-desktop/pull/2054 on my few latest start ups, each time I have taken a shot in the dark and removed another symlink from `/usr/local/bin`.

### Proposed Solution

It would be nice if the conflicting symlinks were listed or the complete list of legacy symlinks that a user is expected to remove.

My understanding is that this is the complete list.
https://github.com/rancher-sandbox/rancher-desktop/blob/c518d95708ca7d25be9e8cb710dd5daf26777aa9/src/integrations/legacy.ts#L35

### Preflight Checklist

- [X] I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.

**Comment by jandubois** [comment]
Looking at the code it looks like each permission error should be included in the error dialog. Are you saying that the error does not include the filename?

If you have a screenshot of the error, could you append it here?

Otherwise, @adamkpickering can you please take a look?

I assume you have fixed the problem for yourself already, but otherwise you should be able to get a full list with

```console
ls -l /usr/local/bin | grep /Applications/Rancher
```

Of course this is also a one-time thing, so improving the dialog will really only help users who skipped installed 1.3.0.

**Comment by GSvensk** [comment]
Thank you for the response!

Yes, no filename, only the hardcoded line here https://github.com/rancher-sandbox/rancher-desktop/pull/2054/files#diff-ad7fc00baacb79d536364ab2e99cf92b7549651af56deb676c8430a18d157d5aR288 . 

I don't have a screenshot unfortunately and I have resolved it now.

Alright, since it's only for this update and as mentioned here https://github.com/rancher-sandbox/rancher-desktop/pull/2054/files#r853517118 , this only happened because I'm not the owner of `usr/local/bin`, I'm happy if you decide to close this issue 😊

**Comment by jandubois** [comment]
> I'm happy if you decide to close this issue

Thanks! It feels like there is not a lot of utility in fixing it for 1.4.0; I think virtually nobody will run into it by then.
