### ISSUE TITLE
.local/share/rancher-desktop/lima/0/diffdisk file takes up 13.5GB

### ISSUE THREAD

**Issue by dodalovic** [rancher-sandbox/rancher-desktop#2285]
### Actual Behavior

@ `Linux PopOS!22.04`

### Steps to Reproduce

/

### Result

![image](https://user-images.githubusercontent.com/6358061/170693590-2d66488d-6e9e-4faa-b0c7-359947e954db.png)

### Expected Behavior

should be less than 13.5 GB

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Pop OS 22.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment]
This is the persistent disk of the VM; it is where e.g. all images are stored that are either built locally, or pulled from dockerhub or any other registry. It is also where any PVC are being stored, if you use kubernetes and create persistent volume claims.

13GB sounds like a reasonable size, and the file can actually grow up to a limit of 100GB as you fetch/build more images. You have to perform a Factory Reset to throw away all the data, but the volume will grow again as you use it.

**Comment by jandubois** [comment]
> Would it be possible to limit the size of the disk? For instance, 50 GB?

It is limited to 100GB by default. There is no way to change the default, but there is a workaround described in https://github.com/rancher-sandbox/rancher-desktop/issues/1521#issuecomment-1030886234

> Also, after deleting the images, shouldn't it get smaller? I did this test, and the volume didn't get reduced.

No, the file never gets smaller. The space that you freed up will be re-used, but there is no way to return unused space from inside the volume back to the host; you will have to delete and re-create it.

**Comment by jandubois** [comment]
The workaround is for macOS, but should work on Linux too (after adjusting the path to the lima directory accordingly), but won't work on Windows.

**Comment by bruno-lopes** [comment]
Very thanks @jandubois ! Quick and very useful response. I'll try the workaround.

**Comment by aminmkhan** [comment]
Yes, the `diffdisk` continues to grow, and the problem seems to be that pruning docker images and containers has no effect on compacting the `diffdisk` used by VM. 

There is a max size set by default of 100 GB, and only way right now to compact this VM is using _Factory Reset_ option which will delete the [Lima VM](https://github.com/lima-vm/lima) and re-create the disk.

The other option not available in UI is to override the default limit to less than 100 GB, as explained in https://github.com/rancher-sandbox/rancher-desktop/issues/1521#issuecomment-1030886234.

At creation time, the disk seems to be around ~250 MB, but will continue to grow with usage.

Proposed enhancements to UI can include:

- There could be an option in UI to just also remove all existing images and containers, without deleting Lima VM
- There could be an option in UI to configure disk size used by Lima VM
- There could be an option in UI to compact the disk used by Lima VM

 Relevant issues:  
 #1942  
 #1521  
 #171  
 #2398

**Comment by unknownzone96** [comment]
>
> I believe this is already possible using the "bulk delete" functionality in the "Images" tab. Click the checkbox on top to select all images, and then click the "Delete" button.
> 
Will this actually downsize the diffdisk? 

Also, you do not actually know of the problem unless you get to the 100GB limit. Then you are stuck in the state where image manager is not starting/ready, so you cannot use the delete functionality in Images tag.

**Comment by andriy-dmytruk** [comment]
My diffdisk file was actually 107Gb. The steps I took to actually reduce the size were:
* Start Rancher Desktop
* Cleanup unused images: https://stackoverflow.com/questions/45798076/how-to-clean-up-docker. 
   Depending on your case you can remove all images not associated with running or stopped containers with `docker image prune -a ` or `docker image rf` to particular images. `docker system prune -af --volumes` is even more aggressive cleaning.
* Quit Rancher Desktop
* Reduce the size of the diffdisk (https://github.com/lima-vm/lima/issues/356):
  ```
  qemu-img resize --shrink '~/Library/Application Support/rancher-desktop/lima0/diffdisk' 50G
  ```
