### ISSUE TITLE
Epic: Automatically manage external dependencies

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#2307]
We download and bundle a lot of additional tools from Github releases:

* alpine-lima, wsl-distro
* cri-dockerd
* docker-cli, docker-buildx, docker-compose
* helm
* kuberlr
* lima-and-qemu

Currently the locations and versions are hard-coded in the source code (some even in multiple locations), making it hard to check for updates, and to apply them.

Stories:

- [x] #2657
- [x] #1498
- [x] #2818
- [x] #2658

**Comment by mook-as** [comment]
Some notes (feel free to discard):
- We can run GitHub Actions on a schedule; perhaps we can use that for the bumping.
- For Docker CLI, for #2567 we'll have separate binaries for win32, linux, darwin, and wsl. For most of the tools though we'll use the Linux version for WSL.
- If possible, please do this in TypeScript (since we can now run TypeScript for the build scripts, whereas when we originally wrote things that wasn't a thing).

**Comment by adamkpickering** [comment]
Linking to #2710 in case we can do this as part of the dependency management improvements.
