### ISSUE TITLE
Expand E2E CI on Windows 11

### ISSUE THREAD

**Issue by prabalsharma** [rancher-sandbox/rancher-desktop#2367]
### Problem Description

Currently our E2E CI is running only on Linux. We need to expand it to run on Windows 11.

### Proposed Solution

Trigger: Nightly or manual
Job: same as Cirrus CI; e2e tests
Self-hosted GitHub runner: 1 provo Windows 10 runner

### Additional Information

This still might be an issue: https://github.com/rancher-sandbox/rancher-desktop/issues/942

**Comment by IsaSih** [comment]
## Timeline:

# Context:
Running the workflow on Windows self-hosted runner. Runner configured as a service.

1) Failed to execute the workflow jobs with powershell as `nt authority/network service`: `rancher-desktop` and `rancher-desktop-data distros` are not installed in WSL.
2) Uninstalled and Reinstalled WSL 2. Updated Kernel. Error continued.
3) Tried to run powershell logged as regular user `Chivo/chivo`. Powershell starts process with ID, then suddenly closes the new shell with generic error : "Process completed with exit code 1"
4) Tried to write the commands of each job in `powershell`scripts and then invoked PSExec to run the scripts, instead of the commands. Jobs pass, but are not actually executed.
5) Tried to execute the commands using bash, instead of `Powershell`. Bash exits with generic error: `exit code 1`
6) Tried to execute the commands using cmd, instead of `Powershell`. Bash exits with generic error: `exit code 1`
7) Figured out a way to change the service's logged account from `network service` to `chivo` in Services Settings. 
8) Tried to run `powershell` with the service logged as `chivo`. Got error `"Access is Denied"`
9) Tried to run `cmd` with the service logged as `chivo`. Got error `"Access is Denied"`
10) Tried to run `bash` with the service logged as `chivo`. Got error `"Access is Denied"`

**Comment by mook-as** [comment]
This is obsolete — we now have Windows E2E CI runs (using GitHub hosted runners).
https://github.com/rancher-sandbox/rancher-desktop/actions/workflows/windows-e2e.yaml
