### ISSUE TITLE
Test RD with Windows hibernation

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#241]
I have been unable to test native Windows hibernation via hypervisor; Windows 10 says that the firmware doesn't support it, and of course that is probably intentional because when the host goes into hibernation, the hypervisor should suspend the VM and not invoke the guest hibernation feature.

Anyways, looks like this needs to be tested on real hardware. Hibernation can be enabled (as admin) via

```
powercfg.exe /hibernate on
```

And hibernation can be triggered from the commandline via

```
shutdown /h
```

**Comment by mook-as** [comment]
This seems to work for me:
- Started RD (`npm run dev`, though since it's WSL either way it shouldn't matter)
- `shutdown /h`
- see that the power was off completely
- turned on the machine again
- See that `kubectl get pods --all-namespaces` shows results.

`main` at 4b993a398f05ec68777bf959579c74255619df5b
