### ISSUE TITLE
We are abusing the notification icon mechanism

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#243]
The [documentation](https://docs.microsoft.com/en-us/windows/win32/shell/notification-area) says:

>The notification area [...] is also not intended for quick program or command access. As of Windows 7, much of that functionality is best accomplished through an application's taskbar button.

I suspect we are just copying UX from Docker Desktop, but I will argue that their usage is both wrong and confusing.

There is no good reason to hide the taskbar button just because the application window is closed. The taskbar button should be the obvious choice to get the window back. It also provides an obvious visual indication that the application is still running.

The notification icon is created in the overflow area and will only be briefly visible while it changes state:

>Only the user can promote an icon from the overflow to the notification area, although in certain circumstances the system can temporarily promote an icon into the notification area as a short preview (under one minute).

The user can potentially decide to remove the notification icon completely, leaving them with no UI to connect to it at all. The concept of removing the taskbar button, but keeping the application running feels counter-intuitive.

So especially for new users it is confusing to find out (or not) that the application is still running, what the status is, and how to regain control over it.

Finally, the concept that the app is just a settings/preferences screen for a "system service" is wrong; it includes information about images (and containers, in the future), about port forwarding, and very likely even more functionality in the future.

If anything, we _could_ make the current behaviour a user-selectable option, if there is really demand for it, but it should not be the default.

**Comment by mook-as** [comment]
> There is no good reason to hide the taskbar button just because the application window is closed. The taskbar button should be the obvious choice to get the window back. It also provides an obvious visual indication that the application is still running.

That last part is… hard. The taskbar really doesn't want to show applications that are running but have no windows (unlike macOS, where running apps with no windows is a reasonable thing).  The closest we can do, I think, is to minimize the window when the user attempts to close it; that would leave the app running but not visible.  However, that has the downside that the window will appear in the alt-tab task switcher (and win+tab, etc.).  Fundamentally, the Windows taskbar model is different from the macOS dock, which lists all running applications, regardless of window state; this is also reflected in the difference in task switching (alt+tab vs ⌘+tab), where one shows windows and the other shows applications.

For better or worse, the convention on Windows, as far as I can tell, _is_ to stash things in the notification area ("system tray") when apps are running without windows.  This is true, for example, for Windows Defender and OneDrive.  I agree that this can lead to users missing that something is running; however, the system does not provide a better way to express this.

(If anything, I think this line of reasoning is convincing me that we should remove the icon on macOS instead; there, we would perhaps leave the app running with no windows, and set up menu entries when you right-click the icon in the dock instead.)

**Comment by jandubois** [comment]
> The closest we can do, I think, is to minimize the window when the user attempts to close it; that would leave the app running but not visible. However, that has the downside that the window will appear in the alt-tab task switcher

This actually sounds like the correct thing to do then. I'm not sure if including the window in the task-switcher is a downside; you are keeping the app running after all.

> I think this line of reasoning is convincing me that we should remove the icon on macOS instead; there, we would perhaps leave the app running with no windows, and set up menu entries when you right-click the icon in the dock instead

This I don't understand at all. You currently can't close the Rancher Desktop window on macOS without closing the application. There is no need to add extra menu entries on the dock icon; you can always task-switch to a running app, even when it has no windows; you still get the app menu bar. Look e.g. at `Preview.app` for an example of a window-less application.

**Comment by mook-as** [comment]
> > The closest we can do, I think, is to minimize the window when the user attempts to close it; that would leave the app running but not visible. However, that has the downside that the window will appear in the alt-tab task switcher
> 
> This actually sounds like the correct thing to do then. I'm not sure if including the window in the task-switcher is a downside; you are keeping the app running after all.

We're keeping the server active, but not actively managing the service; this is much like how we wouldn't keep the [firewall management UI](https://firewalld.org/documentation/utilities/firewall-config.html) open while we expect the [firewall daemon](https://firewalld.org/documentation/the-daemon-firewalld.html) to be active.

> > I think this line of reasoning is convincing me that we should remove the icon on macOS instead; there, we would perhaps leave the app running with no windows, and set up menu entries when you right-click the icon in the dock instead
> 
> This I don't understand at all. You currently can't close the Rancher Desktop window on macOS without closing the application. There is no need to add extra menu entries on the dock icon; you can always task-switch to a running app, even when it has no windows; you still get the app menu bar. Look e.g. at `Preview.app` for an example of a window-less application.

You can close the Rancher Desktop window by clicking on the red X in the stoplight (top left corner of the window), just like any other window.  (This was actually already discussed in Slack; we concluded that the current behaviour, including making the dock icon go away, is confusing, especially since starting Rancher Desktop again via spotlight doesn't open a new window and just leaves you with no windows and just the menu bar.)

**Comment by nicerloop** [comment]
Hi, just want to add some insight as a user Rancher Desktop to share how I would like the window/tray situation, as a user of both windows/macOS/linux systems:
- system tray / menubar items are used to have a visual presence for otherwise hidden services: network, anti-virus, Kubernetes
- taskbar / dock is for applications with actual windows as a user interface: code editor, browser, configuration screens

The usual interface between the user and rancher-desktop services is the command-line tools, so it does not need a permanent presence in the taskbar / dock, only when a window is open. On the other hand, the system tray icon / menubar item shows the current service status and offers quick access to those windows.

This is how I would envision the GUI of Rancher Desktop:
- have a system tray icon / menubar item to reflect the current Kubernetes service status, and offer quick access to the visual application
- have the visual application be opened on user call from the windows menu / search bar / spotlight
- have an option to only show the visual application on launch if the service is already running, to allow for a background start of the service on user login if desired

I currently have to close the Rancher Desktop window on login as it is set as a login item, but used mainly through non-visual (command line / docker API) interactions during my developer activities.

**Comment by nicerloop** [comment]
For reference, the macOS Menu Bar Extras Human Interface Guidelines:
https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/

**Comment by jsoref** [comment]
Technically Windows has headless applications. They're generally called **services**, and they're managed via the Service Manager (also visible via the Services tab of Task Manager).

`control programs` / `windows` for services are very much a thing, and closing them doesn't generally result in the underlying service quiting.

Windows 11 to my recollection doesn't put its Firewall into the system notification area.

Certainly WSL2 doesn't stick an icon into that area. Nor does Hyper-V.

**Comment by adamkpickering** [comment]
Closing this issue since we have more actionable issues that overlap with it. Please refer to #3144 for more info.
