### ISSUE TITLE
WSL docker: command not found

### ISSUE THREAD

**Issue by SoreGums** [rancher-sandbox/rancher-desktop#2432]
### Actual Behavior

```
> which docker
docker not found
```

installed rancher desktop a while ago 1.1 or something.
updated to 1.4.1 just now - took a bit, no errors all good.
been on kubernetes & containerd, nerdctl all good from wsl & host powershell
then turned off kubernetes and switched to dockerd (moby)

`docker` works on host from powershell, doesn't in wsl

created the link and all good now
```
> cd /usr/local/bin && sudo ln -s /mnt/c/Users/username/AppData/Local/Programs/Rancher\ Desktop/resources/resources/linux/bin/docker
> which docker
/usr/local/bin/docker
```

### Steps to Reproduce

in wsl (debian)
`> which docker`

### Result

`docker not found`

### Expected Behavior

location of `docker`

### Additional Information

also toggled WSL integration off then on, didn't create the symlink

once sorted out docker from WSL then VSCode WSL > Remote Container was much faster as expected cause files are all on WSL filesystem. VSCode Remote Container from windows host all just worked, was slow though... hence why i went looking for docker in WSL :)

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.23.6 (disabled)

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
Hi!

We just add the Linux binary to your Windows `PATH`, and typically the WSL distributions just pick it up from your Windows environment; if that is not working, the two most common issues are:
- You have a custom `~/.profile` / `~/.bashrc` etc. in your WSL distribution that clobbered your `PATH` environment variable
- You have configured WSL to [not append the Windows `PATH`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings)

If one of those two issues are the cause of it not working for you, there's not much we can do (other than maybe trying to force-mount our executable there, which seems like a bad idea as it would override any custom versions you may have).  If neither is applicable for your environment, we'd be interested in learning what the actual issue is.

Thanks!

**Comment by SoreGums** [comment]
ahh - that makes sense - something happened to this computer with the PATH and haven't figured it out.

good to close this then :)

**Comment by SoreGums** [comment]
looked more into it
> /mnt/c/Users/user1/AppData/Local/Programs/Rancher Desktop/resources/resources/win32/bin

is in the path
> which docker

command not found
however
> /mnt/c/Users/orrni66/AppData/Local/Programs/Rancher\ Desktop/resources/resources/win32/bin/docker.exe info

prints the expected info

and checking if the space in the path is an issue, doesn't seem to stop `code`
ahh this is it...
> which code
> /mnt/c/Users/user1/Documents/bin/Microsoft VS Code/bin/code

so 
>which docker.exe
> /mnt/c/Users/user1/AppData/Local/Programs/Rancher Desktop/resources/resources/win32/bin/docker.exe

if use `docker.exe` all good

**Comment by mook-as** [comment]
On WSL, `/mnt/c/Users/user1/AppData/Local/Programs/Rancher\ Desktop/resources/resources/linux/bin/docker` should be in the path (note `linux` instead of `win32`); that's the Linux executable that should be used instead.  It will talk to `/var/run/docker.sock` (as a Linux client) instead of talking via the Windows named pipe APIs, so it should be able to handle non-drvfs mounts better.

**Comment by SoreGums** [comment]
yeah - I've added to path now higher - all good.

I'm about to setup a new windows 11 machine - will test things there - might be a simple case of updating doesn't do everything 👍
