### ISSUE TITLE
Rancher Desktop shows fading radio buttons and checkboxes when navigating pages

### ISSUE THREAD

**Issue by huyz** [rancher-sandbox/rancher-desktop#2560]
### Actual Behavior

If you run Rancher Desktop, and you go back and forth between the Application Settings and Kubernetes Settings pages, you'll see that UI elements like radio boxes and checkboxes inexplicably show blue that fades out.
This is confusing and doesn't follow UI norms.
This leads me to doubt whether the radio boxes and checkboxes are set properly and somehow the app is struggling with knowing what the proper state should be: why would they even momentarily be selected?

### Steps to Reproduce

1. run Rancher Desktop UI
2. switch back and forth between the Application Settings and Kubernetes Settings pages
3. Notice that radio boxes and checkboxes that should always be white and unselected appear blue at first and then fade out.

### Result

Blue in radio boxes and checkboxes where there should never be

### Expected Behavior

The state of radio boxes and checkboxes should not change just because I'm changing between different pages in the UI

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

dunno

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS 12.4

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by rak-phillip** [comment]
@huyz thanks for raising this issue and helping to make Rancher Desktop better!

We've recognized that this is a problem and have worked to update the way that we manage state surrounding preferences as a part of a larger effort in #2373. I am going to close this issue because it will be resolved in an upcoming release. Please feel free to reopen if you feel this hasn't been properly resolved.

@jandubois
