### ISSUE TITLE
Kubernetes Config changed from yaml to json without indentation

### ISSUE THREAD

**Issue by jonstelly** [rancher-sandbox/rancher-desktop#275]
My Kubernetes Config file got changed from YAML to JSON format and worse still, it's unformated/indented JSON that looks like a big blob of text.  I'm only 90% sure it was RD that did this but if it was, please take more care when modifying this file, writing the entries is fine but changing it to a different format or removing indentation isn't acceptable.  I have no idea if all of my Kubernetes tools support JSON (maybe, but I haven't checked).

**Comment by mook-as** [comment]
First, I agree that's a problem (that is to say, I agree that we should be emitting YAML-looking YAML).

YAML's [specs](https://yaml.org/spec/1.2/spec.html#id2759572) claim to be a superset of JSON, so I believe all of your tooling should support it (it's just using odd flow styles for everything instead of block styles).

Emitting whitespace-preserving YAML (as in, maintains arbitrary whitespace such as new lines and custom indenting, not to mention comments) would be difficult though; I believe most tools will parse the config files completely and rewrite, as attempting to patch YAML is difficult due to how much leeway there is in the format.  Adding a comment and making silly whitespace changes in my kubeconfig before running `kubectl set-context` shows this (actually it didn't even preserve key ordering…)

In conclustion:
- I think we should fix this.
- The fix will _only_ be scoped to emitting text that uses block-formatted YAML; it will _not_ attempt to preserve non-semantic structure.
- We will probably not be able to preserve key ordering: the default format depends on the layout of structures in the golang code upstream.

**Comment by mook-as** [comment]
This should be both, as the [`k3sHelper`](https://github.com/rancher-sandbox/rd/blob/2e9b4fdd8a5456e2e7636e72d8c097752030bd79/src/k8s-engine/k3sHelper.ts#L500) calls [`exportConfig`](https://github.com/kubernetes-client/javascript/blob/e632ad82665b64426123c9cf260b050cafe5fd9d/src/config.ts#L355-L366).

**Comment by jandubois** [comment]
> This should be both

Yes, I got it mangled on the Mac too now once I "reset" the VM.

You get also restore it by running

 ```console
$ kubectl config view > ~/.kube/config.new
$ mv ~/.kube/config.new ~/.kube/config
```

Don't do it in one step, as the redirect will truncate the config file before `kubectl` gets a change to read it. Don't ask me how I know... 😄

**Comment by ericpromislow** [comment]
Fixed in https://github.com/rancher-sandbox/rancher-desktop/pull/322#event-4834434065
