### ISSUE TITLE
1.6.0 RC1-Tray menu not showing correct container runtime

### ISSUE THREAD

**Issue by prabalsharma** [rancher-sandbox/rancher-desktop#3039]
### Actual Behavior

After switching container engine from containerd to docker, the tray menu still shows containerd as container runtime.

### Steps to Reproduce

Test case 20

1. Start RD - select containerd runtime
2. Check Tray menu for container runtime: Containerd
3. Switch to Docker container runtime from preferences
4. Check Tray menu for container runtime

### Result

Tray menu shows containerd container runtime 

### Expected Behavior

Tray menu should update with change in container runtime

### Additional Information

<img width="800" alt="Screen Shot 2022-09-27 at 4 28 48 PM" src="https://user-images.githubusercontent.com/3749546/192655072-6852ba29-a4a3-4c87-aad1-283bc318734c.png">

### Rancher Desktop Version

1.5.0-701-g2d00a573

### Rancher Desktop K8s Version

1.18.20

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Catalina

### What CPU architecture are you using?

x64

**Comment by rak-phillip** [comment]
@torchiaf this looks like a regression introduced in 84ea3e2ac89c154bbb89e30a50009aa706b631a2 where the id for the tray menu item was changed to `container-runtime`. 

We should also update the label so that we are consistently referring to this as the "Container Engine" like we do elsewhere throughout Rancher Desktop
