### ISSUE TITLE
Hostresolver has a bug with truncating responses

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3072]
See https://github.com/lima-vm/lima/pull/1079

Need a decision if this must be fixed for "Next".

**Comment by Nino-K** [comment]
Not plumbing the truncate correctly in the upstream can impact us currently. When a DNS request is generated from a users application (e.g running a container within RD) the host-resovler’s built-in DNS never replies with truncate flag (TC flag) since it is not set. This can cause a loss of records due to the user never upgrading to TCP. When a client receives a reply with TC flag it will retry the query over the TCP.

**Comment by jandubois** [comment]
Fixed by #3081
