### ISSUE TITLE
Epic: Auto-start and backgrounding behaviour

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3144]
We want to make the following activities configurable:

- App starts automatically at login
- App starts in the background (no window)
- App terminates when the app window is closed
- Notification icon menu can be hidden

All 4 options are off by default, but can be enabled by the user via Preference settings.

The app window can be opened either via the tray icon, or by starting the app again, in which case it will just open a window for the already running instance.

# Stories

- [x] #3262
- [x] #3832 
- [x] #3722
- [x] #3769
- [x] #3771
- [x] #3772
- [x] #3773
- [x] #3261
- [ ] #3775
- [ ] #3776

# Related PRs

These can probably be closed once this epic is implemented:

- #243 (has a pretty extensive discussion already)
- #824
- #2129
- #3127
- #2437

**Comment by adamkpickering** [comment]
We had a meeting to clarify what we want for this. Here are the main conclusions:

- When the user closes the Rancher Desktop window, Rancher Desktop should continue running in the background by default, regardless of platform or package format.
- When the Rancher Desktop window is closed, but it is running in the background, there should be a Rancher Desktop icon in the tray/notification area that can be used to open the window, and is used to access other functionality. However, this may not be doable when running via AppImage on Linux.
- When the Rancher Desktop window is closed, but it is running in the background, there should **not** be a Rancher Desktop icon in the dock/task bar.

Note that Windows already works as described above. Other things we want:

- We want an option that, when checked, exits Rancher Desktop when the Rancher Desktop window is closed, rather than allowing it to continue running in the background.
- We want an option to run Rancher Desktop on startup inside the Rancher Desktop window.

Things to investigate:

- How do we implement this on macOS?
- How do we implement this on Linux?
- When running as AppImage on Linux, how easy is it for the user to exit Rancher Desktop when closing the window does not exit? Is there an obvious way to do this?

@jandubois @mook-as please let me know if I got anything wrong.

**Comment by aitorpazos** [comment]
As a user I like what I see here as it is aligned with my expectations as a Linux (non-Appimage) user. However, disappointed about it not being prioritized. It has been a big show stopper for me.

**Comment by jandubois** [comment]
> However, disappointed about it not being prioritized. It has been a big show stopper for me.

@aitorpazos Not sure what you mean by "not being prioritized". Things do take time, and we have a limited number of developers working on a vast number of issues.

This particular issue is under active development right now, e.g. #3260 is part of this epic, and PR #3517, which implements/fixes it, is already in the review stage.

So we will not be able to deliver this functionality in the next release, but it is not being ignored.

**Comment by aitorpazos** [comment]
I didn't want to sound harsh (sorry if it was), but each of us stakeholders need to apply some pressure in order to push for the things we care more 😀. This is the issue that is holding me back from using RD in a daily basis over anything else. It is so disturbing to have the window open while multitasking and also to easily accidentally close it when quickly switching apps. 
I am thrilled to see that it has been moved back to `Next`. Thanks!!!
![imagen](https://user-images.githubusercontent.com/2015196/206740802-37f0c075-1b7e-4b24-81ea-a7c5e7668e96.png)

**Comment by jandubois** [comment]
> each of us stakeholders need to apply some pressure in order to push for the things we care more

Absolutely, and one of the best ways to do this is to put a 👍 on an issue (directly, not on a comment in the thread below) because during planning, among other things, we look at the list of open issues sorted by the number of reactions on them. 😄 

I know that our use of the "Later" milestone has been confusing (and we are going to move away from it). It was supposed to be the milestone after "Next" but has become kind of a dumping-ground and has way more issues than could be scheduled in a following release. So renaming "Later" to "Next", creating a new "Later" and moving things around was creating a bit of a whiplash. We will probably turn it into a label, like "on-radar", but that alone will not solve the problem that too many things are being put into it.

> I am thrilled to see that it has been moved back to Next. 

Note that I just renamed the previous "Next" milestone to "1.7", so we'll work on this functionality for the following release (most likely 1.8, sometime in February, but no promises).

We just had a meeting 2 days ago about the UI, which will be tracked in https://github.com/rancher-sandbox/rancher-desktop/issues/3262 (still needs to be updated with meeting results).

**Comment by jsoref** [comment]
> When the user closes the Rancher Desktop window, Rancher Desktop should continue running in the background by default, regardless of platform or package format.

Classically, Windows programs would the first time you closed show a thing that either told you or let you change the behavior.

---

In general, Windows apps understand (since Microsoft has beat app devs up for abuse) that they shouldn't be in the system notification area if they aren't notifying the user.

For the use case Rancher Desktop has, a button to Start/Stop rancher from the settings app would be more appropriate. Such a thing would be very similar to how Windows Firewall/Windows Defender behave: the service runs hidden independently of a gui, and users can start/stop it from a program (or from the services manager).

---

macOS hasn't had a real reconning about abuse of the menubar in over a decade. (From memory, there was a campaign against abuses of [Faceless Background Applications](https://www.wikiwand.com/en/Extension_(Mac_OS)) a long time ago, but it was pre Mac OS X.)

Do note that Apple's own menu items can all be turned on/off which should definitely argue in favor of the same option for Rancher.

---

Linux can do whatever it likes, but I'd strongly advise following the Windows model:
* a button that can start/stop
* not requiring the app to be open

I have much less opinion about the rules for a notification area as I really don't use Linux  Desktop Environments and have no idea what their individual conventions are these days.

**Comment by aitorpazos** [comment]
@jandubois This is "just" a kind thanks comment, everyone likes getting validated :smile: . I am already on 1.8.1 and running Rancher Desktop on start as my default k8s/container local dev platform.
Very happy to see the team has done a great job delivering all options I can possibly need to manage Rancher Desktop in my laptop.
Some say these messages are just noise (sorry to those of that opinion), but I don't believe they are.
Thanks!

**Comment by jandubois** [comment]
@aitorpazos Thank you for your feedback! Hearing that the features we implement are helping our users is always appreciated!
