### ISSUE TITLE
Create rddepman PRs with a PAT that allows tests to run immediately

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#3151]
Right now the PRs don't run the "tests" action because the PR has not been submitted by a repo member. It requires a team member to manually close and re-open the PR to get the tests to start.

We want tests to run automatically as soon as the PR is created, so all we have to do is approve and merge the PR when all tests have passed.

**Comment by adamkpickering** [comment]
Created https://github.com/rancherlabs/eio/issues/1392 to create a PAT tied to Rancher Bot for use in this.

**Comment by adamkpickering** [comment]
This issue is also about modifying the ucmonitor.yaml and docker-cli-monitor.yaml workflows to use the PAT. This is because the issues they create cannot be automatically added to the Stripey project by the board-automation.yaml workflow unless these workflows are using a PAT, and not `GITHUB_TOKEN`.
