### ISSUE TITLE
KIM installed onto 3rd party WSL

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancher-desktop#325]
As an existing user of WSL, it would be nice if I could easily install KIM into my current WSL install. 

This likely shouldn't be done without user interaction since it changes the PATH. My suggestion would be a dropdown to select which WSL to install into.

**Comment by jandubois** [comment]
> As an existing user of WSL, it would be nice if I could easily install KIM into my current WSL install.

I used to think that interacting with the kube setup from within WSL distros would be out-of-scope for RD because it opens up too many configuration edge case, some of which we will invariably get wrong.

But I can see the benefit of working using a Unix shell instead of `cmd.exe` or Powershell.

My suggestion would be to bundle the Linux versions of helm/kubectl/kim with RD as well and offer to create symlinks to them into `/usr/local/bin` inside all of the installed distros that have a `/usr/local/bin` directory, but not a file installed yet.

Beyond that, I think any further support should be via documentation. Or maybe we just bundle the tools with RD and document how users can symlink/copy them wherever they want?

**Comment by mook-as** [comment]
We already add `…/resources/win32/bin` to the `PATH` in the Windows installer, right? I'd think running `kim` would already kind-of work, just kind of useless because it wouldn't be great at seeing Linux paths. We could just add a `linux_amd64` too, and add Linux binaries in there, ahead of the `win32` version, right? So on Linux, it would find the Linux binaries, and use that?

No messing about with the user environment needed, nor `/usr/local/bin`.

**Comment by mattfarina** [comment]
I think the "what" is that we want to be able to use `kim` from within other distros like openSUSE or Ubuntu. The how can be left up to us. Bundling the linux versions of those tools in the app and then linking them when someone requests it seems like an appropriate experience.

**Comment by agracey** [comment]
I don't know how much of an issue it is but I'd like to see this work with bash, fish, and zsh. I would imagine linking to a commonly used location in the path should take care of any specific shells.

**Comment by jandubois** [comment]
> I would imagine linking to a commonly used location in the path should take care of any specific shells.

I have verified that [Mark's suggestion above](https://github.com/rancher-sandbox/rancher-desktop/issues/325#issuecomment-854244533) works with bash/fish/zsh on openSUSE. We could even drop the Linux and the Windows binaries into the same directory, and it will still work because Windows shells will ignore the Linux binaries, and Linux shells will ignore the Windows binaries unless you explicitly include the `.exe` suffix in the command name.

So I think the only things to do are:

1. Decide if we want to have a single bin directory, or multiple ones. I prefer the single directory, as it is less code to set up, and keeps the `PATH` slightly shorter (but that is already a lost cause).
2. Add the additional binaries into the resources directory.
