### ISSUE TITLE
Kubeconfig merge in existing WSL ~/.kube/config

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancher-desktop#326]
Similar to #325, it would be nice to have an easy way to add rancher desktop as a new context in the default kubeconfig on my existing WSL.

**Comment by jandubois** [comment]
I think the right way to deal with this is either to have a symlink from inside the distro to the `.kube/config.yaml` on the Windows side, or to reference the Windows copy via the `KUBECONFIG` environment variable:

```console
$ KUBECONFIG=/mnt/c/Users/Jan/.kube/config.yaml kubectl get pods -A
```

Instead of using a symlink the user could also add the `KUBECONFIG` setting to their `.profile`. All of these options are easy to document, but hard to automate.

Updating multiple config files inside different distros however sounds like a documentation and support nightmare to me.

**Comment by agracey** [comment]
Do you happen to know if there are any device management issues with linking between file systems? 

It might be useful to have some documentation or a guided setup on the first run after install.

**Comment by jandubois** [comment]
> Do you happen to know if there are any device management issues with linking between file systems?

I don't know what you mean by "device management issues".

The mount location is potentially configurable, but otherwise I think all distros will mount the host filesystem by default as long as there is a `mount` command included in the distro.

Note that I'm explicitly talking about a symlink from the Linux side back to the Windows side. The symlink can always be created, even if there is a problem with the mount; it just becomes a "dangling" symlink.

We use the same symlinking technique to access the `k3s` binary and airgap image tarball from Linux even though they are stored in a cache on the host filesystem: https://github.com/jandubois/tinyk3s/blob/main/run-k3s#L31-L37

So if there are problems with the linking mechanism, then RD itself won't work either...

**Comment by mattfarina** [comment]
@jandubois I think the device management issues would be for cases where RD us under corp management on Windows. I think we would need to work with some enterprise users to work some of this out.

**Comment by mattfarina** [comment]
I think the ultimate goal of this issue is that tools like kubectl, kim, and helm just work under a linux distro because the configuration is available.

**Comment by jandubois** [comment]
> I think the ultimate goal of this issue is that tools like kubectl, kim, and helm just work under a linux distro because the configuration is available.

I agree; I'm just advocating for a single source of truth for the configuration instead of having multiple copies that can get out of sync (e.g. user makes manual edits).

I also think that right now the kubeconfig includes the WSL IP address, so if that changes, RD may have to update the config file. If this is still true, then again having just a single location to update will be much preferable.

**Comment by mook-as** [comment]
I'm not sure using a symlink (while conceptually cleaner) will work in practice: the file can contain paths to certs or helper executables (like the AWS or Azure stuff for auth), and the Linux-side kubectl (and other Kubernetes tooling) wouldn't be able to parse those paths.

**Comment by jandubois** [comment]
> I'm not sure using a symlink (while conceptually cleaner) will work in practice: the file can contain paths to certs or helper executables (like the AWS or Azure stuff for auth), and the Linux-side kubectl (and other Kubernetes tooling) wouldn't be able to parse those paths.

The `k3s.yaml` includes all certs, so this argument does not apply to it. For all other clusters configured, I think it is not our responsibility make them accessible from all distros. And how would you do it anyways, run `gcloud init` in each distro?

Not trying to defend the symlink solution; just pointing out that your argument is really solvable, so would affect all other solutions similarly.

**Comment by mook-as** [comment]
Yeah, I'm not sure there's anything we could do _better_ than just the symlinks.

And for doing symlinks, I'd want to have a static (Linux) binary mounted at `/mnt/wsl/rancher-desktop/…` (which is shared across all distros) and just run it once per distro, I think.  I don't really want to assume functioning `/bin/sh` / `ln`, I think…

**Comment by jandubois** [comment]
> I'd want to have a static (Linux) binary mounted at `/mnt/wsl/rancher-desktop/…`

Yes, that sounds like a prudent approach, assuming you can setup the mount from the Windows side (or from inside the rancher-desktop distro).

> I don't really want to assume functioning `/bin/sh` / `ln`, I think…

I think it is safe to assume `/bin/sh` exists, but maybe not `ln`.
