### ISSUE TITLE
Revoking administrative access does not reinstate previous state (e.g. remove sudoers)

### ISSUE THREAD

**Issue by udf2457** [rancher-sandbox/rancher-desktop#3342]
### Actual Behavior

This relates to MacOS.

If you initially grant administrative access, a dialogue box appears that tells you that Rancher will modify the following paths:
`/opt/rancher-desktop`
`/private/etc/sudoers.d/zzzzz-rancher-desktop-lima`

If you then at a later date return to the GUI and revoke such access by unticking the box, Rancher Desktop does not re-instate the previous state.

Particularly critical here is that Rancher Desktop does not remove the sudoers file, which therefore leaves now unwanted administrative access in place.

### Steps to Reproduce

See above

### Result

See above

### Expected Behavior

See Above

### Rancher Desktop Version

1.6.1

### Rancher Desktop K8s Version

?

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

Monterey 12.6.1

### What CPU architecture are you using?

x64

**Comment by jandubois** [comment]
This will eventually be addressed by the remaining items in #1224: Rancher Desktop will install a privileged helper process to handle all admin access required, so the sudoers file will go away.

Even though this issue is not strictly the same, I will still close it as a duplicate; we won't be adding code to remove the sudoers files (which would once again need the sudo password) until we implement the privileged helper.

The actual commands authorized by the sudoers file are very narrowly scoped and should not present any kind of vulnerability. They just allow you to start the daemons to allocate an additional network interface.
