### ISSUE TITLE
Images Allow List - Commit changes when losing focus

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3369]
We would like to improve the UX around committing changes to the list.

### Current behavior 

1. Enable Allowed Image Patters
2. Click plus
3. Type an image pattern
4. Click away from the image pattern
5. Click Apply

If I enter a value without pressing enter and then click Apply, the value that I entered is not applied. Perhaps this is expected, but I'm considering if it would make sense to "commit" the pattern when clicking or tabbing away.

### Expected behavior

Tabbing away or losing focus from the Images Allow List input should behave the same way as pressing enter so that changes can be applied if a user clicks away from the input.

_Originally posted by @rak-phillip in https://github.com/rancher-sandbox/rancher-desktop/pull/3357#pullrequestreview-1173013129_

**Comment by torchiaf** [comment]
Hi @rak-phillip @jandubois , I have a doubt. 
What should be the behavior in case of the input lost focus and the item is duplicate ?

**Comment by jandubois** [comment]
> What should be the behavior in case of the input lost focus and the item is duplicate ?

I guess this is another example of a validation error; what we just talked about this morning, like when the kube port has an invalid value.

For consistency with the port setting being invalid, this should display a red alert notification and disable the "Apply" button until the error is fixed.

**Comment by torchiaf** [comment]
Thanks @jandubois .
I agree with you about disable the `Apply` button until the error is fixed. The solution is to emit the error list outside the UI component (`StringList`).

We should also change the error handling inside list box. I would show the duplicate error message during the user types the item name and when Enter key is pressed (currently it is displayed only on Enter key).
Then, if the input lost the focus and there is a duplicate, the item is not saved and the input field is closed.

What do you think? IMO this is the simplest solution.

**Comment by jandubois** [comment]
> Then, if the input lost the focus and there is a duplicate, the item is not saved and the input field is closed.

This is intriguing, but we should discuss this in the group to see how this behaviour would transfer to other validation scenarios: E.g. what happens when the user selects an invalid port number, and then the field loses focus? Should the value be the default value? Or the value before the user started editing?

Do we need to alert the user because they may not have realized that their value was invalid and has now been changed behind their back (e.g. when focus is lost because the user switched to a different page or tab)?

So I think we need to think through this scenario for a bunch of different settings where the user could potentially give invalid input, and how those should handle loss of focus.

**Comment by jandubois** [comment]
Only somewhat related: I was wondering why the `+` button is disabled while the user edits the field. I expected to be able to click on `+` when I'm done with one entry, and it would just accept my edits, and create another one. Having to press Enter to re-enable the `+` button felt odd to me.
