### ISSUE TITLE
Missing SUSE publisher - Windows msi installer

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3499]
### Actual Behavior

Once Rancher Desktop Setup.msi is executed, SUSE is missing as a publisher in UAC when running the installer and installing Privileged Services.

### Steps to Reproduce

Once Rancher Desktop Setup.msi is executed, SUSE is missing as a publisher in UAC when running the installer and installing Privileged Services.

### Result

![WhatsApp Image 2022-11-30 at 10 56 50 AM (1)](https://user-images.githubusercontent.com/70187881/204884873-af9293d1-859a-4022-9c6f-34b8e3ce2469.jpeg)
![WhatsApp Image 2022-11-30 at 10 56 50 AM](https://user-images.githubusercontent.com/70187881/204884943-8ea9f5d4-897b-4b11-a5af-e963d7e38247.jpeg)

### Expected Behavior

Publisher in all UAC must be SUSE Software Solutions

### Rancher Desktop Version

 1.6.0-431-g070c8677

### Rancher Desktop K8s Version

n/a

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
Are you using a signed build? It's expected that CI builds are not signed by SUSE (because there's no way we trust CI in the cloud enough to give them keys. Also, our keys are in a physical fob anyway.)

As a workaround, you can attempt to [manually sign a build](https://github.com/rancher-sandbox/rancher-desktop/blob/main/docs/development/signing.md), and import the certificate into your Windows certificate store under _Trusted Root Certification Authorities_ before trying to run the installer.

(For taking screenshots of UAC dialogs, a VM is best; it's also possible to modify the _Windows User Account Control Settings_ to "do not dim my desktop", though that has security implications so it might not be good for a non-testing machine.)

**Comment by gaktive** [comment]
@gunamata to share with @IsaSih a signed build to see if this happens. Otherwise, this is expected until we do sign it.

**Comment by IsaSih** [comment]
So, re-tested it with a signed build. SUSE appears as the publisher.
