### ISSUE TITLE
Windows Installer not creating event log source for service

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#3506]
Is it expected behavior that once I install the msi version then I will not be able to install the exe version? even after I manually uninstalled the msi version and then tried installing the exe version?

The installation process aborts/hangs after some progress..

Steps:

- Install the MSI version. Close the session if it's open.
- Install the exe version. The installation process hangs.
- Uninstall the MSI version from the "Add/Remove Programs" 
- Try installing the exe version. The installation process hangs again.

![image](https://user-images.githubusercontent.com/59538726/204931301-95865fac-1fef-4f1b-bed1-16fd2cbd0737.png)

**Comment by mook-as** [comment]
This appears to have to do with not being able to run `privileged-service.exe install`, because the event log registry keys already exist.

Possible scenario:
- User installs via the MSI installer (service registered)
- User installs via the EXE installer (service skipped, event source registered)
- User uninstalls via the MSI installer. (service unregistered; event source untouched, still registered)

At that point, `privileged-service.exe install` will not work, because the event source exists.

**Comment by Sugatoshifumi** [comment]
@mook-as 
Below is who threw a similar event in the Q&A.
https://github.com/rancher-sandbox/rancher-desktop/discussions/3445

Sorry for throwing the question after it was closed, but I have one question.
Are you saying that I need to delete the event log registry keys in order to complete the setup successfully?

If the response policy is correct, I would like to investigate the event log registry keys and see if I can figure out how to remove them.

**Comment by mook-as** [comment]
@Sugatoshifumi This is in relation to the Windows installer work we're doing for Rancher Desktop 1.7.0; if you've just been downloading the release EXE installers, this would not be relevant for you.

I'll answer in the discussion for more debugging details.
