### ISSUE TITLE
a lot of unknown containers.

### ISSUE THREAD

**Issue by jack-liew** [rancher-sandbox/rancher-desktop#3536]
Hi:
When I failed to build an image use "docker build”, I get a lot of None images in RD's image list, and a lot of containers with sha256 headers that can't be started.These containers and images cannot be deleted from the RD, but can only be manually deleted from the CLI.

but, Since my build is wrong, it should not have an image, much less a container.

![屏幕截图_20221204_133019](https://user-images.githubusercontent.com/102201538/205484896-e1d667a6-ccd4-4576-a41a-1c9f9b69cc02.png)

![屏幕截图_20221204_161642](https://user-images.githubusercontent.com/102201538/205484902-be045744-a4ff-4e8f-9042-6d91f05a69d4.png)

### Rancher Desktop Version
1.62
### Rancher Desktop K8s Version
1.25.4
### Which container engine are you using?
moby (docker cli)
### Operating System / Build Version
windows 11
### What CPU architecture are you using?
x64

**Comment by ericpromislow** [comment]
@gunamata  This probably follows from #3532 -- feel free to re-assign this to me if it's a different problem.

**Comment by gunamata** [comment]
@jack-liew , The strange images you see in the images screen are the intermediate image layers that got pulled/built in the process of building your image. Since your build failed in between these intermediate layers did not get a chance to get cleaned up and show up on the images list. 

Also, the  containers you see are the ones that got fired during the image build process. Technically, every `RUN` command in your docker file fires up a container in the background to perform that step. Again, since your build process did not complete those containers would not have gotten a chance to gracefully stop.

And the reason Rancher Desktop doesn't allow you to delete those images is because those dangling images do not have repository name and it's not possible to delete an image explicitly with no repository name. However, you can use `docker image prune` to remove all the dangling images. 

I hope this helps. I am closing this as the reported issue is not a problem with Rancher Desktop.

**Comment by jack-liew** [comment]
> @jack-liew , The strange images you see in the images screen are the intermediate image layers that got pulled/built in the process of building your image. Since your build failed in between, these intermediate layers did not get a chance to get cleaned up and show up on the images list.
> 
> Also, the containers you see are the ones that got fired during the image build process. Technically, every `RUN` command in your docker file fires up a container in the background to perform that step. Again, since your build process did not complete, those containers would not have gotten a chance to gracefully stop.
> 
> And the reason Rancher Desktop doesn't allow you to delete those images is because those dangling images do not have repository name and it's not possible to delete an image explicitly with no repository name. However, you can use `docker image prune` to remove all the dangling images.
> 
> I hope this helps. I am closing this as the reported issue is not a problem with Rancher Desktop.

I see, Thank you !!!
