### ISSUE TITLE
virtualization.framework option on MacOS 

### ISSUE THREAD

**Issue by ramantseshau** [rancher-sandbox/rancher-desktop#3537]
### Problem Description

Apple added virtualization.framework feature on macOS Big Sur and macOS Monterey. 

> The Virtualization framework provides high-level APIs for creating and managing virtual machines (VM) on Apple silicon and Intel-based Mac computers. Use this framework to boot and run macOS or Linux-based operating systems in custom environments that you define. The framework supports the [Virtual I/O Device (VIRTIO)](https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html) specification, which defines standard interfaces for many device types, including network, socket, serial port, storage, entropy, and memory-balloon devices.

### Proposed Solution

Add virtualization.framework as option or as replacement of lima/QEMU

### Additional Information

https://developer.apple.com/documentation/virtualization

**Comment by jandubois** [comment]
> Add virtualization.framework as option or as replacement of lima/QEMU

Lima will support virtualization.framework as an alternative to QEMU soon, and then will be supported from Rancher Desktop as well.

See also #3107 

Note that support for Virualization.Framework (and for Rosetta 2) will be limited to macOS 13 (Ventura) and later.

**Comment by Sebor** [comment]
Hello @jandubois!
Any news about this feature in RD? As I can see the [PR](https://github.com/lima-vm/lima/pull/1147) has been merged already

**Comment by jandubois** [comment]
> Any news about this feature in RD? As I can see the [PR](https://github.com/lima-vm/lima/pull/1147) has been merged already

We still need a 2 settings, to switch the VM type between qemu and vz, and to enable Rosetta2 support to run amd64 images on arm64. I hope to do that this week.

Then we need to update Lima once more to get some recent bug fixes. Lima 0.15 release is waiting for nerdctl 1.2.1 release, which should come out soonish. If it doesn't, then I may just bump lima-and-qemu to the latest `master` of lima.

And we need a special release of lima-and-qemu with a qemu version that still supports Catalina.

I hope all the pieces fall into place by some time next week, and then we'll need another week or two for testing and bug fixes, so hopefully we'll have a release by the middle of March.

Otherwise you'll have to play with a CI build from the `main` branch, if you feel comfortable doing that (enable VZ manually, make sure you disable auto-update, etc).

**Comment by jandubois** [comment]
Not sure why this issue wasn't closed; Rancher Desktop 1.8 supports

```
rdctl set --experimental.virtual-machine.type=vz
```

The option will be exposed via the UI as well in 1.9. Support will remain experimental as long as it is considered experimental by the Lima project.
