### ISSUE TITLE
Allow users to configure an override to the use lima and qemu from a system path

### ISSUE THREAD

**Issue by shri314** [rancher-sandbox/rancher-desktop#3694]
### Discussed in https://github.com/rancher-sandbox/rancher-desktop/discussions/3693

<div type='discussions-op-text'>

<sup>Originally posted by **shri314** January  2, 2023</sup>
On mac, I see that rancher-desktop bundles its own lima and qemu binaries. This is good to make it work out of the box, however it is limiting as one can get the later versions of qemu and lima via something like `brew install qemu lima`. But, rancher desktop insists to using only its own bundled files. See https://github.com/rancher-sandbox/rancher-desktop/issues/3672 and https://github.com/rancher-sandbox/rancher-desktop/issues/3488.

Why not provide a way to override the configuration to allow use of some other qemu or lima? Like via environment: RD_LIMA_BIN, RD_QEMU_BIN?

This will allow advanced users to not wait a whole rancher desktop release cycle to get the benefits of new lima and qemu releases. </div>

**Comment by jandubois** [comment]
> Why not provide a way to override the configuration to allow use of some other qemu or lima? Like via environment: RD_LIMA_BIN, RD_QEMU_BIN?

Mostly because there are often some subtle interdependencies between the lima version, the alpine image, and the code in RD itself, including the code that handles updates from earlier versions. Running with random versions might not only not work, but also damage the persistent state in a way that only a factory reset can fix.

We simply have no bandwidth to deal with the additional bug reports this would cause; we already are struggling to keep up.

Using a newer version of qemu is less problematic; so this might be something that we can support. It is not clear though what benefit you would expect from that.

> This will allow advanced users to not wait a whole rancher desktop release cycle to get the benefits of new lima and qemu releases.

Advanced users should be able to build from source any version they want. Typically a release cycle is 8 weeks or less, so the bundled versions are always fairly recent.

What exactly do you expect to gain by running the latest lima and qemu version?

**Comment by ryancurrah** [comment]
@jandubois the latest lima support virtiofs on macOS and qemu has released some enhancements to the 9p mount driver.

**Comment by jandubois** [comment]
> latest lima support virtiofs on macOS

I'm aware (I'm a Lima maintainer), but those changes will require some support in RD to be usable. As I just mentioned in the other issue, there are still problems being discovered and addressed, on how to get good performance out of it. E.g. it looks like enabling Rosetta support is slowing down various workloads.

BTW, the reason the Lima version in 1.7.0 is at the specific commit it is, is because the commit adding VZ support broke the build on older macOS platforms. It has since been fixed.

> and qemu has released some enhancements to the 9p mount driver.

As far as I know the performance of 9p in qemu 7.2 is still pretty bad (on macOS).

**Comment by jandubois** [comment]
#3761 provides access to a newer version of `limactl` that supports the VZ framework, and this will soon be updated with the latest versions again.

As discussed above, we will not enable the user to configure Rancher Desktop with arbitrary versions of Lima and Qemu.
