### ISSUE TITLE
Add method for opening main window from tray menu [5d]

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#3722]
Rancher Desktop currently uses the `Preferences` menu item in the tray to both open the main window and the preferences window. The application is left without a clean way to simply open the main window from the tray.

> There's some history tied to this one.. All the preferences that we have today used to be in the main window, interspersed with application behavior. When we pulled all the preferences out into a separate window, we were left without a way to easily open the main window, so we opted to open both the main window along with the preferences window in as a short-term fix until we could come up with an appropriate pattern.

_Originally posted by @rak-phillip in https://github.com/rancher-sandbox/rancher-desktop/pull/3675#discussion_r1065148127_

# Acceptance criteria

### Test on all 3 platforms (Linux, macOS, Windows)

* "Show window" must be accessible via tray menu over Preferences
* Test that "Show window" restores the main window from various situations
  * Start Rancher Desktop
  * Verify that the tray menu contains a "Show window" menu entry
  * Minimize the main window
  * Verify that "Show window" restores the window
  * Hide the main window
  * Verify that "Show window" restores the window
  * Close the main window
  * Verify that "Show window" restores the window
  * Verify that PID number is the same comparing it before and after "Show window" is clicked

**Comment by jandubois** [comment]
> The application is left without a clean way to simply open the main window from the tray.

Yes, we should have a menu in the tray to open the app window again.

We also have the alternate mechanism of running the app again. If it finds it is already running in the background, it is supposed to open a window for it (even if the new preference says to start RD without an app window).

**Comment by rak-phillip** [comment]
I think we need to answer two questions:

1. What do we name the new entry in the tray menu
2. Does adding a new entry change the behavior of the existing Preferences entry?
  - Preferences continues to open both the main window and the preferences window
  - Preferences only opens the preferences window

**Comment by rak-phillip** [comment]
We will add the new entry for opening the main window above Preferences in the tray menu.

**Comment by jandubois** [comment]
> I think we need to answer two questions:
> 
> 1. What do we name the new entry in the tray menu

Yes, this is still outstanding. My suggestion: Either `Show window` or `Show Rancher Desktop`.

Since we already have `Quit Rancher Desktop` at the bottom, I find it repetitive, and would therefore prefer `Show window`.

As long as we have `Dashboard` as a separate window, we could use `Show main window` to be more specific, but once it is the only window, the "main" part becomes meaningless.

Here are current menu screenshots from macOS and Windows for reference:

<img width="212" alt="Screen Shot 2023-01-12 at 7 41 15 PM" src="https://user-images.githubusercontent.com/78947/212232588-abc32adc-b4be-44b3-93a0-7aca399184b5.png">

<img width="198" alt="Screen Shot 2023-01-12 at 7 41 38 PM" src="https://user-images.githubusercontent.com/78947/212232611-c9661346-0ef6-460e-9697-1ff5e4f2c1b7.png">


> 2. Does adding a new entry change the behavior of the existing Preferences entry?
> 
> * Preferences continues to open both the main window and the preferences window
> * Preferences only opens the preferences window

I think it should continue to also open the main window, as having Preferences without the main window looks a bit odd.

**Comment by adamkpickering** [comment]
Why not remove the Preferences entry completely? Ever since we introduced this behaviour it has felt weird to me that it opens the main window and the preferences window at the same time.

In its stead, we could have an entry to open the main window. From there people can get to preferences just fine.

I like this approach because it makes the tray menu feel more focused: it's for doing high-level things related to Rancher Desktop: opening the window, quitting it, seeing its status etc. If I want to get into details, I can open an interface that is better suited to that.

**Comment by jandubois** [comment]
> I think it should continue to also open the main window, as having Preferences without the main window looks a bit odd.

I have changed my mind on this, and if we have a separate menu entry to open the app window, then this entry should only open the Preference dialog (if this is easily possible). I assume the app will show in the dock / task list / task bar while the dialog is shown, but should be removed again as soon as the dialog is dismissed (applied or canceled).

**Comment by jandubois** [comment]
> In its stead, we could have an entry to open the main window. From there people can get to preferences just fine.

I think some people may view RD as a pure background service, whose sole UI is the menu bar icon. So selecting "Preferences" allows them to make config changes, and dismiss the dialog.

Why should they have to bring up the main window, in which they have no interest, just to launch the dialog. And once they are done with the dialog, they also have to manually close the main window again.

Example: user want to quickly change the Kubernetes version from 1.24 to 1.25. Why would they be interested in the main window?

**Comment by gunamata** [comment]
For opening, closing the application from the notification area/taskbar icon menu, one suggestion is to call the options `Open Rancher Desktop`, `Close`. This suggestion is based on the notification area icon menus of some of the standard Windows apps such as Teams, OneNote, Outlook etc.

**Comment by gaktive** [comment]
Some edits made above based on discussion.
