### ISSUE TITLE
Incorrect auto-generated options in MacOS

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#3806]
### Actual Behavior

By testing the auto-generated options for `rdctl set`, the following flags must not be available for rdctl set: `--kubernetes.host-resolver` as this option applies just for Windows and `--container-engine.image-allow-list.locked` as it cannot be changed via API.

### Steps to Reproduce

1.Run `rdctl set --kubernetes.host-resolver`
2. Check the output
3. Run `rdctl set --container-engine.image-allow-list.locked`
4. Check the output

### Result

```
Error: errors in attempt to update settings:
Changing field containerEngine.imageAllowList.locked via the API isn't supported
```

### Expected Behavior

the following flags must not be available for rdctl set: `--kubernetes.host-resolver` as this option applies just for Windows and `--container-engine.image-allow-list.locked` as it cannot be changed via API.

### Rancher Desktop Version

1.7.0-133-g25e1eabd

### Rancher Desktop K8s Version

1.17.17

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
We will eventually add support for `--kubernetes.host-resolver` on the other platforms too, but right now it is only available on Windows.

There are other platform-specific options, so I hope this can be configured via annotations in the schema.

E.g. `--wsl.integrations` only exists on Windows (but I guess we don't support it at all yet because it has a "map" datatype), and `kubernetes.experimental.socket-vmnet` only exists on macOS.
