### ISSUE TITLE
Permission denied error when creating symlinks

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#383]
From the Rancher User Slack:

```
app version: 0.3.0
Error creating symlink for /usr/local/bin/helm: EACCES: permission denied, symlink '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/helm' -> '/usr/local/bin/helm'
Error creating symlink for /usr/local/bin/kim: EACCES: permission denied, symlink '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kim' -> '/usr/local/bin/kim'
Error creating symlink for /usr/local/bin/kubectl: EEXIST: file already exists, symlink '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl' -> '/usr/local/bin/kubectl'
```

Maybe this is all expected, but I want to make sure the code deals with the `EACCES` error correctly.

**Comment by gaktive** [comment]
We need to explore the idea of a locked down user account since most of us have admin on our setups. LIMA may help.

**Comment by mook-as** [comment]
Currently (using code from #414 because that's what I hope to land), we do get a "proper" error surfaced to the UI:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/3977982/126197061-52bc9806-cb9f-4aba-9dec-d999dfefc0a5.png">

I'm not sure attempting to make a better error message is a good idea (mostly in the sense that it makes it harder for people who know what they're doing to diagnose the issue).

**Comment by mook-as** [comment]
Looking back at Slack, I believe this was just an informational message; the actual issue has to do with not having internet access on startup (due to proxies). #417 should help with that.
