### ISSUE TITLE
Move locked-field checking from issue 3756 to here

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3862]
### Problem Description

The v1 PR is already big enough

### Proposed Solution

Do the work in a separate branch

**Comment by jandubois** [comment]
If you split a story, please include the relevant description, and acceptance criteria in the new story as well, so the scope is clear!

**Comment by ericpromislow** [comment]
Locked objects cannot be changed via the API. In particular, if `containerEngine.imageAllowList.locked` is currently `true`, you can't modify other parts of the `imageAllowList` object (which currently is just `containerEngine.imageAllowList.enabled` and `containerEngine.imageAllowList.patterns`.

This includes trying to change a locked object via the following:

* rd set --container-engine.image-allow-list.enabled=`DIFFVALUE`
* rd api /v1/settings -X PUT --body '{"containerEngine": {"imageAllowList": { "patterns": ["pattern1", "pattern2", etc.] }}}'
* rd start --containerEngine.imageAllowList.enabled=`DIFFVALUE`
* start APP --containerEngine.imageAllowList.enabled=`DIFFVALUE`

where `DIFFVALUE` is the opposite of the current setting for `prefs.containerEngine.imageAllowList.enabled`.

Note that `rd api` is currently the only way to modify compound prefs, including `patterns` and `WSL.integrations`.

# Acceptance Criteria

It's not an error to specify the current value of a locked field. This is mainly to treat the following as a no-op:
```
rd api /v1/settings -X PUT --body "$(rd api /v1/settings)"
```

In particular, if `containerEngine.allowedImages.locked` is currently `true`, you can't modify other parts of the `allowedImages` object by starting the app with `rdctl start --container-engine.allowed-images.enabled=DIFFVALUE` or directly invoking the app via `... --containerEngine.allowedImages.enabled=DIFFVALUE` where `DIFFVALUE` is the opposite of the current pref.

If there is an attempt to change a locked field when the app is currently running, an error message should be returned and the action rejected.

If there is an attempt to change a locked field on the command-line when starting the app, the error message should appear in a dialog box (because output to the console might not be visible), and the app shuts down.

**Comment by mook-as** [comment]
The current design (adding a `.locked` setting) means that we can _only_ lock a whole subtree at once.  This works for image list settings, but doesn't work for locking single preferences; for example, and administrator might want to lock `kubernetes.port` (to avoid issues / work with some tooling) but not `kubernetes.version` (because changing the kubernetes version would still be useful).  Or even worse, trying to lock `hideNotificationIcon` (maybe they have a policy of never having apps with zero UI) means the whole set is locked.

Ultimately, I believe putting the locked state in-band with the settings that's being locked is a bad idea.

A potential solution is to divide the settings into layers, where the locked settings (which would be a subset of all settings, initially empty) goes on top of the settings that are normally loaded from disk / modified by the API / etc. So the user is free to make changes, but those changes would have no effect (because the locked settings are an override).

**Comment by ericpromislow** [comment]
Alternatively, there could be a separate settings-like object called `lockedSettings`, that contains a tree of all the locked objects.  Four sample trees:

1. 
`{ containerEngine: { imageAllowList : true }, kubernetes: { port: true } }`
- meaning: all `containerEngine.imageAllowList` fields are locked, and `kubernetes.port` is locked

2. `{ containerEngine: { imageAllowList : true }, kubernetes: true }`
- all all `containerEngine.imageAllowList` and `kubernetes` fields are locked

3. `{ containerEngine: { imageAllowList : true }, kubernetes: { port: true, version: true } }`
- meaning: all `containerEngine.imageAllowList` fields are locked, and `kubernetes.port` and `kubernetes.version` are the  only locked fields in the `kubernetes` subtree

4. `{}` or `undefinedish` -- there are no locked fields 

If a leaf is `false`, it's the same as if the path to that leaf doesn't exist.

It's an error for a leaf-value to be non-boolean.

**Comment by jandubois** [comment]
We have agreed on splitting deployment profiles into 2 settings structure: one for default values on first start, and one for locked settings.

The locked settings are currently limited to `containerEngine.imageAllowList.enabled` and `containerEngine.imageAllowList.patterns`. All other settings in the `locked` structure will be ignored (for now).

In the future we will need to differentiate between missing keys, and keys with the default value because the mere presence of the key indicates that the value cannot be changed.

**Comment by ericpromislow** [comment]
Here's the change I would make then:
```
diff --git a/pkg/rancher-desktop/config/settings.ts b/pkg/rancher-desktop/config/settings.ts
index aaf351da..6efd8a03 100644
--- a/pkg/rancher-desktop/config/settings.ts
+++ b/pkg/rancher-desktop/config/settings.ts
@@ -528,9 +528,13 @@ export function readDeploymentProfiles() {
     }
     break;
   }
-
+  if (!profiles.defaults && !profiles.locked) {
+    return undefined;
+  }
+  // When more fields are lockable, expand this object
+  const lockedDefaultSettings = { containerEngine: { imageAllowList: { enabled: true, patterns: [] }}};
   profiles.defaults = validateDeploymentProfile(profiles.defaults, defaultSettings) ?? {};
-  profiles.locked = validateDeploymentProfile(profiles.locked, defaultSettings) ?? {};
+  profiles.locked = validateDeploymentProfile(profiles.locked, lockedDefaultSettings) ?? {};

   return profiles;
 }

```
