### ISSUE TITLE
Include first run iso/images in RD

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#39]
On first run RD downloads elements from the Internet. This can be slow and the first startup time is slow. Can this be packaged into the download and copied to the right place (or linked) on first run to speed up the startup experience.

**Comment by jandubois** [comment]
All the cached files are stored under `$MINIKUBE_HOME/cache`, so the easiest way would be to run RD once locally and package that directory. Just make sure that you start with a fresh directory, otherwise you might include older cached files.

This would also be the most robust approach, as the list of downloaded/cached files could change over time, and this way they won't have to be hard-coded in RD itself.

**Comment by jandubois** [comment]
Bundling of the Linux distro (`boot2tcl.iso` on macOS and `distro.tar` on Windows) is covered by #224.

@mattfarina  The only other files downloaded should be k3s and it's images, and I don't think we want to bundle a specific k3s version with the app itself, so I think this issue can be closed.

**Comment by gaktive** [comment]
Closing based on age (and we moved away from Minikube so this ticket's relevance has faded).
