### ISSUE TITLE
Is it "imageAllowList" or "allowedImages"

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#3919]
### Problem Description

Most of the v5 settings code is still using `containerEngine.imageAllowList` but there are a few instances of `containerEngine.allowedImages`. 

One of these needs to be changed to the other.

### Proposed Solution

Just use one name.

**Comment by jandubois** [comment]
I thought that was covered by #3740, but it doesn't mention it.

Anyways, the idea is that the field names should be close to the names in the GUI so that the `rdctl set` options look familiar.

So since the UI calls it "Allowed Images" the setting should be `allowedImages.enabled` etc. so that we have `rdctl set --container-engine.allowed-images.enabled=true`
