### ISSUE TITLE
Kubernetes Starting Error on MacOS

### ISSUE THREAD

**Issue by kasunsjc** [rancher-sandbox/rancher-desktop#400]
Hi Getting the following error when starting Rancher Desktop

![image](https://user-images.githubusercontent.com/16514562/124322578-4f32a680-db9d-11eb-8572-f3107bd8cbce.png)

OS - macOS Big Sur
MacBook Pro Intel

**Comment by jandubois** [comment]
When you start Rancher Desktop the first time on macOS, it asks for permission to change the file ownership (and setuid bit) of the hyperkit driver. The error message sounds like you didn't grant that permission. Rancher Desktop cannot work without this.

**Comment by kasunsjc** [comment]
I didn't get any popup window to grant permissions. Let me know how can I give permission

**Comment by jandubois** [comment]
Please delete Rancher Desktop from your `/Applications` folder and install it again. The first time you run it, you should get a dialog like this:

<img width="555" alt="Screen Shot 2021-07-05 at 10 28 47 AM" src="https://user-images.githubusercontent.com/78947/124504219-df2e4700-dd7b-11eb-8283-275d73f713f6.png">

Do you not get that?

**Comment by kasunsjc** [comment]
Nope, I tried now. after I dragged the app to the application folder then run the app. Prompt the error starting Kubernetes permission error as above. 

Didn't get the popup window to enter password.

**Comment by jandubois** [comment]
@kasunsjc Are you running device management software or something similar that might prevent you from elevating privileges to administrator?

I've tested on Catalina and Big Sur, and created both Standard and Admin users, and I *always* get the prompt. When I cancel the prompt, I get the same error dialog, but that is expected, and exactly what the error says: "User did not grant permission".

@mook-as Any ideas under which conditions the dialog might not be displayed (or auto-cancelled)?

**Comment by mook-as** [comment]
Hmm, we're doing a very boring [invocation](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.3.0/src/k8s-engine/hyperkit.ts#L238) of [sudo-prompt](https://www.npmjs.com/package/sudo-prompt); it's possible that it's seeing some _other_ error and thinking it's because the user didn't grant permission instead…

**Comment by jandubois** [comment]
> it's possible that it's seeing some _other_ error and thinking it's because the user didn't grant permission instead…

I don't see how that would happen; shouldn't that still display the dialog?

@kasunsjc Normally I would suggest to add additional logging around this call to investigate what is going wrong. But the whole dialog will disappear in the next release because we will no longer need to change ownership/permissions, so digging much deeper is of limited use: there will be no way to ship any fix we might come up with.

So if this is fine with you, I would like to suggest to simply wait for the next release, which doesn't have a firm timeline, but hopefully should be out by the end of the month.

**Comment by kasunsjc** [comment]
No rush. will wait till next release :)

**Comment by jandubois** [comment]
@rkazak Thank you for confirming!

You should not have gotten an error on the first install, but since you have done a successful install afterwards, there will be no logs around to investigate what happened, so nothing to investigate. I assume this issue then can be closed now.
