### ISSUE TITLE
The initialization cannot be completed in the Linux environment without GUI

### ISSUE THREAD

**Issue by Aurelius-Huang** [rancher-sandbox/rancher-desktop#4025]
### Problem Description

After newly installing rancher desktop, the initialization cannot be completed in the Linux environment without GUI, and an exception will be thrown when entering the rancher-desktop command for the first time:

[4077:0223/065944.303314:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[4077:0223/065944.303416:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
Segmentation fault

### Proposed Solution

After the installation is complete, you can complete the initialization directly through the command line.

**Comment by mook-as** [comment]
Hi! I don't believe we have supporting non-GUI environments on our plans at the moment. If you're comfortable using non-GUI environments, installing docker/nerdctl/k3s/etc. manually from your package manager (or getting them manually) is probably a better route for you.

If your plan is instead to set up the environment for your users (in an administrative installation sort of way), we _do_ have plans to better support that scenario that would involve dropping files in predetermined places, without actually starting Rancher Desktop (interactively or otherwise).  Please watch for the next release or two for details.

If you're looking for something else, please describe your use case in more detail, thanks!
