### ISSUE TITLE
The ~/.rd/bin directory has not been added to the PATH, so command-line utilities are not configured in your bash shell.

### ISSUE THREAD

**Issue by Noksa** [rancher-sandbox/rancher-desktop#4163]
### Actual Behavior

Rancher Desktop thinks that I use bash shell

### Steps to Reproduce

* Install Rancher Desktop on macos with zsh default shell
* Select manual configure PATH
* Add `~/.rd/bin` to PATH in `.zshrc`

### Result

<img width="928" alt="image" src="https://user-images.githubusercontent.com/36312857/224642060-a0a4f29e-6638-4aca-9f4a-760e389d9d3c.png">

### Expected Behavior

I would say it shouldn't show information about `bash`, because I added required settings in `.zshrc` file for `zsh` shell.
```
❯ ~ dscl . -read /Users/$(whoami) UserShell
UserShell: /bin/zsh
```

Rancher should be aware of user's shell.

### Rancher Desktop Version

1.7.0

### Rancher Desktop K8s Version

Doesn't matter

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Venture 13.2.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by adamkpickering** [comment]
Many of Rancher Desktop's users are relative novices with regard to Unix system administration. These users are the intended audience for these messages. I realize the messages might be annoying, especially if they are for a shell you don't use, but this was a design decision the dev team consciously made. Luckily, it is possible to mute diagnostic messages (see the toggle on the right) - that's what I recommend you do.

Hopefully that addresses your concerns! I'm going to close this issue for now. We can reopen it if you have further concerns.

**Comment by tethich** [comment]
The reporting is delivered in form of issue/error, saying that there is 1 failure. This implies something went wrong and Rancher might not work properly. No matter the audience, Unix novices or not, the tool should be more explicit. Is not about annoyingness. Is about proper, clear and easy to understand messaging. 

Also just muting it does not imply it will go away and that Rancher will use z shell instead of bash.

1. Please reopen the issue and improve tool to server better diagnostics
2. Is there a way to know for sure which shell is Rancher using ? I expect to be the active one the OS has. But still ...

**Comment by adamkpickering** [comment]
I no longer work on Rancher Desktop - @jandubois any chance you want to comment on this?
