### ISSUE TITLE
`rdctl factory-reset` does not delete `~Library/Application\ Support/Rancher\ Desktop`

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4175]
It is also weird that we have **both** `rancher-desktop` **and** `Rancher Desktop` directories there. The former contains our own data; the latter contains stuff managed by Electron. Not sure if we should maybe combine things.

I'm not 100% sure if a factory reset **must** delete the Electron directory, but since we don't have a separate `uninstall` mechanism, it is probably a good idea.

Also not sure if we have the same issue on other platforms.

**Comment by adamkpickering** [comment]
I ran into this a while ago, while working on the single instance stuff. I tried hard to combine these two directories (or whatever their equivalents are on Linux), and came to the conclusion that Electron makes it prohibitively difficult. See https://github.com/electron/electron/issues/35680#issuecomment-1340203727 for more information.

As far as *deleting* the electron `Rancher Desktop` directory on factory reset, I think that is more feasible. Especially since that would be done from `rdctl`, which is external to the main electron program. Though I am concerned that as long as the electron app is running, it may be trying to use this directory. This needs more investigation.
