### ISSUE TITLE
Not able to launch the 1.8 RC build on my Windows 10

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4191]
I seem to have broken something with my local Rancher Desktop setup as part of [1.8 RC](https://github.com/rancher-sandbox/rancher-desktop/actions/runs/4390255742) testing. At this state, none of `Factory Reset`, `wsl --shutdown`, `Machine restart`, `uninstall & re-install` seem to help! Unfortunately, I don't know what got me into this state. 😞

Here's the error screenshot. From the log messages, it looks like something to do with the `rancher-desktop-guestagent` but I am not sure.

![image](https://user-images.githubusercontent.com/59538726/225157847-d6e34830-f561-452c-a1ed-13f56a4de819.png)

```
2023-03-14T22:26:16.294Z: Registered distributions: Ubuntu
2023-03-14T22:26:16.580Z: Registered distributions: Ubuntu
2023-03-14T22:26:18.346Z: Registered distributions: rancher-desktop,Ubuntu
2023-03-14T22:26:18.483Z: Registered distributions: rancher-desktop,Ubuntu
2023-03-14T22:26:18.484Z: Creating initial data distribution...
2023-03-14T22:26:21.212Z: Did not find a valid mount, mounting /mnt/wsl/rancher-desktop/run/data
2023-03-14T22:26:24.158Z: Installing C:\Users\GunasekharMatamalam\AppData\Local\Programs\Rancher Desktop\resources\resources\linux\internal\trivy as /mnt/c/Users/GunasekharMatamalam/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/internal/trivy into /usr/local/bin/trivy ...
2023-03-14T22:26:24.403Z: Installing C:\Users\GunasekharMatamalam\AppData\Local\Programs\Rancher Desktop\resources\resources\linux\internal\rancher-desktop-guestagent as /mnt/c/Users/GunasekharMatamalam/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/internal/rancher-desktop-guestagent into /usr/local/bin//rancher-desktop-guestagent ...
2023-03-14T22:26:27.280Z: WSL: executing: cat /root/.docker/config.json: Error: wsl.exe exited with code 1
```

Logs:

[logs-20230314.zip](https://github.com/rancher-sandbox/rancher-desktop/files/10974472/logs-20230314.zip)

**Comment by gunamata** [comment]
@IsaSih and I investigated a bit and could figure out the repro steps. This happens while executing the [Testcase#88](https://trello.com/c/fnqszz2Z/364-test-case-88-private-registry-pull-behind-the-corporate-vpn-experimental-rd-networking)

Here are the repro steps:

- Connect to Cisco AnyConnect VPN
- Enable experimental network tunnel `rdctl set --experimental.virtual-machine.networking-tunnel=true`
- At this state, pulling a image from private registry did not work. 
`docker pull registry.suse.de/suse/containers/caps/2/containers/registry/harbor-nginx:2.0.2`
- Disable experimental network tunnel `rdctl set --experimental.virtual-machine.networking-tunnel=false`
- At this state, the status bar in the GUI keep running and if left like that runs into the error shown in the issue description
- If Cisco AnyConnect is disconnected then the GUI status bar progress completes and the app seems to get to a working condition. However, the RD icon in the system tray still shows red!

**Comment by Nino-K** [comment]
So I went ahead and tried this out, it is a known [issue](https://github.com/rancher-sandbox/rancher-desktop/issues/3091) that also occurs on 1.7. The issue is related to the routing on the host network while VPN is enabled. When the rancher desktop makes a [request](https://github.com/rancher-sandbox/rancher-desktop/blob/b9ab5d36b67af5c480a910c9ea73d5390d931c25/pkg/rancher-desktop/backend/kube/wsl.ts#L215) to the kubeAPI on `WSL_IP:6443` the request is being mishandled due to the higher route priority on the VPN interface and it never gets routed to the WSL VM. I have documented a workaround for our users [here](https://github.com/rancher-sandbox/rancher-desktop/issues/3091#issuecomment-1268931636).

However, as for the [test case #88](https://trello.com/c/fnqszz2Z/364-test-case-88-private-registry-pull-behind-the-corporate-vpn-experimental-rd-networking) you would need to make you one of the following occurs:

1) run `rdctl set --experimental.virtual-machine.networking-tunnel=true` during the startup even when rancher desktop UI is stuck at the "starting k8s" stage.
2) Or, start the RD first and run the `rdctl set --experimental.virtual-machine.networking-tunnel=true` and then start your cisco annyconnect
3) Or, run the [workaround](https://github.com/rancher-sandbox/rancher-desktop/issues/3091#issuecomment-1268931636) and then enable the  `rdctl set --experimental.virtual-machine.networking-tunnel=true`.

Please note that this will not be an issue once the new network is a default network. This only occurs during this transition.

**Comment by gunamata** [comment]
I could sort this out with @Nino-K 's help. First, I could switch between enabling and disabling the experimental tunnel without connected to VPN while launching RD. Second, there were DNS issues on my machine due to multiple VPN clients running at the same time, which was causing problem resolving the DNS for the private registry. Closing the issue.
