### ISSUE TITLE
Windows Deployment profile registry key types get auto corrected  

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#4218]
The deployment profile keys get auto corrected which is not correct. For example, the code at present seems to be okay if REG_SZ is used instead of REG_MULTI_SZ etc.

**Comment by ericpromislow** [comment]
I don't understand where the auto-correcting is taking place. It looks like there's a missing attachment in this report.

**Comment by jandubois** [comment]
I think Guna means that incorrect types don't throw an exception.

E.g. using REG_SZ instead of REG_MULTI_SZ will be auto-converted into an array with a single entry instead of throwing a type-mismatch error.

But also a REG_DWORD would be accepted as a string, but I think it will just take the DWORD value as the codepoint for a single character instead of converting the DWORD to a string representation of the number.

Instead of hoping that these auto-conversions yield the expected result, we should treat all of them as errors.

**Comment by ericpromislow** [comment]
I started a branch to work on this on Friday -- I'll see how it's working now

**Comment by ericpromislow** [comment]
Once PR #4251 gets merged I'll convert type mismatches from a log statement to a fatal exception that appears in a dialog box. That PR is large enough.
