### ISSUE TITLE
rdctl toggle flags

### ISSUE THREAD

**Issue by foolioo** [rancher-sandbox/rancher-desktop#4225]
`rdctl` is great, unless i missed something, it does not support toggling some flags.
for instance, there is a support for enabling telemetry by using `--application.telemetry.enabled` flag, yet there is no corresponding support for disabling the telemetry (e.g. `--application.telemetry.disabled`.

maybe instead of having a specific flags toggling (disabling\enabling), the flag can accept and argument in the same spirit of `--application.path-management-strategy string`, e.g.

```
--application.telemetry     allow collection of anonymous statistics (Allowed values: [enable, disable])
```

**Comment by jandubois** [comment]
All boolean options can take a `true` or `false` argument, so the way to turn the option off is to write e.g. `--application.telemetry=false`. If you don't specify a value, the implied default is `true`.

Note that due to the way parsing of boolean command-line options works in Go, you **must** use an `=` sign to specify the value, you cannot write `--application.telemetry false` (see https://pkg.go.dev/flag#hdr-Command_line_flag_syntax for more details).

Side note: telemetry isn't currently implemented, so this particular option has no effect.
