### ISSUE TITLE
Installing an extension without a tag should install newest version

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4362]
Right now it installs the image with the `latest` tag. Some extensions don't have a `latest` tag, and sometimes `latest` is no longer being updated.

---
The target algorithm is:
- If the user specifies a tag, that tag will be used. (If that doesn't exist, it fails.)
- Otherwise, iterate through the tags and select the highest semver tag
- Otherwise, use the tag `latest`
- Otherwise, fail.

#### Acceptance Criteria

Try to install an extension ID with no tag specified. RDX must install the highest semantic version from the registry. Only if there's no semantic version available, then it should install the latest tag.

**Comment by mook-as** [comment]
How would you define _newest version_? Say, for example, when you install `ghcr.io/epinio/extension-docker-desktop`…

Do we need to enumerate the registry and hope they have a useful last-modified date? Note that the API for [getting tags](https://docs.docker.com/registry/spec/api/#get-tags) only returns a raw string, and there doesn't seem to be a good way to get dates other than parsing the manifests.

**Comment by jandubois** [comment]
> How would you define _newest version_?

I would enumerate all tags, drop any that are not a plain semver, and then do a semver sort.

If there are no semver release, try `latest`. If that also doesn't exist, throw an error that an explicit tag is required.

**Comment by mook-as** [comment]
@jandubois I propose editing the list slightly:

- If the user specifies a tag, that tag will be used. (If that doesn't exist, it fails.)
- **New** Otherwise, if the extension is already installed, use the installed version.
- Otherwise, iterate through the tags and select the highest semver tag
- Otherwise, use the tag latest
- Otherwise, fail.

That is, if you say `rdctl extension install foo`, and `foo:1.0.0` is already installed, we use `1.0.0` even if `1.2.0` is available.  This would make parts of the internal workings easier (that is, so we can default to fetching the installed version for places that just need _a_ version).

**Comment by jandubois** [comment]
I'm not sure I understand why/how this would be easier.

The advantage of always installing the highest semver is that `rdctl extension install foo` would guarantee to update to the highest version. Otherwise you have to uninstall and reinstall to upgrade (or add an `update` command).

Why would a user ask to install an extension that is already installed, and then expect this to be a no-op?

And if the install request is generated internally, why would we not include the tag in the request? Can you describe the scenario where this becomes a problem?

**Comment by mook-as** [comment]
Hmm, right, for the CLI, ignoring the installed version makes more sense. For internally getting the extension, the currently installed version makes more sense (but that just means we need to always pass in the version… or a flag.)
