### ISSUE TITLE
Troubleshooting tab is not adjusted to the main Window dimensions

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4467]
### Actual Behavior

Content of Troubleshooting tab is not aligned with the main Window.

### Steps to Reproduce

1. Launch Rancher Desktop
2. From the main window, go to Troubleshooting
3. Check the tab's layout

### Result

<img width="1279" alt="Screen Shot 2023-04-14 at 5 06 21 PM" src="https://user-images.githubusercontent.com/70187881/232181155-c96d6b65-9cde-4999-9751-12bdd9666100.png">

### Expected Behavior

Layout of Troubleshooting tab must be responsive to the main window dimensions.

### Rancher Desktop Version

1.7.0-1041-g54242d2c

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> Layout of Troubleshooting tab must be responsive to the main window dimensions.

It is actually responsive, it just has a maximum width. This is not a regression, but we didn't notice because the default window size used to be smaller than the max.

I'm not convinced that stretching the page to the full monitor width (if the window is maximized) is desirable. @manuelecarlini can you have a look at what other options we might have?

**Comment by jandubois** [comment]
> @jandubois this is how I would organize the layout

Thanks, looks good to me, and should work nicely even when the window is stretched rather wide.

**Comment by manuelecarlini** [comment]
@rak-phillip I like the card component for this page design, I can see that along with the dark theme works great

**Comment by rak-phillip** [comment]
> I like the idea of reusing the card component, I'm not sure about stacking them in columns & the box-shadows.

The box-shadow is baked into the card component so maybe we can raise an issue to modify the default design of these? We can remove the box-shadow with little effort, but I'm of the mind that the box-shadow is something that should be additive and the default design of Card should reflect this. It's also much easier to add the box-shadows when they are needed.  

> Maybe having them in rows and without the box-shadow (maybe even removing the border (?)) would keep it a more consistent look?

Is this more in line with what you are suggesting?

![image](https://user-images.githubusercontent.com/835961/235982497-458f3371-beec-4a15-b691-9da8204dd13c.png)

**Comment by manuelecarlini** [comment]
Personally, I still think the 3 vertical columns design looks better,
but if we decide to use cards I'd propose this adjustment to make it more clear where 
one ends and the other begins.
This is also because I was looking at those screenshots with my secondary monitor and the shadows around the cards were not visible. So, no line under the title and buttons at the bottom right.

![troubleshooting-new](https://user-images.githubusercontent.com/6459624/236500999-0252b3ff-73fa-48de-bc8a-c3527b9193b9.jpg)

**Comment by rak-phillip** [comment]
We can override styles for the card component in Rancher Desktop but I think it's best to modify the core component to ensure that it's flexible enough to meet our needs. I've created the following issues to address the box shadow and horizontal rule:

- rancher/dashboard#8798  
- rancher/dashboard#8799

We might want to discuss with the rest of the UI team to make sure that these changes are clearly communicated.

@manuelecarlini @scures @gaktive
