### ISSUE TITLE
Standard formatting should be applied in the Extensions description

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#4468]
### Actual Behavior

By clicking on the extensions from the catalog, it's possible to verify that there is no formatting in terms of title and description of extensions, just a difference in the font size.

### Steps to Reproduce

1. Launch Rancher Desktop
2. From the main window, access the Extensions catalog
3. Select each extension
4. Check the formatting of the extension's description

### Result

There is no pattern in terms of titles and description. E.g Logs explorer has emojis whereas epinio has not. Tachometer has a single line with a much smaller font size.
<img width="1168" alt="Screen Shot 2023-04-14 at 8 47 43 PM" src="https://user-images.githubusercontent.com/70187881/232181416-6fd38c7d-55ba-476d-b22c-a6e5c5f46907.png">
<img width="1168" alt="Screen Shot 2023-04-14 at 8 46 59 PM" src="https://user-images.githubusercontent.com/70187881/232181419-3224bc0d-5b10-47de-a6f8-757258f4fd6a.png">

<img width="1168" alt="Screen Shot 2023-04-14 at 8 46 00 PM" src="https://user-images.githubusercontent.com/70187881/232181370-61f84ed8-102d-4ece-b339-befefd165dfa.png">

### Expected Behavior

A pattern must be applied in the style of the extension's description.

### Rancher Desktop Version

1.7.0-1041-g54242d2c

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
Both the screenshot and the description is provided by the extension (in raw HTML), so there is very little we can do about the formatting.

Compare the display on Dockerhub:

https://hub.docker.com/extensions/docker/logs-explorer-extension
https://hub.docker.com/extensions/splatform/epinio-docker-desktop
https://hub.docker.com/extensions/julianb90/tachometer

Our Catalog entries display the description on top of the screenshot, but otherwise the presentation is identical.

We do not consider this to be a bug in Rancher Desktop.
