### ISSUE TITLE
Add Ability to Install/Uninstall Extensions Directly from Extension Catalog

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4576]
We want to add the ability to manage extensions directly from the extension catalog. Each extension card should provide a method for installing the extension if it is not installed, in addition to allowing for the extension to be uninstalled if it is installed. The extension catalog should also be able to filter by installed state.

## Acceptance Criteria
- [x] Each extension card in the extension catalog should have a method for installing/uninstalling the extension.
- [ ] When a user installs an extension, the install button should be replaced with a "Remove" button.
- [ ] When a user removes an extension, the "Remove" button should be replaced with an install button.
- [ ] If the installation or uninstallation fails, the user should be notified and the button should remain the same.
- [x] The extension catalog should be able to filter extensions by installed state.

**Comment by IsaSih** [comment]
Minor issues to be fixed:
1. Once an extension is installed, the button is replaced with a "Remove" button instead of "Uninstall".
2. Once a user uninstalls an extension, there are no notifications displayed stating that the uninstallation was successful. Nor that the installation was successful.
3. When installation fails, the error message displayed is "Unprocessable Entity". I believe it should be more intuitive like "Installation failed. Please, try again."
Moving back to to do to update the documentation and fix the described minor issues.
