### ISSUE TITLE
Display how much space a snapshot consumes on disk in UI

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4597]
We should show how much hard drive space any given snapshot consumes. This will make it easier to understand how much disk space Rancher Desktop snapshots take up as a whole and will help inform users on which snapshots can be deleted if they need to free up space.

## 🔳 Acceptance Criteria

- [ ] Given a collection of snapshots, each snapshot displays the total amount of disk space it consumes in a user-friendly format, such as gigabytes or megabytes.
- [ ] The space consumed by each snapshot is accurate, taking into account any compression or deduplication that may be in place.
- [ ] The snapshot list displays the total amount of disk space consumed by all snapshots.
- [ ] The snapshot list can be sorted based on the amount of disk space each snapshot consumes, in ascending or descending order.

**Comment by jandubois** [comment]
> We should show how much hard drive space any given snapshot consumes. This will make it easier to understand how much disk space Rancher Desktop snapshots take up as a whole and will help inform users on which snapshots can be deleted if they need to free up space.

This is not as trivial as it sounds. At least on macOS I expect us to use `clonefile()` to copy the data, so it would not take up any additional space until the user modifies the current instance (due to copy-on-write semantics).

We may be able to do something similar on Linux on e.g. btrfs.

So the user may not get back as much space as expected based on the reported sizes.

There is also the issue of reporting actual used size for sparse files, but that is easier to implement (basically run `du` on the image).

**Comment by gaktive** [comment]
I'll add the related backend ticket here.

**Comment by gaktive** [comment]
#5556 is the related backend ticket for listing snapshots and their disk usage. #5557 is kinda related though it's more on the anticipate size front.
