### ISSUE TITLE
Define behavior when snapshots fail to create

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#4599]
If the snapshot could not be saved successfully, then any partial snapshot data should be deleted.

We probably should write some kind of sentinel once the snapshot is complete, to indicate that creation has not failed somewhere in the middle.

## Notes

- What happens when a restore fails? 
- How do we inform the user that a snapshot failed to create and what options do we provide to them?

**Comment by jandubois** [comment]
We still need to define the behaviour when a snapshot restore from the CLI failed while the app was not running.

There is no mechanism yet when the app is started to show information about the error that occurred.

We can't rely on the CLI reporting the error because the CLI may have crashed, or the machine rebooted etc.

**Comment by adamkpickering** [comment]
This issue seems outdated. @jandubois can we close it?

**Comment by gaktive** [comment]
Looks like we can close this until something specific comes up.
