### ISSUE TITLE
Update version checks for VZ emulation mode

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#4792]
Since we updated to Alpine 3.18 we now require macOS 13.3 on ARM64 machines because previous versions could not load the image.

Also VirtioFS depends on using VZ emulation mode, and not just Ventura.

**Comment by IsaSih** [comment]
So, does this mean the hover over VZ should indicate that the version of Ventura must be equal or superior to 13.3? 
Moving this back to todo because the label still indicates the version 13.0


![Image](https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/3f4202f5-7a74-4e1f-b885-e0bb1c20b900)
