### ISSUE TITLE
Got an error when using rdctl list-settings

### ISSUE THREAD

**Issue by RDLemos** [rancher-sandbox/rancher-desktop#5004]
### Actual Behavior

I have just updated Rancher Desktop from version 1.8.1 to version 1.9.0. The application seems to be running fine, and I have a deployment profile that I have used without problems with rancher 1.8.1.

When I try to check the configuration using:

`rdctl list-settings`

I get the following error:
`Error: Get "http://localhost:6107/v1/settings": dial tcp [::1]:6107: connect: connection refused`

Other `rdctl` commands seem to be working fine.

I do not find where this port 6107 is set ( or if it is hard-coded), or why is is being for list-settings.

### Steps to Reproduce

1) Update rancher desktop from version 1.8.1 to version 1.9.0.
2) use `rdctl list-settings` to verify the current deployment profile settings.

### Result

`Error: Get "http://localhost:6107/v1/settings": dial tcp [::1]:6107: connect: connection refused`

### Expected Behavior

List the current deployment settings 

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

1.26.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS Ventura 13.4

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
Port 6107 is hard-coded [here](https://github.com/rancher-sandbox/rancher-desktop/blob/80be3cada112ea1858f89c1e647266b5f9db73fd/pkg/rancher-desktop/main/commandServer/httpCommandServer.ts#L32); that's actually the port for the internal HTTP server that `rdctl` is using for more-or-less all of its functionality.  For example, `rdctl extension…`, `rdctl set…`, `rdctl start…`, and `rdctl shutdown…` are all talking to the same port.

When you mention that _other `rdctl` commands seem to be working fine_, do you mean one of those? Because that would be very odd that only one of those is working correctly. Does `rdctl api /v1/settings` (which is what `rdctl list-settings` does under the hood) work?

**Comment by RDLemos** [comment]
Hi Mook-as,
I have tried other rdctl commands. start and shutdow are working ( even tough shutdown gave a different message. rdct set gives the same error. See output below.

```
❯ rdctl set --kubernetes.enabled
Error: Put "http://localhost:6107/v1/settings": dial tcp [::1]:6107: connect: connection refused
```
```
❯ rdctl start
INFO[0000] About to launch /usr/bin/open -a /Applications/Rancher Desktop.app ...
```
Shutdown is not possible (rancher desktop is running)
```
❯ rdctl shutdown
Rancher Desktop is currently not running (or can't be shutdown via this command).
```

**Comment by RDLemos** [comment]
> Does rdctl api /v1/settings (which is what rdctl list-settings does under the hood) work?
No. It shows the same error:
```
❯ rdctl api /v1/settings
Error: Get "http://localhost:6107/v1/settings": dial tcp [::1]:6107: connect: connection refused
```

**Comment by mook-as** [comment]
Ah, okay, so if I'm understanding correctly:
- `rdctl` is always contacting `[::1]:6107`, and it's failing to connect
- … because the app is actually listening on `127.0.0.1:6107` (i.e. IPv4, instead of IPv6).
- And somehow the fallback to `127.0.0.1` isn't working as it should (which is weird).
- None of the commands (that use the backend) is actually working. (Sorry, I made a mistake, `start` just launches the executable directly.)

This means:
- In the short term, we need to modify the client to connect to `127.0.0.1` (i.e. force IPv4) instead of [`localhost`](https://github.com/rancher-sandbox/rancher-desktop/blob/a068c816b82d2249a21ecf559ad1f1b88aec3c56/src/go/rdctl/pkg/config/config.go#L98).
- As a temporary workaround, you may be able to edit `~/Library/Application Support/rancher-desktop/rd-engine.json` to add `"host": "127.0.0.1"` to force it to use IPv4.  This is kind of a terrible workaround, though, since that file gets rewritten every time Rancher Desktop starts.
- Perhaps we can look into using unix sockets (named pipes on Windows) instead? (That would take longer, though.)

**Comment by RDLemos** [comment]
Thanks or your help mook-as! I have actually checked my /etc/hosts, and fixed the problem by adding `127.0.0.1	    localhost`. I had only `::1 localhost`, and `127.0.0.1 <my_computer_name>` set. This is what I got now, and it is working.

```
## localhost
255.255.255.255	broadcasthost
::1                             localhost
127.0.0.1	                my_computer_name
127.0.0.1	                localhost
```

**Comment by mook-as** [comment]
Great! I think we should keep this open for now to make it work without the entry, but it's good that your issue is solved (for now).

**Comment by jandubois** [comment]
You can also use `rdctl --host 127.0.0.1 ...` but I agree that this should be the default instead of `localhost`.
