### ISSUE TITLE
RD should prevent users from selecting 9p w/ VZ

### ISSUE THREAD

**Issue by jsoref** [rancher-sandbox/rancher-desktop#5053]
### Actual Behavior

RD breaks because VZ emulation isn't compatible w/ 9p volume sharing

### Steps to Reproduce

1. Open RD Preferences
2. Select Virtual Machine
3. Select Volumes
4. Select `9p`
5. Select Emulation
6. Select `VZ`
7. Select `Enable Rosetta` (not required, but, it's an attractive nuisance, so I clicked it!)
8. Click Apply

### Result

```
Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura exited with code 1
```

```
    '--tty=false',
    '0'
  ],
  stdout: '',
  stderr: 'time="2023-06-26T11:44:57-04:00" level=info msg="Using the existing instance \\"0\\""\n' +
    'time="2023-06-26T11:44:57-04:00" level=fatal msg="field `mountType` must be \\"reverse-sshfs\\" or \\"virtiofs\\" for VZ driver , got \\"9p\\""\n',
  code: 1,
  [Symbol(child-process.command)]: '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura start --tty=false 0'
}
```

### Expected Behavior

Preferences should warn me at the various screens and apply shouldn't be abled if the settings are incompatible.

VirtualBox has states like this where it leaves an info bar in the window while there are incompatible settings.

Note that I should be able to change either the VM type or the Mount type to get out of the mess, I shouldn't be forced to go to a specific one to start getting out of this mess.

### Rancher Desktop Version

1.9.0

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

13.4.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I'm wondering if the UI should prevent users from **selecting** incompatible options at all. Maybe it should just prevent them from **applying** incompatible options. That way we don't force users to manipulate settings only in a prescribed order.

E.g. right now you have to first select emulation mode VZ before you can select the mount type VIRTIOFS. If you want to switch back to QEMU, you first have to switch the mount type back to REVERSE-SSHFS before you can change the emulation mode.

And this only works because we have one mount type that works for both modes. If (making this up) QEMU only supported REVERSE-SSHFS and VZ only supported 9P and VIRTIOFS, then there would be no way to switch from QEMU to VZ because the mount type would be invalid, and you cannot switch 2 settings at once.

So if we only enforce settings compatibility in the validator, we get part of the way there[^1]:

![CleanShot 2023-07-04 at 15 20 58](https://github.com/rancher-sandbox/rancher-desktop/assets/78947/98710596-b8cf-417b-b06b-a944d7eaf69f)

There are 2 problems with it though:

1. The status area to the left of the Apply button is used to show the "restart reasons" and under certain conditions will display the "Kubernetes will restart" message instead of the validation failure.

2. The validation failure message references the CLI variable name `experimental.virtual-machine.type` which doesn't help the user to find the place in the UI to change it (the Emulation tab).[^2]

    ```
    $ rdctl set --experimental.virtual-machine.mount.type 9p
    Error: errors in attempt to update settings:
    Setting experimental.virtualMachine.mount.type to "9p" requires that experimental.virtual-machine.type is "vz".
    ```

So while I think that letting validation handle all this is the right way to go, I also feel like the UX of validation will need a lot of work to get there: how do we guide the user to the incompatible settings? Can we make the errors clickable?

[^1]: The screenshot is from https://github.com/jandubois/rancher-desktop/commit/43c0693, but modified to make it incompatible with qemu instead of vz for testing purposes.

[^2]: There is also an unrelated bug that `experimental.virtualMachine.mount.type` should be `experimental.virtual-machine.mount.type`.

**Comment by jsoref** [comment]
I'd suggest adding an extra row for the warning message bubble.

Here's what VirtualBox 7.0.8 (beta for arm) does:
<img width="811" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/2119212/da528e1e-9cce-4fc7-b648-a66e13db013d">

The bubble appears when I hover over the invalid settings indicator:
<img width="811" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/2119212/3a4cc265-5be8-4367-82f1-830912e7bf1e">

Note: I definitely endorse blocking `Apply` as opposed to blocking selecting settings for exactly the reasons you're describing.

I'd half argue in favor of trying to move the settings that are incompatible to the same pane so that users don't have to travel to multiple panes to resolve incompatible settings.

**Comment by kwwii** [comment]
I suggest adding an inline alert banner above/below/near the options themselves to inform the user that the given option is disabled because they another option in another tab needs to be enabled first.

For example, 9p would have an alert banner which informs the user that they need to navigate to the Emulation tab and enable the QEMU option in order to enable this control.

Any option which is disabled due to another option not being set should display a banner near the option itself explaining to the user what they need to do to enable it.

**Comment by rak-phillip** [comment]
It sounds like #4003 can influence how we might approach validation in a scenario like this.

**Comment by jandubois** [comment]
> Are these all the possible combinations or am I missing something?

virtiofs is supported with qemu on Linux as well, but not on macOS.

This needs to be updated in the backend validator as well, so the CLI returns an error too.

**Comment by jandubois** [comment]
> Any option which is disabled due to another option not being set should display a banner near the option itself explaining to the user what they need to do to enable it.

This will work for now because doing proper validation will still require a lot of preparation.

But as I noticed above, this mechanism does not work in general, i.e. when there is no valid path between 2 configuration because at some point 2 options would have to be changed simultaneously for it to remain valid.

Fortunately we don't have any settings like that right now.

**Comment by s0nea** [comment]
> virtiofs is supported with qemu on Linux as well, but not on macOS.
> 

Okay, thank you!
Just for reference: at the moment we don't show virtiofs on Linux at all. See e.g. https://docs.rancherdesktop.io/ui/preferences/virtual-machine/volumes and acceptance criteria "Verify the cases where the tabs are preserved across different platforms, but some of its inner options should be displayed only in their supported platfroms. e.g. virtiofs MUST NOT be available on Linux" in https://github.com/rancher-sandbox/rancher-desktop/issues/4181.

**Comment by jandubois** [comment]
> e.g. virtiofs MUST NOT be available on Linux

Yeah, that was wrong; very likely my mistake. I'm sorry. Let's fix it for 1.10.

It is also wrong in the settingsValidator; it also assumes that it is only available with VZ.

**Comment by jandubois** [comment]
Lima references:

VZ (only available on macOS) supports `reverse-sshfs` and `virtiofs`:

https://github.com/lima-vm/lima/blob/c11f1bf5a937ad37506c1b79fe832a47b80862d5/pkg/vz/vz_driver_darwin.go#L44-L46

QEMU supports `reverse-sshfs` and `9p` everywhere, but `virtiofs` only on Linux:

https://github.com/lima-vm/lima/blob/c11f1bf5a937ad37506c1b79fe832a47b80862d5/pkg/qemu/qemu_driver.go#L47-L50

**Comment by IsaSih** [comment]
While testing this issue, I found on macOS that the settings validator is not working at the CLI level. Will move this issue to done, as the UI is behaving as expected by preventing users to select incompatible settings. Issue #5542 will address the settings validator in the backend.
