### ISSUE TITLE
rancher-desktop cli missing in Windows terminal

### ISSUE THREAD

**Issue by ulkas** [rancher-sandbox/rancher-desktop#5112]
### Actual Behavior

after a generic windows update i suddenly lost the terminals for ubuntu (wsl), rancher-desktop and rancher-desktop-data. 
a hint might be that when i opened the wsl terminal from windows menu directly, it prompted me to enter new superuser and password for ubuntu, like it was a fresh installation after the windows update. after that im able to see the ubuntu cli but still no rancher.
reinstalling rancher didnt help. deleting the settings.json in windows terminal also didnt help.
![image](https://github.com/rancher-sandbox/rancher-desktop/assets/4291621/f7c0fa10-240d-487d-9fbb-90c7b84a1123)

### Steps to Reproduce

none

### Result

access to the rancher-desktop terminal window

### Expected Behavior

rancher-desktop shall be listed in the windows terminal list

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.23.8

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

windows 10 enterprise 21H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by ulkas** [comment]
adding output of the `wsl --list --verbose` command in PS:

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/4291621/342c5857-0222-44d7-985f-4cee84ee9c65)

**Comment by mook-as** [comment]
Unfortunately we're not doing anything there (we didn't even add it to Windows Terminal, it just picked it up because it's a WSL distribution). Which is to say, you might need to ask the [Windows Terminal](https://github.com/Microsoft/terminal/) folks about it. Sorry about that.

If anything, we need to at some point implement making Windows Terminal skip `rancher-desktop-data` (since everybody, including our app, should be accessing it via `rancher-desktop`) anyway…

**Comment by jandubois** [comment]
> If anything, we need to at some point implement making Windows Terminal skip `rancher-desktop-data`

This has actually been implemented in Windows Terminal now, and is the reason both distros are no longer listed: https://github.com/microsoft/terminal/pull/15166.

So the behaviour reported in this issue is intentional.

The only supported mechanism to run a shell in the `rancher-desktop` distro is via `rdctl shell` because that also takes care of setting up the correct network namespace etc.
