### ISSUE TITLE
init binary missing in vm

### ISSUE THREAD

**Issue by Congee** [rancher-sandbox/rancher-desktop#5150]
### Actual Behavior

`nerdctl` does not respect the `--init` command line argument, nor does `nerdctl compose`

### Steps to Reproduce

`nerdctl run --init -it --rm busybox:latest /bin/true`

### Result

`FATA[0000] init binary "tini" not found`

### Expected Behavior

/bin/true just runs

### Additional Information

`nerdctl` officially supports it, it is just the default `tini` binary being nonexistent. As soon as I grabbed a `tini` binary to $PATH in the VM via `rdctl shell`, `nerdctl --init` starts to work. Note that the VM that rancher desktop builds against musl, the official tini binary released is built against glibc. So I grabbed a static binary. You may have a good reason to build and distribute a dynamic library against musl on your own.

See:
https://github.com/containerd/nerdctl/blob/dcb346715e6a740592efb77914695deeff96c2e7/docs/command-reference.md?plain=1#L161-L164
[tini-static-arm64](https://github.com/krallin/tini/releases/download/v0.19.0/tini-static-arm64)

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

v1.26.3+k3s1

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.4.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
`tini` is already installed inside the image under the name `docker-init`. You have to reference it explicitly by name if you use `nerdctl` because it has the `tini` name embedded as the default:

```console
$ nerdctl run --rm --init --init-binary docker-init busybox /bin/true
```

You can also create a `tini` symlink with

```console
$ rdctl shell sudo ln -sf /usr/bin/docker-init /usr/bin/tini
```

We'll be creating the symlink automatically in the next release.

**Comment by Congee** [comment]
Closing as it seems either fixed or a false alarm, though I don't have a chance to test it.

Thanks!

**Comment by jandubois** [comment]
> Closing as it seems either fixed or a false alarm, though I don't have a chance to test it.

It is not yet fixed; you need to either manually create the symlink, or specify the `--init-binary`. It will be fixed in 1.10.

I'm re-opening the issue until the fixes have been merged and tested.

**Comment by midnight-wonderer** [comment]
### For those who reach here via Google
If you run `containerd` directly on your machine, you are probably having an unrelated issue.  
Make sure `tini` is in your `PATH` on the host machine.

If you are on OpenSUSE, you need:
~~~bash
sudo zypper install tini
ln -s /usr/sbin/tini ~/.local/bin/tini
~~~

### Advertisement
I borrow the space of this project for you; let's help them promote it.  
`Rancher Desktop` is similar to `Docker Desktop,` but the licensing might be of interest to you; please check them out.

If you are on OpenSUSE, that's great because this project is made by the same company. It also works on other distros, including Ubuntu.

However, for day-to-day development tasks, I recommend sticking with bare containerd if you are on Linux. This is because Rancher Desktop will create additional layers of virtual machines, potentially degrading performance and the development experience. If you are on OSX or BSD, it doesn't matter; you'll get the same kind of virtualization one way or another.

Whenever you think of Docker Desktop, don't forget you have Rancher Desktop as an option, too.

**Comment by jandubois** [comment]
> I recommend sticking with bare containerd if you are on Linux. This is because Rancher Desktop will create additional layers of virtual machines

This true, but an advantage of the additional layers is that you can run a factory reset and start over with a clean slate. Or you can use snapshots to save/restore different configurations.

We originally planned to only support Rancher Desktop on macOS and Windows, and only added Linux support because a significant number of users asked for it.
