### ISSUE TITLE
Kubectl auto completion with binary installed by rd is very slow

### ISSUE THREAD

**Issue by zhuoyuan-liu** [rancher-sandbox/rancher-desktop#5216]
### Actual Behavior

Kubectl binary installed by rancher desktop auto-completion is significantly slower than original/installed using brew. 

Not sure if there is any conflict with https://github.com/Azure/kubelogin

**Every restart, the Rancher desktop will rewrite the PATH with `$HOME/.rd/bin`. Is there any way we can disable this step?**

### Steps to Reproduce

Try to run several kubectl commands with auto-completion using different binary files.

### Result

Rancher deskop is the slowest one.

### Expected Behavior

All the binary should be the same speed.

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.26.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS 13.4.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> Kubectl binary installed by rancher desktop auto-completion is significantly slower than original/installed using brew.

I suspect this happens because the `kubectl` installed by Rancher Desktop is really [kuberlr](https://github.com/flavio/kuberlr), which will check the server version before picking a compatible `kubectl` version from the cache. This will be slow when the apiserver is not responding (at all, or slowly).

> **Every restart, the Rancher desktop will rewrite the PATH with `$HOME/.rd/bin`. Is there any way we can disable this step?**

You can configure this in the [Environment](https://docs.rancherdesktop.io/ui/preferences/application/environment) preferences.

**Comment by zhuoyuan-liu** [comment]
Thanks @jandubois for your quick answer.

The Environment config solved my issue.
