### ISSUE TITLE
macOS upgrade from 0.3.0 to 0.4.1 moby/buildkit	still present

### ISSUE THREAD

**Issue by bdekany** [rancher-sandbox/rancher-desktop#531]
Hi

I did an upgrade from 0.3.0 (based on Moby Buildkit) to 0.4.1 (based on new lima + qemu)

The images tab still show me the old(?) images

moby/buildkit | v0.8.3 | cf14c5e88c0eb | 56.5MB
-- | -- | -- | --

Is it normal? Should we provide a cleanup procedure before upgrade?
How to remove it?

Rancher Desktop: 0.4.1
OS: macOS 11.5.2
arch: x86_64

**Comment by agracey** [comment]
The buildkit image is actually for KIM to do builds with and wasn't impacted by the shift of the underlying VM runner to lima.

**Comment by jandubois** [comment]
It is not possible that images could have survived the upgrade from 0.3.0 to 0.4.x because the old VM and data was destroyed and a completely new data volume (and VM) have been created.

However, for future upgrades we do expect to retain the images. That will be an intentional feature, so you won't have to pull down images again (or build them again using kim). We actually expect your workloads to continue running when you start up the new Rancher Desktop with the existing VM (after the upgrade to 0.5.0). 😄 

> Should we provide a cleanup procedure before upgrade? How to remove it?

We expect this to happen automatically as space runs low on the VM data volume via [Garbage Collection of unused images](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images).
