### ISSUE TITLE
Remove extensions feature flag

### ISSUE THREAD

**Issue by rak-phillip** [rancher-sandbox/rancher-desktop#5365]
In nuxt/vue configs, we specify a feature flag for extensions. This could be removed, as the feature is released in production.

              For a follow-up: we should remove this. (But not in this PR.)

_Originally posted by @mook-as in https://github.com/rancher-sandbox/rancher-desktop/pull/5287#discussion_r1291693218_

**Comment by jandubois** [comment]
This seems to refer to this feature flag: https://github.com/rancher-sandbox/rancher-desktop/blob/b1722036174330a079b54983c71ed4ff94313211/pkg/rancher-desktop/vue.config.js#L52

This seems to be used to modify the behaviour of the Diagnostics page.

I don't understand what is meant by "is released in production". It seems to be disabled by default.

So should we enable it by default and get rid of the flag? Or are the fixes not needed, because we did not enable them?

I'll put this into the next milestone solely to find out what we need to do, not to necessarily make the change right away.

**Comment by rak-phillip** [comment]
@jandubois I think this issue had to do with the `featureExtensions` environment variable. It's a constant that always returns `true`. I think this is what I meant by "the feature is released in production" - the flag initially existed to allow for toggling extensions features during development.

**Comment by jandubois** [comment]
> think this issue had to do with the `featureExtensions` environment variable.

Ah, ok, my bad. So that would be just deleting this variable everywhere, right? I will do this myself.

Do you remember what `RD_ENV_DIAGNOSTICS_FIXES` is for? Is this work-in-progress that was abandoned? Or why is it not enabled by default?

Don't bother researching it, if you can't remember; I can run `git blame` to see what it relates to.

PS: I don't know why I have closed this issue; that was unintentional. 😄

**Comment by rak-phillip** [comment]
> Do you remember what RD_ENV_DIAGNOSTICS_FIXES is for? Is this work-in-progress that was abandoned? Or why is it not enabled by default?

I would need to do the same `git blame` to refresh my memory for this one. 😆

**Comment by jandubois** [comment]
> I would need to do the same `git blame` to refresh my memory for this one. 😆

Thanks, in that case I'll do it myself.
