### ISSUE TITLE
Why is Rancher Desktop using %APPDATA% at all?

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5378]
The `%APPDATA%` environment variable points to the roaming profile which is stored on the network and shared between multiple computers.

The files Rancher Desktop creates under `%APPDATA%` are all specific to the local installation of Rancher Desktop and should be stored under `%LOCALAPPDATA%` instead.

If the user runs Rancher Desktop on multiple Windows machines, then the different installations will overwrite each others configuration.

```
08/22/2023  11:57 AM                86 credential-server.json
08/01/2023  03:27 PM    <DIR>          provisioning
08/22/2023  11:57 AM                86 rd-engine.json
08/22/2023  11:57 AM             1,141 settings.json
```

There are several issues in the backlog mentioning the roaming profile that might be fixed by moving all data to local storage.

**Comment by mook-as** [comment]
`provisioning` and `settings.json` makes sense there, because those should apply regardless of which machine you're on.  `credential-server.json`, `rd-engine.json` are both runtime configuration we write out and should be in `%LOCALAPPDATA%`.

(I've previously encountered the roaming profile situation in university, where `%APPDATA%` is on NFS, and `%LOCALAPPDATA%` isn't ported across when you login on a different machine — think hot-desking.)

**Comment by jandubois** [comment]
> `provisioning` and `settings.json` makes sense there,

Why?

What if I have 2 machines, and I want to run Rancher Desktop with `moby` on one, and use Kubernetes with `containerd` on the other? This becomes impossible if both machines share their `settings.json`. And I could make similar arguments about `provisioning`, although you could work around this by checking the machine name in the provisioning scripts[^1].

The `settings.json` file is more closely coupled with the current VM instance and not some general per-user settings. With the upcoming snapshot feature we will save and restore settings with the snapshot. This operation is again local to the machine as the VM is not a network-wide singleton.

[^1]: In the medium term I would want to fold provisioning scripts (or at least a single script) into `settings.json`, so it could be controlled by deployment profiles (and ideally edited via the Preferences UI).

**Comment by mook-as** [comment]
> What if I have 2 machines, and I want to run Rancher Desktop with moby on one, and use Kubernetes with containerd on the other? 

That isn't what a roaming profile is about; if you have that, you want to be able to log in into any of the machines and get what looks like the same machine.  Your use case is more of a person (not using AD roaming) with two machines, possibly with the same Microsoft account; in which case, nothing roams at all.

**Comment by jandubois** [comment]
> That isn't what a roaming profile is about

Exactly my point!

Since the VM cannot roam, the configuration of the VM shouldn't roam either. It is by essence a non-roaming application. You can't "hot-desk" it. Even if you share the `settings.json` between machines, the images inside the VM and the deployed workloads simply cannot roam; you have local instances on each machine.

So why do you think it makes sense to store `settings.yaml` in the roaming profile if it can't roam? I feel like we are mis-communicating here.

**Comment by byjrack** [comment]
So I think both are valid scenarios.  I know I have to test on a bunch of machines and get to a repro when a user reports a problem.  So changing configs on all runs may not be ideal.  Converse is in our virtual space starting from scratch with a config may seem annoying.  

This is a chicken and egg problem though since you can't just set a flag for roaming or local since you would normally set that in your settings.json.  You can do that in the init logic though to try Roaming first and then go Local so if someone decided to put their JSON in a profile or a redirected folder than it would be used, but otherwise it will stick Local.

In general I would probably lean more toward LOCALAPPDATA for RD's config.  We use redirection and not the classic roaming profile model, but I can't think of a ton of configs in RD that I would expect to roam.  It's not like bookmarks and extensions in Chrome where the UX sufffers greatly if you have to recreate them.  And it's not like images and compose or k8s deploys will roam with you.  Environment configs like proxy or locks I would expect to leverage the OS configs (our proxy config differs in a number of environments) or the HKLM settings an admin has pushed down for whatever reason and not for Users to make.

And while there are similar solutions for macOS and Linux you start to create some feature skew in the docs that can be confusing for users.  I just don't see enough value for roaming to override the possible issues that you might create.
