### ISSUE TITLE
Container running on Localhost cannot be accessed with experimental tunnel and Moby engine in WSL2

### ISSUE THREAD

**Issue by pshutt97** [rancher-sandbox/rancher-desktop#5396]
### Actual Behavior

When using the experimental tunnel feature and the Moby engine with WSL2, containers running on localhost with WSL cannot be accessed on the host machine or via browser.

### Steps to Reproduce

Use Moby container engine.
Run container on localhost or 127.0.0.1.
Use experimental tunnel feature on WSL2.
Try to access the running container from browser localhost with the port.

### Result

The running container cannot be accessed from a browser or the host machine.

### Expected Behavior

The running container should be able to be accessed from a browser or the host machine.

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Cisco AnyConnect, Zscaler, Microsoft Defender and Symantec Endpoint Protection

**Comment by IsaSih** [comment]
By testing this issue, here are my findings:
1. When I enable the networking tunnel BEFORE running the container in localhost, I can successfully access it via browser/ host machine
2. When I first run the container on localhost and AFTER enable the networking tunnel, then I can't connect to localhost neither via browser nor via the host machine.

I'm reopening the issue so that @Nino-K can investigate this further.

**Comment by Nino-K** [comment]
@pshutt97 Thanks for reporting this, I managed to repro this by restarting Rancher Desktop as @IsaSih mentioned in her comment. The fix should be included in `1.11`.

**Comment by pshutt97** [comment]
Awesome!! Thank you!!!
