### ISSUE TITLE
Locked checkboxes  are white, not greyed out

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#5448]
### Problem Description

Once there's a locked deployment profile, the Preferences dialog and the main window show checkboxes with white filling, and are not greyed out like the other components, make it confusing for the user to know that these fields are locked at a first look. As for now, just the lock icon indicates the fields are locked.

<img width="760" alt="Screen Shot 2023-09-01 at 5 51 37 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/70187881/7d259f2c-45f6-4ac7-8e64-0aa3171daa10">

### Proposed Solution

Locked checkboxes should be greyed out.

**Comment by s0nea** [comment]
Hi @IsaSih,

Thank you for testing and opening the issue!

As far as I can tell, the checkbox is correct the way it is. If it was grayed out, the user would not be able to differentiate between **locked** and **locked + disabled**. Please see https://github.com/rancher-sandbox/rancher-desktop/issues/3959#issuecomment-1525300555 and  https://github.com/rancher-sandbox/rancher-desktop/issues/4664#issuecomment-1557219899 for more information.

**Comment by jandubois** [comment]
> the checkbox is correct the way it is

I can confirm that it matches the spec.

I do agree with @IsaSih though that it would make more sense to have the locked checkboxes greyed out. We do the same thing for dropdown listboxes, so why treating checkboxes differently is confusing for users.

Should be discussed in UI/UX sync meeting.

**Comment by jandubois** [comment]
> I can confirm that it matches the spec.

Looking more closely at https://github.com/rancher-sandbox/rancher-desktop/issues/3959#issuecomment-1525300555 I see that the locked checkbox does have a greyed out background:

<img width="145" alt="CleanShot 2023-09-05 at 11 12 52@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/8b89492b-b0ba-410a-aaae-ed64953f2b3d">

The difference to the disabled checkbox is that the checkmark is a solid black. In the disabled checkbox the checkmark is a darker grey:

<img width="137" alt="CleanShot 2023-09-05 at 11 13 48@2x" src="https://github.com/rancher-sandbox/rancher-desktop/assets/78947/880f927f-750e-4ba9-8eaa-fc1f120a62e2">

For disabled checkboxes you won't be able to tell the difference. But you still have the lock icon and tooltip so I think it is still good.

I haven't seen the same mockup for darkmode, but I would expect it to work similarly, with a lighter grey checkmark to indicate the setting is disabled instead of locked.

Please ignore the difference in colour between the 2 greyed out checkbox; they are supposed to use the same colour. See also https://github.com/rancher-sandbox/rancher-desktop/issues/4664#issuecomment-1563139183 for the same issue regarding listboxes.

**Comment by s0nea** [comment]
Yes, I see your point with the light grey background of the locked checkbox. I'm unsure if it should be the same color as the disabled one. If the background is very dark and the check is some kind of blackish too, the check is hard to recognize (in dark mode):

![239921819-acf027b7-b8fd-46b2-ab71-ec48db815994](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/351aafcf-ea12-4cac-b837-280f38b8cc63)

Lets discuss it in the UI/UX meeting

**Comment by jandubois** [comment]
> I'm unsure if it should be the same color as the disabled one.

Yes, it should be. We talked about this in the context of the listbox, which had initially different shades of grey for locked vs. disabled states, but later agreed that it should be the same colour because it represents the same fact to the user: you cannot change this control.

It is the difference in text colour that conveys the difference between "this value is ignore" (grey) vs. "you can't change this value, but it is in effect" (black).

**Comment by jandubois** [comment]
> As per our discussion we agreed on removing the third option.

I know we just agreed on that, but wasn't this just about the background? I thought we also said that the checkmark would be greyed out when setting is locked, just like for dropdown listboxes.

So you wouldn't be able to tell the difference when the box isn't checked, but when it is checked, the checkmark would still be a different colour.

**Comment by s0nea** [comment]
I think in case of the dark mode (as shown on the screen above https://github.com/rancher-sandbox/rancher-desktop/issues/5448#issuecomment-1707826137), the check is white :thinking: Or should this be changed too?

I'll still have to take a look at light mode but I assume it works accordingly.

I'll post some screenshots for both modes.

**Comment by s0nea** [comment]
Here are the screens for both modes:

**Light - checked (normal/disabled/locked)**
![Screenshot_2023-09-14_15-36-47](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/27eb5ac9-5b36-450d-a54a-c54683346ed4)

**Light - unchecked (normal/disabled/locked)**
![Screenshot_2023-09-14_15-35-40](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/5ba2e4dd-6638-4705-88d3-1c21e2c7c600)

**Dark - checked (normal/disabled/locked)**
![Screenshot_2023-09-14_15-11-58](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/c4879866-fc64-43fd-86f3-1ab3e1032e8d)

**Dark - unchecked (normal/disabled/locked)**
![Screenshot_2023-09-14_15-12-55](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/2af3ef75-e072-4ee0-9d87-226ba38cf784)

**Comment by jandubois** [comment]
I think this is good.

I'm wondering if a disabled checkbox should ever have a checkmark in it (wouldn't that be a contradiction to being disabled?), but that is a different issue. So far I don't think we even have any check boxes that can be in disabled state, so it is kind of pointless to worry about.

---

Looking at the unchecked normal checkbox in dark mode, I notice that in System Preferences it uses a medium-grey background instead of black. But maybe we should ignore this right now unless we are willing to make the disabled grey a lot lighter (in dark mode only).

**Comment by s0nea** [comment]
> I think this is good.

Thanks for confirming!

> I'm wondering if a disabled checkbox should ever have a checkmark in it (wouldn't that be a contradiction to being disabled?), but that is a different issue. So far I don't think we even have any check boxes that can be in disabled state, so it is kind of pointless to worry about.

Well... in general I think it's good to have the possibility to disable a checked checkbox. E.g. in situations where something is enabled but not editable. Sometimes the user might still require the information even though he can't change it. But these situations might not apply here.
