### ISSUE TITLE
Disabled + locked radio buttons are not visualized correctly

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#5527]
The bug came up as part of https://github.com/rancher-sandbox/rancher-desktop/issues/5449.

According to
![242025877-52db699d-db23-4698-b2a7-4bcee5f9534b](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/01d059e9-c33c-48a6-996a-f6fe02858ee0)

the **disabled + locked** should have a grey background. Which is currently not the case as you can see here
https://github.com/rancher-sandbox/rancher-desktop/issues/5449#issue-1878227047.

**Comment by jandubois** [comment]
Should the selected but locked button have a different colour?

Looking at check boxes, an unlocked selected checkbox has a white mark on a blue background. When it is locked it changes to grey background.

I can't tell how this should translate to radio-buttons though, without making them look disabled instead of just locked. For the checkboxes we have the checkmarks to distinguish them.
