### ISSUE TITLE
When called from UI, `rdctl snapshot ...` commands should print errors as JSON to stderr

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5570]
As it says in the title. Printing errors as JSON should make them easier for the UI to consume.

I propose indicating that `rdctl` is being called from the UI via a command line option. The name of the option hasn't been discussed, but it doesn't matter as long as it is descriptive. A couple quick, probably-bad ideas:
- `--ui`
- `--porcelain`

@torchiaf if this doesn't sound like a good idea, please say so. Either way, I'm sure you want to have input.

**Comment by jandubois** [comment]
> The name of the option hasn't been discussed

It should be some generic name, that can be used for all commands that produce output that might need to be parsed by other programs. Like `--output json`. I think I would be fine with just `--json` too.

**Comment by ericpromislow** [comment]
So I propose the output should be:
```
{ "errors"?: [ <ARRAY OF ERROR MESSAGE strings> ],
  "warnings"?: [ <ARRAY OF WARNINGS > ] # Right now we have no warnings
 }
```

(where the `?` means the field is optional, and you would never get a stderr payload of `{}`

Normally if there's an `errors` field, there shouldn't be any output to `stdout`. But if we ever add warning messages, we might end up with non-empty strings written to both `stdout` and `stderr`.

**Comment by jandubois** [comment]
> So I propose the output should be:

Sounds fine to me. The output should all be on a single line, not pretty-printed, because eventually it should become a streaming protocol using [Newline Delimited JSON](http://ndjson.org):

```json
{"status": "Saving snapshot data", "progress": 5}
{"status": "Saving snapshot data", "progress": 10}
{"errors": ["Out of disk space"]}
```

On further thoughts, I'm wondering if we really expect to receive multiple errors; I would expect the command to abort on the first error.

And I think it would be good to receive 2 strings: the error message, and a suggestion what the user should do before retrying the operation.

```json
{"error": "Out of disk space on /Volumes/MyData", "hint": "You will need to have at least 85GB of free space to take a snapshot of the current VM, but only have 30GB. Free up an additional 55GB before trying again!"}
```

**Comment by ericpromislow** [comment]
At this point, there is only at most one error message, so +1 on `"error":...`. The`hint` field is optional.

As long as we're sometimes providing a hint in JSON output, should it also appear in plain-text output?

**Comment by jandubois** [comment]
> At this point, there is only at most one error message, so +1 on `"error":...`. The`hint` field is optional.

Yes, the beauty of streaming JSON objects instead of plain text is that we can add fields at the time we need them, and not worry about breaking the parser. So we can just ignore the `hint` field for now.

> As long as we're sometimes providing a hint in JSON output, should it also appear in plain-text output?

I think so, yes. But I don't think we'll have hints in time for the 1.11 release, so let's concentrate on just getting a single error message back to the UI and iterate on it afterwards.

**Comment by adamkpickering** [comment]
> The output should all be on a single line, not pretty-printed, because eventually it should become a streaming protocol using [Newline Delimited JSON](http://ndjson.org/)

**Comment by jandubois** [comment]
> I had imagined us sending error JSON objects to stderr, and progress JSON objects to stdout. Might this ease parsing on the UI side?

I don't think so.

I think there should be no output to STDERR when streaming JSON output; everything goes through a single file descriptor. On the receiving side you know that the current object is an error object because it includes a non-empty `error` field.

I would think of this as a file based command server. Each object is processed as an individual "request" and will be forwarded to the UI as an event. The UI then updates the progress bar, or reports the error etc.

**Comment by torchiaf** [comment]
I think best things for the UI is to provide a JSON option for both output & errors; this will really simplify the parsing on the UI side. ATM this is done by Regex the results from `rdctl snapshot` commands.
