### ISSUE TITLE
Allow user to use snapshot ID or snapshot name as argument to `rdctl snapshot delete` and `rdctl snapshot restore`

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#5571]
Right now, `rdctl snapshot delete` and `rdctl snapshot restore` only accept snapshot ID as their argument. It should be possible to specify the snapshot to operate on via **either** its name or its ID.

**Comment by jandubois** [comment]
> It should be possible to specify the snapshot to operate on via **either** its name or its ID.

Sorry, I only noticed this when looking at the PR.

I disagree on using the ID in the API at all. The name is the unique key to identify a snapshot, and the ID is just a directory name because the snapshot name may not be a valid filename.

Or did I miss any reason why we would need to use the ID in the API?

**Comment by adamkpickering** [comment]
There are no good reasons for allowing the use of snapshot ID as an argument to a `rdctl snapshot` command. The best I can think of is that somebody may want to write a script that reads the snapshot directory names, and maps them over to snapshot IDs. But that is so unlikely that I'm not sure it even bears mentioning.

It's just the way I wrote it originally; there is no reason this can't change.
