### ISSUE TITLE
Spike: Define environment constraints for limactl.ventura

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#5909]
This is kind of a desperate idea to try to fix #4867:

It seems to only affect machines running fairly recent releases of macOS that also have some form of device management profile installed.

On those machines launching `limactl.ventura` is eventually blocked with an `EACCES` error by `mcxalr` (something like the 5th time the process is launched, not right away).

During my research I stumbled over [Launch Environment Constraints](https://developer.apple.com/documentation/security/defining_launch_environment_and_library_constraints), which seems like a more generic and modern version of the "Managed Client application launch restriction" of mcxalr.

The video [Protect your Mac app with environment constraints](https://developer.apple.com/videos/play/wwdc2023/10266) from WWDC 2023 mentions:

> Launch constraints [...] are enforced starting in macOS 13.3.

Now this feels a little bit like there might be a bug in the way the new launch constraints interact with the legacy mcxalr system.

So my wishful thinking is: Maybe if we define our own launch constraints on `limactl.ventura`, then the defaults from the legacy mechanism don't apply, and we can always start the `limactl.ventura` subprocess.

No way to find out than to give it a try...

**Comment by mook-as** [comment]
Some notes (I'll be editing this comment as I get more):
- MCX is parental controls, according to [this documentation](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html#//apple_ref/doc/uid/TP40005929-CH3-SW5).  However, that doc also says it's an admin thing (and signing is only involved for upgrades).
- The level of control this requires means we need to implement #1021 too (so that we can have better control of the signing); this likely also implies #4091.
