### ISSUE TITLE
Since 1.11.1 the kubernetes context in wsl is not switched using context menu "kubernetes contexts" on tray icon anymore

### ISSUE THREAD

**Issue by benzman81** [rancher-sandbox/rancher-desktop#6087]
### Actual Behavior

Only the kubernetes context in windows host is switched. The context in WSL stays untouched.

### Steps to Reproduce

- create a kubernetes config with multiple contexts
- use the context menu "kubernetes contexts" on tray icon to switch context

### Result

The kubernetes context in windows host changes, but not in WSL anymore.

### Expected Behavior

First, both kubernetes config files should be the same as before 1.11.1, because otherwise you have to maintain two seperate files, which is annoying.
Second, the use of the context menu "kubernetes contexts" on tray icon was to easily switch contexts in both, windows host and wsl. Now, there is no easy way to switch both contexts with a simple click.

### Rancher Desktop Version

1.11.1

### Rancher Desktop K8s Version

1.25.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows 10 Enterprise 10.0.19045 Build 19045

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

should be irrelevant

**Comment by jandubois** [comment]
Thank you for reporting this. We were making the (obviously incorrect) assumption that users would prefer to keep a separate kubeconfig inside their Linux distros because it becomes much easier to e.g. integrate with cloud provider toolkits.

It is unfortunately too late to revert this behaviour in time for Rancher Desktop 1.12: the reason we needed to create a separate config was because the Rancher Desktop cluster API was no longer listening on `localhost` inside the distro, but on a bridged gateway (because Rancher Desktop is now running in an isolated separate network namespace).

We'll investigate restoring the old behaviour again (using a forwarding proxy) for a later release. Sorry for the inconvenience in the meantime!

**Comment by Nino-K** [comment]
@benzman81 Thanks for reporting this, we did some work as part of https://github.com/rancher-sandbox/rancher-desktop/issues/6245 that should address this issue. This work will be included in our new upcoming release. You can try out our new release that will be coming out soon to see if it works for you. Meanwhile, I will go ahead and close this issue, if you encounter anything further feel free to reopen.
