### ISSUE TITLE
Ver 1.12.1 Win11 Pro fails to start

### ISSUE THREAD

**Issue by MHacker9404** [rancher-sandbox/rancher-desktop#6322]
### Actual Behavior

RD just spinning on `updating kubeconfig` and no config files are created

### Steps to Reproduce

install RD on Win11Pro with latest WSL2
enable network tunneling and WSL integrations
RD gets to `updating kubeconfig` and just spins
no config files created

### Result

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/4184348/99564758-6e00-4d92-a91f-69774fea60cc)

### Expected Behavior

I can use RD for kubernetes

### Additional Information

running the wsl-helper kubeconfig manually - I see the following error:
`C:\\Windows\\system32\\wsl.exe --distribution Debian11 --exec /mnt/c/'Program Files'/'Rancher Desktop'/resources/resources/linux/internal/wsl-helper kubeconfig --enable=true --rd-networking=true`

Error: Windows kubeconfig not supplied

[wsl-exec.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929705/wsl-exec.log)
[integrations.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929706/integrations.log)
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929707/background.log)
[shortcuts.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929708/shortcuts.log)
[wsl.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929709/wsl.log)
[k3s.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929710/k3s.log)
[wsl-init.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929711/wsl-init.log)
[diagnostics.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929712/diagnostics.log)
[wsl-helper.Debian11.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929713/wsl-helper.Debian11.log)
[host-switch.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929714/host-switch.log)
[dashboardServer.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929715/dashboardServer.log)
[k8s.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929716/k8s.log)
[update.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929717/update.log)
[server.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929718/server.log)
[settings.log](https://github.com/rancher-sandbox/rancher-desktop/files/13929719/settings.log)

### Rancher Desktop Version

1.12.1

### Rancher Desktop K8s Version

1.25.8

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Win11 Pro

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

no

**Comment by lukasjelonek** [comment]
I had the same problem with windows 10 pro. After upgrading from 1.11.1 to 1.12.1, rancher-desktop with moby engine did not complete start. After switching to `containerd` it started, but I required docker.

A look into the vm `wsl -d rancher-desktop` revealed, that `dockerd` could not start. Manually executing `dockerd` resulted in a segmentation fault and according to the logs I assume that the same happened for the automatic start.

My solution was to remove the `rancher-destop` distribution, so that it can be recreated on the next start of rancher-desktop:

```
# close rancher-desktop and then
wsl --unregister rancher-desktop
# restart rancher desktop, the distribution will be reinstalled
```

Now I can use docker again.

I assume that somehow either a corrupted or wrong dockerd-file was installed during the update, but I cannot check it anymore.

**Comment by jackmtpt** [comment]
@MHacker9404 are you using IIS or anything else on your Windows machine that's bound to tcp/80, 443 or 6443? If so try stopping that (see my comment on #6335) and see if it fixes things.

**Comment by MHacker9404** [comment]
no - any .Net apps are Kestrel - no dependency or usage of IIS/IIS Express - checked resmon - nothing using any of those ports locally

**Comment by jandubois** [comment]
@MHacker9404 From the comment in https://github.com/rancher-sandbox/rancher-desktop/issues/6335#issuecomment-1900803452 I understand that your log files do show port conflicts, so disabling Traefik should allow you to start Rancher Desktop normally.

Otherwise I've created issue #6341 to track the port conflict problem.

I'm going to close this issue; if you think your problem is not explained by the port conflicts, then please create a new issue, with a new set of log files, that show that host-switch had no problems binding to ports 80 and 443.
