### ISSUE TITLE
What exactly does the "WSL Integration"?

### ISSUE THREAD

**Issue by ontec-xrail** [rancher-sandbox/rancher-desktop#640]
There is really less documentation out there - when I installed rancher desktop I already had WSL2 (Ubuntu 20.04) running with docker configured in it (also dockerd running)
The installation of Rancher Desktop then created a new WSL image "rancher-desktop".
What does the "WSL Integration" do? Does Rancher Desktop then use the existing "Ubuntu 20.04" image? Can I delete the other one?

Actually my system is now screwed up -> the Gui is not showing anything (images or so) and also kim is showing an error ...

```
C:\Users\mbuchner>wsl -l -v
  NAME               STATE           VERSION
* Ubuntu-20.04       Running         2
  rancher-desktop    Running         2
```

```
C:\Users\xxx>kim images
time="2021-09-21T17:52:09+02:00" level=warning msg="Cannot find available builder daemon, attempting automatic installation..."
time="2021-09-21T17:52:30+02:00" level=warning msg="Get \"https://172.29.153.29:6443/api/v1/nodes\": dial tcp 172.29.153.29:6443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat."
Error: Get "https://172.29.153.29:6443/api/v1/namespaces/kube-image/services/builder": dial tcp 172.29.153.29:6443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
Usage:
  kim images [OPTIONS] [REPOSITORY[:TAG]]

Aliases:
  images, image list

Flags:
  -a, --all        Show all images (default hides tag-less images)
      --digests    Show digests
  -h, --help       help for images
      --no-trunc   Don't truncate output
  -q, --quiet      Only show image IDs

Global Flags:
  -x, --context string      kubeconfig context for authentication
      --debug
      --debug-level int
  -k, --kubeconfig string   kubeconfig for authentication
  -n, --namespace string    namespace (default "kube-image")

time="2021-09-21T17:52:51+02:00" level=fatal msg="Get \"https://172.29.153.29:6443/api/v1/namespaces/kube-image/services/builder\": dial tcp 172.29.153.29:6443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat."
```

```
kubectl get all -A -o name
I0921 17:51:29.270628    6284 versioner.go:56] Remote kubernetes server unreachable
Unable to connect to the server: dial tcp 172.29.153.29:6443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
```

![image](https://user-images.githubusercontent.com/68220434/134204809-d7d2e863-c2e5-400c-8f31-32bee8fdeef8.png)

![image](https://user-images.githubusercontent.com/68220434/134204881-6b40d3a9-010c-43f7-b4e1-d50db851ee41.png)

![image](https://user-images.githubusercontent.com/68220434/134204937-9070bac9-6216-42b3-8f63-6a4db7598a18.png)

Please provide more documentation!!!
- How can I restart rancher desktop?
- How can I clean uninstall rancher desktop (to do a clean reinstall)
- What does the "WSL Integration" do?
- Where can I find detail logs?

Thanks

**Comment by mattfarina** [comment]
> Please provide more documentation!!!

You are right that we need this. We plan on it in the near future. I've had recent discussions with folks to get this started. It should start after the 0.5 release.

> How can I restart rancher desktop?

If you choose File -> Exit it will shut down Rancher Desktop. Or, you can right click on the tray icon and choose to quit. Both of those will shut down the app.

> How can I clean uninstall rancher desktop (to do a clean reinstall)

There are two options.

1. If you go to Troubleshooting you can reset to defaults. This will remove all user data such as Kubernetes, any caches, and configuration, logs, and everything. After this Rancher Desktop should restart and start fresh.
2. In Add & Remove programs you can uninstall Rancher Desktop.

> What does the "WSL Integration" do?

This make the Kubernetes Configuration accessible in that WSL distribution so that you can use commands like `kubectl` to communicate with Kubernetes.

> Where can I find detail logs?

In the upcoming 0.5 release there is a _Logs_ button on the troubleshooting page. We wanted to make that easier.

In 0.4.1 you can go to `~\AppData\Local\xdg.state\rancher-desktop\logs`. Note, in 0.5 this location is moved to a more standard location `~\AppData\Local\rancher-desktop\logs`

If you have further questions please feel free to ask. We are working to improve the experience.

**Comment by mook-as** [comment]
- Re: WSL integration:
When it's turned on, we create a symlink in `~/.kube/config` in the given distribution to the one for Windows, so that the distribution can use `kubectl` etc. to talk to the Rancher Desktop kubernetes cluster.

- Re: paths:
We always put `C:\Users\<user-name>\AppData\Local\Programs\Rancher Desktop\resources\resources\linux\bin` in your user's `PATH` (via the setup exe), in addition to `…\win32\bin`; while that only contains Linux binaries (so it might not sound like it makes much sense), by default WSL will convert your Windows `PATH` and have that exposed in your Linux distributions, so it ends up when you run `kubectl` in your (non-rancher-desktop) WSL distribution it runs the binary out of the Rancher Desktop installation.

- Re: user:
WSL is per-user, so it's all under your user account.  Under the hood, WSL 2 runs a Hyper-V virtual machine (… insert lots of hand waving here), and does some NAT for network access.  Also, I believe the network namespace is shared (one distribution listening will be visible in another, they all have the same IP address, etc.); so I suspect you only need to do the `ifconfig` bit in one distribution for it to apply? From a brief test, I couldn't get the VM to set MTUs via a sysctl kernel command line option, so unfortunately that didn't work.

**Comment by donatelloOo** [comment]
WSL integration (or the missing/buggy part of it) is basically:
```
sudo chown root:docker /mnt/wsl/rancher-desktop/run/docker.sock
export DOCKER_HOST=unix:///mnt/wsl/rancher-desktop/run/docker.sock
export KUBECONFIG=/mnt/c/Users/<USER>/.kube/config
```
