### ISSUE TITLE
Dataloss when using virtiofsd on Linux

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#6582]
### Actual Behavior

`$HOME` on the _host_ (not the VM) is wiped out when using virtiofs on Linux.

### Steps to Reproduce

1. Install OpenSUSE Leap 15.5
2. Install qemu from `obs://Virtualization`
   1. `sudo zypper addrepo 'https://download.opensuse.org/repositories/Virtualization/$releasever' obs:Virtualization`
   2. `sudo zypper install --force --allow-vendor-change --repo obs:Virtualization qemu`
   3. (If you had qemu installed, allow the install)
3. Install Rancher Desktop (possibly from the repo)
4. Start Rancher Desktop
5. In Preferences → Virtual Machine → Volumes, select _virtiofs_ for the mount type.
6. Allow Rancher Desktop to start.
7. Quit Rancher Desktop
8. Delete the VM:
   > `LIMA_HOME=$HOME/.local/share/rancher-desktop/lima/ /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl delete 0`
9. Start Rancher Desktop

### Result

`$HOME` is emptied; only newly created files remain. That's dataloss on the _host_, not the VM.

### Expected Behavior

If Rancher Desktop fails to start up, the files on the host doesn't get removed.

### Additional Information

```
> /usr/lib/virtiofsd/virtiofsd --version
virtiofsd 1.10.1
```

This appears to happen right around the time the an error pops up saying the Kubernetes fails to start. Note that no logs are listed (because the log directory got wiped out, probably).

This doesn't happen if the VM isn't manually deleted first.

If we start Rancher Desktop from a fresh install / factory reset (no existing VM) from `/opt/rancher-desktop/resources/resources/linux/bin/rdctl start --experimental.virtual-machine.mount.type virtiofs` then it *does* happen.

### Rancher Desktop Version

1.12.3-424-g7a6880cb

### Rancher Desktop K8s Version

1.28.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.5

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by AkihiroSuda** [comment]
Can't repro (with bare  Lima)
https://github.com/lima-vm/lima/issues/2221#issuecomment-1982577316

**Comment by mook-as** [comment]
Notes on reproducing:
- This could not be reproduced in lima v0.20.1 with the default `experimental/virtiofs-linux.yaml`
  - Not even when the mount is changed to be writable
  - I can actually see files from the mount; editing a file works.
  - Creating a new file doesn't work.
  - Gracefully shutting down is fine.
- I _can_ reproduce it if I use [`alpine.yaml`](https://github.com/lima-vm/lima/blob/v0.20.1/examples/alpine.yaml) + `mountType: "virtiofs"` + make `~` writable. Yay!
  - This doesn't happen when `~` isn't writable.

**Comment by AkihiroSuda** [comment]
The op of https://github.com/lima-vm/lima/issues/2221 seems to have hit a similar issue with Alpine + vz + virtiofs on macOS.
I guess https://github.com/lima-vm/alpine-lima may have some bug?

**Comment by AkihiroSuda** [comment]
> I can't start lima (0.20.1) with the latest alpine 3.18 release ([0.2.32](https://github.com/lima-vm/alpine-lima/releases/tag/v0.2.32)) — it hangs after binfmt but before ssh host key generation, so I can't login either. This is only if I set mountType: virtiofs.

Same for me, even with https://github.com/lima-vm/alpine-lima/releases/download/v0.2.35/alpine-lima-std-3.19.0-x86_64.iso

**Comment by AkihiroSuda** [comment]
Apparently `boot/04-persistent-data-volume.sh` is wiping the entire `/home` during `mv`

**Comment by jandubois** [comment]
> (but why only with virtiofs? 🤔 )

I think it will happen with `9p` too.

With `reverse-sshfs` it would fail:

```console
lima-rancher-desktop:~# mv /tmp/rancher-desktop /mnt/data
mv: can't remove '/tmp/rancher-desktop': Resource busy
```

But it doesn't happen anyways because `04-persistent-data-volume.sh` is executed before the sshfs mounts are set up.

With `virtiofs` and `9p` the mounts are already in place, and the move completes successfully:

```console
lima-rancher-desktop:~# mv /tmp/rancher-desktop /mnt/data
```

We already have code to unmount any directories under `/tmp` for this reason: https://github.com/lima-vm/lima/blob/fe633d4e150fe60142444a4591070fb45c3276a0/pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh#L64-L68. And at the end we run `mount -a` to remount them.

We obviously need this for any potential mount point.

So this explains what happens on Linux. It is kind of weird that the `~/.lima` directory would be moved inside `~/.lima/alpine/diffdisk`, and once the VM exits, everything is gone...

However, none of this explains https://github.com/lima-vm/lima/issues/2221 because `/Files` isn't being moved. But since the `lima.yaml` is from memory, maybe the directory name was actually different.

**Comment by jandubois** [comment]
> With `reverse-sshfs` it would fail:

Actually, it only fails to delete the mountpoint, but the data inside the directory is still gone:

```console
lima-rancher-desktop:~# cp /etc/os-release /tmp/rancher-desktop/
lima-rancher-desktop:~# find /tmp/rancher-desktop
/tmp/rancher-desktop
/tmp/rancher-desktop/os-release
lima-rancher-desktop:~# mv /tmp/rancher-desktop /mnt/data
mv: can't remove '/tmp/rancher-desktop': Resource busy
lima-rancher-desktop:~# find /tmp/rancher-desktop
/tmp/rancher-desktop
lima-rancher-desktop:~# find /mnt/data/rancher-desktop
/mnt/data/rancher-desktop
/mnt/data/rancher-desktop/os-release
```

So the only thing that saves `/home` on Linux with `reverse-sshfs` is the fact that the mount isn't in place yet.

**Comment by jandubois** [comment]
> We obviously need this for any potential mount point.

I was hoping we could use `umount -a -t virtiofs,9p` to simply unmount all hostmounts, do the moving, and then remount with `mount -a`, but unfortunately musl-1.2.4 still has the broken `mntent` implementation that doesn't support spaces in filenames.

```console
lima-rancher-desktop:~# umount -a -t virtiofs,9p
umount: can't unmount /Applications/Rancher\040Desktop.app/Contents/Resources/resources: No such file or directory
```

It is [reported](https://git.musl-libc.org/cgit/musl/tree/WHATSNEW) to be fixed in musl-1.2.5, but that won't be in Alpine until 3.20.

BTW, we need to retest this on Linux with `9p`; I don't see why it wouldn't have the same issue.

**Comment by AkihiroSuda** [comment]
Something like this may work?
```
# FIXME: the sed command below is not robust to cover other whitespaces such as tabs
for f in "$(cat /proc/mounts | awk '$3 == "virtiofs" || $3 == "9p" {print $2}' | grep "^${DIR}" | sed -e 's/\\040/ /g')"; do umount "$f"; done
```

**Comment by AkihiroSuda** [comment]
PR
- https://github.com/lima-vm/lima/pull/2234

**Comment by jandubois** [comment]
@AkihiroSuda Thank you, I've cherry-picked the commits into a Rancher Desktop branch of lima for now due to time constraints. Rancher Desktop is also still using Lima 0.19.

I'll provide some feedback on the PR before we merge it upstream.
