### ISSUE TITLE
Stuck at `Waiting for Kubernetes API` with WSL `networkingMode=mirrored`

### ISSUE THREAD

**Issue by oidualc** [rancher-sandbox/rancher-desktop#6665]
### Actual Behavior

When WSL is configured to use `networkingMode=mirrored`, Kubernetes doesn't start, and is instead stuck at the stage `Waiting for Kubernetes API`.

### Steps to Reproduce

- Set the following option in `%USERPROFILE%/.wslconfig`

```
[wsl2]
networkingMode=mirrored
```

- Open Rancher Desktop
- Enable Kubernetes

### Result

Kubernetes doesn't start, and is instead stuck at the stage `Waiting for Kubernetes API`.

### Expected Behavior

Kubernetes starts

### Additional Information

This is very similar to #6517, but this issue is not resolved in Rancher Desktop 1.13.1.

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

1.29.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Pro 23H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by evilhamsterman** [comment]
Yep it was not resolved in 1.13 apparently I had turned off mirrored mode at some point.

It appears that k3s does start, it is accessible within in the wsl rancher-desktop, and if you copy the kubeconfig out from the rancher-desktop image it works. The problem seems to be that Rancher Desktop is trying to check the wrong IP. With `networkingMode=mirrored` the cluster is accessible from the host Windows on localhost/127.0.0.1 rather than whatever IP Rancher Desktop is trying to check.

**Comment by evilhamsterman** [comment]
Even more information. When you enable `networkingMode=mirrored` the VM gets that same IP as the host computer. So I thought maybe it's trying to use that to test the api. The kubeconfig that works as above on 127.0.0.1 still doesn't work with VM/Host IP. 

However if you have Windows 11 22H2 or higher you can also enable the experimental setting `hostAddressLoopback=true` If you do that and restart WSL I assumed that I would be able to access the cluster as above on the 127.0.0.1 and my host computer address. I can access the cluster via 127.0.0.1 as before, but I still can't access it via VM IP address. 

You recently enabled your own Network Tunnel by default and that also appeared to causing issues. When I turned that back off now I was able to access the cluster via 127.0.0.1 and via my host IP address but Rancher Desktop still doesn't think the cluster is running.

At this point I'm not sure what IP Rancher Desktop is trying to access since both the localhost and the host IPs can access the cluster. However it seems to be that Rancher Desktop should be checking the `.wslconfig` to see if `networkingMode=mirrored` is enabled, if it is then rather than trying to use some IP in the VM you should just be using 127.0.0.1. It appears you do this on MacOS with your Lima backend

**Comment by DmytroYanchuk-tomtom** [comment]
Same problem on 1.15.0

**Comment by Codesmith1024** [comment]
I'm running into this issue with my teams - everything works great, but we need mirrored mode for VPN support, and then the UI breaks. `docker` and `kubectl` work great, it's just the UI that's borked.

I'd offer that `wslinfo --networking-mode` was added by MS as an official way to check for NAT vs mirrored networking, so it should be more reliable than trying to check the config file. However, I'm a bit surprised that the UI doesn't just use the endpoints specified in the docker / kubernetes context -- whatever's in there seems to be working just fine.

I did scan the log files for errors, and got a few, but didn't see anything relevant to this. I'll try to spin up the source code and poke around. If there's anywhere I should start looking, I'm all ears!

**Comment by Codesmith1024** [comment]
Notes for anyone who comes after:

1. `pkg/rancher-desktop/backend/kube/wsl.ts:208` is the `start()` method for the WSL implementation.
2. `:232` is where it waits for the server to be ready by calling `/pkg/rancher-desktop/backend/k3sHelper.ts`, and passes in `this.vm.ipAddress`
3. That ipAddress probably uses the implementation at `/pkg/rancher-desktop/backend/wsl.ts:939`, which finds the IP address by looking for the `eth0` address inside WSL2.
4. In mirrored mode, I don't have an `eth0`, so that function returns `undefined` (`:948`)
5. `waitForServerReady` waits for `ipAddress` to not be `undefined` (`:845`), which results in an infinite loop

Also of note is that that function looks like it probably can get called before kubeconfig exists, hence it doesn't just use that address.

If I can get the build environment up on my machine (I don't know that I have access to VS Studio), I'll try to add a check for mirrored mode via `wslinfo` and have the IP Address resolve to `127.0.0.1` if so.
