### ISSUE TITLE
Update rancher/dashboard fork whenever RD is ready

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#6874]
### Problem Description

https://github.com/rancher-sandbox/dashboard is an older fork of https://github.com/rancher/dashboard that still has Drone as its CI. `rancher/dashboard` was recently updated to be built via Github Actions and soon, Drone will go away so this will impact any updates to the dashboard whenever newer builds are required.

As I recall, the current roadmap doesn't require any UI updates but bear this in mind when this does change.

### Proposed Solution

Quick proposal: re-fork dashboard when ready
Less quick: since the fork has custom elements, then copy the GH Actions?

**Comment by gaktive** [comment]
FYI: this will soon happen with https://github.com/rancher-sandbox/rancher-desktop-steve too but that should spawn its separate ticket; I'm putting this here so it's not forgotten.

**Comment by jandubois** [comment]
I believe there are no automated builds happening for the dashboard clone; I think @rak-phillip has made them manually. Can you please confirm Phil?

We can remove the `.drone.yml` file, if we have to, but I believe it is non-functional anyways because this repo is not registered with drone.

**Comment by rak-phillip** [comment]
@jandubois that's correct. The builds are triggered when a github release is published.

**Comment by jandubois** [comment]
Oh, I see, we do run GHA to create the release already: https://github.com/rancher-sandbox/dashboard/blob/master/.github/workflows/release-rancher-desktop.yml

The trigger even is pushing a tag matching `desktop-v*`, and the workflow will then create the corresponding release.

I was confused because the UI says there are no workflow runs, but I assume that is because they have been so long ago that they expired.

Anyways, it means everything is all good already, building new releases with GHA.

So I don't see any action items for this issue; I would suggest that we close it @gaktive
