### ISSUE TITLE
Wrong kubectl architecture in Rancher.Desktop-1.13.1.aarch64.dmg

### ISSUE THREAD

**Issue by cbandy** [rancher-sandbox/rancher-desktop#6922]
### Actual Behavior

The `kubectl` executable provided in the macOS installer for Apple silicon is built for x86 and won't execute.

```console
$ file /Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/*
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker:                        Mach-O 64-bit executable arm64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-buildx:                 Mach-O 64-bit executable arm64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-compose:                Mach-O 64-bit executable arm64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-credential-ecr-login:   Mach-O 64-bit executable arm64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-credential-none:        Mach-O 64-bit executable arm64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker-credential-osxkeychain: Mach-O 64-bit executable arm64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/helm:                          Mach-O 64-bit executable arm64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl:                       Mach-O 64-bit executable x86_64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kuberlr:                       Mach-O 64-bit executable x86_64
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/nerdctl:                       Bourne-Again shell script text executable, ASCII text
/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/rdctl:                         Mach-O 64-bit executable arm64

$ '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl' --version
-bash: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl: Bad CPU type in executable

$ uname -m -v
Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64
```

### Steps to Reproduce

1. Install from the `aarch64.dmg` at https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.13.1
2. Start Rancher Desktop
3. Try to run `~/.rd.bin/kubectl --version`

### Result

```console
$ ~/.rd/bin/kubectl --version
…/kubectl: Bad CPU type in executable
```

### Expected Behavior

I expected to see the version of the `kubectl` client.

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

1.29.3

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Sonoma 14.4.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
This is intentional (see #980); you need to install Rosetta2 to run it.

Since we no longer require Rosetta for any other parts of the app anymore, we need to revisit this.

The most likely "solution" will be to drop support for Kubernetes versions before 1.21.0; then we can simply to switch to the `aarch64` version of `kuberlr` and everything will work automatically.

I can't tell yet when this will happen; maybe we should announce this in the 1.14 release notes, and if nobody complains, drop support for older k8s versions in the 1.15 release.

As a workaround, if you don't want to install Rosetta, you would have to install `kubectl` (or `kuberlr`) for `aarch64` yourself and put it on the PATH in front of `~/.rd/bin`.


I've put #980 into the 1.15 milestone, and will close this issue as a duplicate. Note that it is still possible that we won't switch yet in 1.15 if we get credible requests to continue to support older k8s versions.
