### ISSUE TITLE
Move wsl-distro dependencies into rancher-desktop repo

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#6971]
We have a couple of repos, like `rancher-desktop-agent`, `rancher-desktop-networking` etc. that all produce releases that will be bundled in `rancher-desktop-wsl-distro`.

This makes development quite awkward; after creating a PR against `rancher-desktop-networking` you need to merge and create a release. Then bump the release in `rancher-desktop-wsl-networking`, merge the bump, and create a release there. And finally you have to bump the distro release in `rancher-desktop` itself.

Since the additional repos only include Go applications, they should be moved under `src/go/` inside `rancher-desktop` itself.

The build script can then add them to the `wsl-distro` tarball.

The same logic can also be used for other external dependencies like `nerdctl`. That way the version dependency can be managed in the main repo, and we can release `wsl-distro` less often.

**Comment by mook-as** [comment]
It would be nice to import the histories of the sub-repos properly instead of pulling in a snapshot.  Possibly with [`git filter-repo`](https://github.com/newren/git-filter-repo) [`--to-subdirectory-filter`](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#_path_shortcuts).

**Comment by jandubois** [comment]
Oops, duplicated by epic in #7136
