### ISSUE TITLE
Indicate when fully online

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rancher-desktop#698]
When Rancher Desktop says it's started is when Kubernetes starts starting. It's when the container engine is online. This needs to be updated to show when Kubernetes is online.

This relates to #660. We shouldn't tell people RD is downloading something if it is not.

When it comes to status, we can tell people when the container engine is online and ready to use and then tell them when Kubernetes is online.

**Comment by mook-as** [comment]
Hmm, but we actually wait until we can start watching `/v1/services`, get cluster info, etc. before we stop claiming Kubernetes is starting.  We don't actually separately track whether the container engine is ready (since, at least initially, we didn't care about the container engine separately from the Kubernetes cluster).

We *do* say the cluster is ready before `kim` is ready, though.

Is there anything in particular that you're finding you can't do when the progress bar goes away?

**Comment by jandubois** [comment]
> Is there anything in particular that you're finding you can't do when the progress bar goes away?

I think it takes another 10s until `kubectl get no` returns actual data and not just `No resources found`, but I don't know if this should be considered "not yet ready".
