### ISSUE TITLE
[Bug] check for updates not working

### ISSUE THREAD

**Issue by GSV472002** [rancher-sandbox/rancher-desktop#7161]
### Actual Behavior

Whenever it is a new version of Rancher Desktop, the app did not notify me about it, so I need to go on the website and check or download the newer version from there.

### Steps to Reproduce

Check the *Check for updates automatically*

### Result

No result, it just does not notify when a new version is available

### Expected Behavior

It needs to notify the user when an update is ready for deploy.

### Rancher Desktop Version

1.14.2

### Rancher Desktop K8s Version

1.30.2

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Enterprise Version 23H2 ( OS Build 22631.3810)

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Yes, I use VPN

**Comment by jandubois** [comment]
As a matter of policy new releases are not added immediately to the auto-update server, but only after the release has been available for 3 to 7 days. That allows us to catch early issues that have slipped by QA and make a patch release before it becomes wildly installed.

This happened for the 1.13.0 and 1.14.0 releases, which both never made it to the auto-update channel.

So if you want to get the latest version on release day, you will have to download and install manually. This is intentional.

Note that it is also possible that we will not make a patch release available via auto-update at all if it only affects a very small subset of the users. For example the 1.14.2 release notes state:

> We are not enabling auto-update for the 1.14.2 release because the percentage of affected users will be very small. You need to manually update if you are on macOS and want to run spin up.

The only change in that release was the `spin` executable for macOS. And even then it would only affect running spin applications locally via `spin up`, and not any usage inside a container or kubernetes.
