### ISSUE TITLE
Upgrade gvisor-tap-vsock library for Windows

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#7260]
The gvisor-tap-vsock library on Windows is still pointing to version `v0.6.2` which is quite old, we should consider upgrading this on Windows.

**Comment by mook-as** [comment]
FWIW, we also need to upgrade it to make more `golangci-lint` bits pass, because the old gvisor we have doesn't support newer versions of the go toolchain.

I have a WIP in https://github.com/mook-as/rd/commit/d15721a501cffac07d409fc8e182c06f63b6ecc4 as part of more golangci-lint work in https://github.com/mook-as/rd/commits/golang-ci-lint/round-2/ but that's not ready for the current release.
