### ISSUE TITLE
Asking for password on startup in MacOS

### ISSUE THREAD

**Issue by mwisnicki** [rancher-sandbox/rancher-desktop#7307]
### Actual Behavior

Every time I login I get password prompt to run Rancher Desktop as root ("Administrative Access Required")

### Steps to Reproduce

1. Install rancher with brew
2. Logout/login

### Result

Password prompt is shown
<img width="486" alt="image" src="https://github.com/user-attachments/assets/ba78588b-6703-45d3-84b0-c1d0efbc32f5">
<img width="262" alt="image" src="https://github.com/user-attachments/assets/e63bfcec-26b0-4229-8538-a9d061aecaed">

### Expected Behavior

No password is needed. Also I have pam/sudo configured for touch ID and it works with other apps so I don't understand why it at least isn't asking for that.

### Additional Information

```
# cat /etc/sudoers | tail
# User specification
##

# root and users in group wheel can run anything on any machine as any user
root		ALL = (ALL) ALL
%admin		ALL = (ALL) ALL

## Read drop-in files from /private/etc/sudoers.d
## (the '#' here does not indicate a comment)
#includedir /private/etc/sudoers.d
```

```
# stat -l /etc/sudoers.d/zzzzz-rancher-desktop-lima 
-rw-r--r-- 1 root wheel 5239 Aug  6 11:54:10 2024 /etc/sudoers.d/zzzzz-rancher-desktop-lima

# stat -l /private/etc/sudoers.d/zzzzz-rancher-desktop-lima 
-rw-r--r-- 1 root wheel 5239 Aug  6 11:54:10 2024 /private/etc/sudoers.d/zzzzz-rancher-desktop-lima
```

### Rancher Desktop Version

1.13.1

### Rancher Desktop K8s Version

deactivated

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Sonoma 14.5

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
> ### Expected Behavior
> No password is needed.

The password prompt only happens when you configure Rancher Desktop with [Administrative Access](https://docs.rancherdesktop.io/ui/preferences/application/general).

This is only needed for 2 things:

* Enabled bridged networking, so your VM has it's own IP address on the local network
* The docker socket is created at `/var/run/docker.sock`

Most users don't need this functionality, which is why admin access is no longer the default.

The prompt should only happen after you reboot your machine (or if the network configuration has changed).

**Comment by mwisnicki** [comment]
Good to know but in case I want both of those items why isn't this working in more user friendly way.

Looks like there is a sudoers file that attempts to do it but is broken?

Also any idea why rancher is the only app where sudo does not offer touch id?

**Comment by jandubois** [comment]
> Good to know but in case I want both of those items why isn't this working in more user friendly way.

There rarely is a need for `/var/run/docker.sock` anymore as most applications now support docker contexts, and Rancher Desktop does create and select a `rancher-desktop` context to point to the custom socket location.

And the external IP address is really only needed if you want to connect to your containers from other machines on your local network. But you can also do port forwarding to `0.0.0.0` and then access the containers via your host IP address.

> Looks like there is a sudoers file that attempts to do it but is broken?

The sudoers file is only used for the vmnet daemon. The password prompt is shown when the sudoers file needs to be updated because the network config has changed.

Ideally the whole sudo mess should be replaced by a privileged helper process that only needs to be authorized once during installation. There is an Epic about changing all this (in #1224), but it has stalled, as there is nobody available to work on it.

> Also any idea why rancher is the only app where sudo does not offer touch id?

It uses [sudo-prompt](https://www.npmjs.com/package/sudo-prompt) to execute the commands, and that library doesn't support touch id. Feel free to suggest a replacement, ideally in form of a pull request. 😉

**Comment by jandubois** [comment]
I'm going to close this, as there is not any action left here that isn't already covered by #1224.

**Comment by mwisnicki** [comment]
Thank you for detailed explanation!

**Comment by mwisnicki** [comment]
> It uses [sudo-prompt](https://www.npmjs.com/package/sudo-prompt) to execute the commands, and that library doesn't support touch id. Feel free to suggest a replacement, ideally in form of a pull request. 😉

I tried to figure out how it does things and that's some sketchy code: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L668 it's a base64 encoded binary embedded in JS :(

**Comment by jandubois** [comment]
> it's a base64 encoded binary embedded in JS that's then extracted and executed

I know. We did unpack it and look at the AppleScript code inside to verify what it does.

**Comment by jandubois** [comment]
If you are curious:

```applescript
do shell script "./sudo-prompt-script" with administrator privileges
```

and the actual script:

```shell
#!/bin/bash
# Set sudo timestamp for subsequent sudo calls if tty_tickets are disabled:
/bin/mkdir -p /var/db/sudo/$USER > /dev/null 2>&1
/usr/bin/touch /var/db/sudo/$USER > /dev/null 2>&1
# AppleScript's "do shell script" may alter stdout line-endings.
# It may also set stdout to stderr if there was a non-zero return code and no stderr.
# We therefore prefer to redirect output streams and capture return code manually:
/bin/bash sudo-prompt-command 1>stdout 2>stderr
/bin/echo $? > code
# Correct ownership of stdout, stderr and code so that user can delete them:
/usr/sbin/chown $USER stdout stderr code
# Always return 0 so that AppleScript does not show error dialog:
exit 0
```
