### ISSUE TITLE
Rancher Desktop no longer works on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7463]
It is broken by an update to `qemu-ovmf-x86_64` (see https://bugzilla.suse.com/show_bug.cgi?id=1230291).

Workarounds:
* Install an older version of `qemu-ovmf-x86_64` if you can still find one
* Use the AppImage release of Rancher Desktop which comes bundled with its own copy of QEMU
* Wait for the `qemu-ovmf-x86_64` package to be fixed by openSUSE

There is no action item in this bug for the Rancher Desktop team; it has to be fixed upstream. This issue is purely about tracking the problem.

**Comment by mook-as** [comment]
It looks like using `/usr/share/qemu/ovmf-x86_64-4m.bin` instead of `/usr/share/qemu/ovmf-x86_64-4m-code.bin` works (drop the `-code` part).  Reading the [readme](https://build.opensuse.org/projects/Virtualization/packages/ovmf/files/README?expand=1), I think this is because the `-code` firmware doesn't include efivars and needs to be paired with `-drive if=pflash,format=raw,unit=1,file=ovmf-x86_64-vars.bin` (where it points at a file that can be modified)? I'm very unclear about this point, and it might be good to ask people who know about this stuff.  But it seems like adding that (pointing to `/usr/share/qemu/ovmf-x86_64-4m-vars.bin`) allows the system to boot.

I think we can [set the firmware](https://github.com/lima-vm/lima/blob/380fe118b448c17f7800a5cd9222233466d0944c/pkg/limayaml/limayaml.go#L23) if needed to use that? Not sure if it makes more sense to use the single file, or get lima to also use `-vars`…

**Comment by mickeybyte** [comment]
Any update on this. I'm running OpenSUSE Tumbleweed Slowroll version 20260402 and tried installing Rancher Desktop. Got an error starting the VM and got this issue. 
I was able to fix it using a .local/share/rancher-desktop/config/override.yaml: 
```
firmware:
  legacyBIOS: true
```
Which forces the VM to use legacy BIOS instead of UEFI.

**Comment by jandubois** [comment]
Thank you for the workaround!

Tumbleweed broke Lima again last month by removing the 2M firmware. This has been fixed in Lima already and will be included in the Rancher Desktop 1.23 release. Until then your workaround or using AppImage is the way to go.
