### ISSUE TITLE
HttpHostConnectException: Connect to localhost:2375

### ISSUE THREAD

**Issue by vynaidu2020** [rancher-sandbox/rancher-desktop#7466]
### Actual Behavior

When I tried to build a docker image for Spring Boot application using Maven I faced the issue.

### Steps to Reproduce

mvn clean package

### Result

Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: com.spotify.docker.client.shaded.org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: getsockopt ->

### Expected Behavior

docker image build successful.

### Rancher Desktop Version

1.15.1

### Rancher Desktop K8s Version

1.30.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by Nino-K** [comment]
Based on the stack trace from your Maven output, it appears that it's trying to connect to the Docker daemon on localhost:2375. However, Rancher Desktop's Docker daemon does not listen on TCP port 2375 by default, which is why you're encountering this error. I recommend checking the configuration on your Maven side, as this issue is not related to Rancher Desktop.
