### ISSUE TITLE
Initial setup stuck on 'Updating kubeconfig' (WSL)

### ISSUE THREAD

**Issue by Heap0017** [rancher-sandbox/rancher-desktop#7471]
### Actual Behavior

The initial setup gets stuck at 'Updating kubeonfig'.

### Steps to Reproduce

Open Rancher Desktop, choose K8s Version + engine as below.

### Result

The initial setup gets stuck at 'Updating kubeonfig'.

### Expected Behavior

The initial setup is succesfull.

### Additional Information

No diagnostic errors.
I tried reinstalling Rancher Desktop.

- `rancher-desktop-guestagent.log` repeated message: `kubernetes: failed to read kubeconfig [config-path=/etc/rancher/k3s/k3s.yaml][error=could not load Kubernetes client config from /etc/rancher/k3s/k3s.yaml: stat /etc/rancher/k3s/k3s.yaml: no such file or directory]`
- `wsl-exec.log` repeated message: `Running: wsl.exe --distribution rancher-desktop --exec /bin/sh -c if test -r /etc/rancher/k3s/k3s.yaml; then echo yes; else echo no; fi`
- `k3s.log` repeated message: `level=fatal msg="no default routes found in \"/proc/net/route\" or \"/proc/net/ipv6_route\""`. Potentially related issue https://github.com/k3s-io/k3s/issues/1144. However, there *is* a default route on my machine.

See also https://rancher-users.slack.com/archives/C0200L1N1MM/p1718399080544969

### Rancher Desktop Version

1.15.1

### Rancher Desktop K8s Version

1.30.4

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 19045

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Using VPN

**Comment by mook-as** [comment]
Could you enable [debug logging](https://docs.rancherdesktop.io/ui/troubleshooting#enable-debug-mode) and reproduce the problem, and then attach all of the [logs](https://docs.rancherdesktop.io/ui/troubleshooting#show-logs) to the bug? That would help track down issues.

For technical detail: we set up a network namespace in WSL, so the `/proc/net/route` that k3s sees should be ours (instead of your defaults).

**Comment by Heap0017** [comment]
Since working around the issue once, I am unable to reproduce it. Rancher Desktop seems to preserve some configuration across factory resets, reinstallations, and system reboots. How can I reset to a fresh installation?

**Comment by mook-as** [comment]
Odd; the only thing we may attempt to persist across factory resets are:
- The cached Kubernetes images (which we don't modify locally); if you factory reset using the UI, you need to tick the checkbox to keep it (and for the CLI, adding `--remove-kubernetes-cache` deletes it).
- Snapshots; these are only used when you explicitly interact with them.
- On Windows only: we don't uninstall WSL for you, because you may have non-Rancher Desktop distributions installed.

Neither should cause the issues you're seeing; so if we're keeping anything else, that would be a bug…

**Comment by Youpiiiii** [comment]
Same for me. I think it's something around WSL. I discover this system and after running some wsl commands, rancher started correctly

**Comment by kbegiedza** [comment]
Facing this again on Windows Server 2022 Datacenter 21H2 with rancher desktop: `v1.22.0`.

@Youpiiiii maybe you can remember / point to those commands?
