### ISSUE TITLE
Win11 WSL integration not working

### ISSUE THREAD

**Issue by sadoMasupilami** [rancher-sandbox/rancher-desktop#772]
After a fresh Rancher Desktop install on Windows 11 the WSL integration tab just shows "Error: wsl.exe exited with code 1". The checkbox is disabled. Is there anylog what happened?

Solid first impression btw!

**Comment by ngauje** [comment]
Same here on Windows 10 too

**Comment by mook-as** [comment]
The relevant message is:
`Error: Could not open Windows kubeconfig: stat : no such file or directory`
I believe the message format is actually `stat <file>: no such file or directory`; which means the file name is missing here.  I've pushe #1090 to have a better error message here, but I think the actual issue is in TypeScript (though I can't see any code path to result in an empty string here).

Leaving this open because I don't think we know what's actually happening here yet.

**Comment by alexmk92** [comment]
I was experiencing something similar (Rancher Desktop was showing `wsl.exe exited with code 1`).  After doing some further debugging I found that Rancher Desktop was trying to execute a command starting with `/mnt/c/rancher-desktop`.

Upon inspecting my WSL distro, I found that there was an empty mount for `/mnt/c` and `/mnt/wsl/rancher-desktop` which was causing any linkage between the Rancher Desktop and my WSL distro to fail.

In order to remedy this I added two symlinks:
```sh
ln -s /c/* /mnt/c
sudo ln -s /wsl/* /mnt/wsl
```

This was a fresh install of WSL2 and I had not yet provided any changes to `wsl.config` so I'm not entirely sure why my mount directorys were empty (and instead they were mounted to my root space 🤔)

After doing the above I was able to tick my WSL distro and run `kubectl` and `nerdctl` commands as expected; I hope this helps someone else 😄

**Comment by mook-as** [comment]
Odd, we _should_ be trying to run `wslpath` to find those (see [here](https://github.com/rancher-sandbox/rancher-desktop/blob/553fe594d8c09843318b90ca61d5509b34cc2cc3/src/k8s-engine/wsl.ts#L552)); though that seems to be different from the original report (since that managed to run the executable and fail internally).

**Comment by donatelloOo** [comment]
Once the `/mnt/wsl` mount is operational, the following can be run to finalize the WSL integration:
```
sudo chown root:docker /mnt/wsl/rancher-desktop/run/docker.sock
export DOCKER_HOST=unix:///mnt/wsl/rancher-desktop/run/docker.sock
export KUBECONFIG=/mnt/c/Users/<USER>/.kube/config
```
Note this is working for a docker-based container runtime (dockerd / moby).

**Comment by jandubois** [comment]
There have been multiple changes in this code over the last few releases, so I think this issue may be already fixed. Please re-open if you can still reproduce the problem with the 1.1.0 release!
