### ISSUE TITLE
Spin kube plugin 0.3.0 is not compatible with Rancher Desktop

### ISSUE THREAD

**Issue by mikkelhegn** [rancher-sandbox/rancher-desktop#7753]
### Actual Behavior

Using the tools associated with the Spinkube 0.4.0 release breaks this tutorial: https://www.spinkube.dev/docs/install/rancher-desktop/ based on this change to the Spin Kube plugin: https://github.com/spinkube/spin-plugin-kube/pull/89 

### Steps to Reproduce

Install 0.3.0 of the Spin Kube plugin
1. `spin plugin install kube -v 0.3.0`
2. Follow this tutorial: https://www.spinkube.dev/docs/install/rancher-desktop/

### Result

It breaks with the following error:
```
Error: invalid object type: core.spinkube.dev/v1alpha1, Kind=SpinApp
```

### Expected Behavior

Spin app gets installed

### Rancher Desktop Version

1.16.0

### Rancher Desktop K8s Version

1.31.2

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

15.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mikkelhegn** [comment]
More context: https://cloud-native.slack.com/archives/C06PC7JA1EE/p1731098637805949

**Comment by jandubois** [comment]
The whole spin operator and spin kube plugin situation is a bit of a mess right now.

The incompatibility with Rancher Desktop 1.16 is expected because because spinkube 0.4.0 and spin kube plugin 0.3.0 are not backwards compatible.

We've updated to spinkube 0.4.0 in #7725 and #7733, but the spin kube plugin 0.3.0 is not compatible with that either (https://github.com/spinkube/spin-plugin-kube/issues/93). It has been fixed upstream, but there is no new release yet.

I've also provided some feedback on how breaking API changes could be handled better in https://github.com/spinkube/spin-operator/issues/352.

Everything should be working fine with the latest spinkube plugin and operator in Rancher Desktop 1.17.0 (assuming a new working plugin release comes out).

**Comment by mikkelhegn** [comment]
@jandubois with the plugin `0.3.1` [released](https://github.com/spinkube/spin-plugin-kube/releases), does that work with Rancher Desktop `1.17.0`?

**Comment by jandubois** [comment]
> @jandubois with the plugin `0.3.1` [released](https://github.com/spinkube/spin-plugin-kube/releases), does that work with Rancher Desktop `1.17.0`?

@mikkelhegn It should now. We are going to maintain our separate `SPIN_DATA_DIR` now, and will reinstall the pinned plugin and templates on each start, to make sure a compatible set is available.

Users can always put their own version first in the `PATH`, but then they are responsible for making sure it all works together.
