### ISSUE TITLE
Kubernetes version not found error and is always disabled

### ISSUE THREAD

**Issue by rodneymorris** [rancher-sandbox/rancher-desktop#7892]
### Actual Behavior

Unable to select a Kubernetes version as none are listed.

### Steps to Reproduce

Start Racher Desktop > Preferences > Kubernetes > Enable Kubernetes > no options in the dropdown

### Result

![image](https://github.com/user-attachments/assets/afd38db0-7d29-4a3f-b1ff-ae934b401d50)

### Expected Behavior

Allow me to specivy a Kubernetes Version so that I can use Rancher on Kubernetes deployments

### Additional Information

wsl --version info
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4541
minikube version: v1.34.0
Docker Desktop 4.36.0; is able to start a Kubernetes integration. 

kubectl version...
Client Version: v1.31.3
Kustomize Version: v5.4.2
Unable to connect to the server: dial tcp 172.23.76.148:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Rancher Desktop Version

1.16.0

### Rancher Desktop K8s Version

None available however Minikube 

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Home 10.0.22631.4541 Build 22631.4541

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

Threatdown Endpoint Agent. Windows Security.

**Comment by rodneymorris** [comment]
Workaround: Uninstall. Install 1.15.1 and on start-up uncheck the Automatic Updates checkbox. Select a Kubernetes version Apply. Check the Automatic Updates and install 1.16.0.

**Comment by michelrisucci** [comment]
Thanks for the workaround, @rodneymorris.

For Debian-based Linux users, the ".deb" packages can be found here: https://download.opensuse.org/repositories/isv:/Rancher:/stable/deb/amd64/. I downloaded the rancher-desktop_1.15.1-3.1_amd64.deb version and could workaround the issue while the fix is coming.

For reference, ".rpm" packages can also be found here: https://download.opensuse.org/repositories/isv:/Rancher:/stable/rpm/x86_64/

**Comment by chibby0ne** [comment]
> Workaround: Uninstall. Install 1.15.1 and on start-up uncheck the Automatic Updates checkbox. Select a Kubernetes version Apply. Check the Automatic Updates and install 1.16.0.

Cannot believe it took me the good part of 2 hours to get to this.
Thanks for the suggestion. It worked perfectly!

**Comment by jandubois** [comment]
This error was caused by an update to the k3s channel server, that Rancher Desktop uses to get the latest/stable versions: https://github.com/k3s-io/k3s/issues/11447

Thankfully the k3s team was able to unbreak Rancher Desktop again.

The workaround of installing 1.15 first worked because 1.15 does not have the check on the `resourceType` in the channel server response, so actually worked with the updated channel server. And when you then upgraded to 1.16 the `k3s-versions.json` was already in the local cache.
