### ISSUE TITLE
Installing Docker Desktop silently crashes Rancher Desktop

### ISSUE THREAD

**Issue by mailmahee** [rancher-sandbox/rancher-desktop#802]
I installed Docker Desktop and all of a sudden RD was not starting and silently crashing.

**To Reproduce**
1. Install RD
2. Install Docker Desktop 
3. restarted system and RD won't start and starts crashing silently/not starting up.

I had to uninstall RD and then install it again - it works fine now...

**Expected behavior**
I was hoping to never uninstall RD

**LOGS**
```
$ tr -d '\0' < background.log
UnhandledRejectionWarning: TypeError: Promise resolve or reject function is not callable
    at Promise.then (<anonymous>)
```

**Setup (please complete the following information):**
 - OS: Windows - I also use WSL from Unix shell to access Kubernetes
 - Rancher Desktop version 0.6.0
 - Kubernetes version 1.21.5

**Comment by cronventis** [comment]
I have the same issue, but with the current version (1.1.1 but also 1.1.0). The only problem is: uninstalling and installing did not fix it.
Once I start rancher Desktop, I see a window opening and closing straight away. The previous version worked...

Setup
OS: Windows
Rancher Desktop version 1.1.1

Where do I find the logs for this crash?

**Comment by gunamata** [comment]
@mailmahee, Do you still see this problem with the latest version of Rancher Desktop? It looks like this issue was filed a while ago. We did make some improvements to Rancher Desktop to avoid some situations where Rancher Desktop and Docker Desktop installations step on each other.

Also, Rancher Desktop is not designed to work in parallel to Docker Desktop in a machine. At any given time you can have either Rancher Desktop or Docker Desktop running on a machine.

**Comment by gunamata** [comment]
Closing this as there's no response. Please feel free to reopen if you still experience this problem with the latest version of Rancher Desktop.
