### ISSUE TITLE
Add moby to the WSL distribution

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rancher-desktop#809]

**Comment by ericpromislow** [comment]
Note that we currently ship `buildkitd` (it's in the wsl distro.tar file), and when we run `kim builder install` it launches `buildkitd` inside a pod with image `docker.io/moby/buildkit:v0.8.3` . Trying to run the same command directly in the `rancher-desktop` WSL was only partially successful. `nerdctl` found the `buildkitd` server to talk to, but there were error messages and the build failed. Part of the reason was that I didn't give `buildkitd` the cert fields -- wasn't clear where a file like `/certs/ca/tls.crt` exists.
