### ISSUE TITLE
[Linux] Closing RD Window shuts the application off

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#824]
**For bugs, describe what you're seeing**
Closing RD through UI (red/orange `X`), it will shutdown the application.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open RD app on Linux
2. Wait until RD services are ready to use
3. Close the application using the UI (right upper corner - `X` icon) 
4. Hover on RD system tray icon
5. You should see the message: `Kubernetes is shutting down`

**Result**
Video:
https://user-images.githubusercontent.com/37411123/137770676-a8048bf8-098a-41b8-a214-685047c90b36.mov
It could be related with/or similar: https://github.com/rancher-sandbox/rancher-desktop/issues/714

**Expected behaviour**
* Closing RD app via UI, should keep the App running on background
* Closing RD app via UI, shouldn't stop the RD running services/tools

**Screenshots**
See `Result`

**Setup (please complete the following information):**
 - OS: `Linux Ubuntu 20.04.3 LTS`
 - Rancher Desktop version: `0.6.0-14-geda4c6e`
 - Kubernetes version: `1.21.5`

**Comment by jacobisaliveandwell** [comment]
@davidcassany I would like to revisit this topic.

If I may, there are many other applications that forego this concern by running as a singleton. I see RD as an almost viable replacement for Docker Desktop, and in that vein, RD should assume it's being run most, if not all the time on the host machine. If the user wants to quit, they can use the menu option for Quit. If they get lost because they don't have a tray, the app should identify a running instance when starting and re-attach; from there the user can find the Quit option.

I would also like to preempt any concern that this is not a common workflow - this is the de facto workflow for all Mac users. They have to use command-tab to reach an application with no windows or re-launch, and then select Quit explicitly.

**Comment by evertonlperes** [comment]
Tagging @adamkpickering in the thread.

**Comment by jacobisaliveandwell** [comment]
>  I guess a better experience on that regard would be to popup a confirmation dialog before closing

Also, this should be the default for all operating systems. Stopping and starting a virtual machine is not fast and RD should be considerate of that. I'm not sure why this was painted as a linux specific problem.

**Comment by thehejik** [comment]
Also `Show/Hide Window` entry in the tray icon menu on right click would be useful (on Windows too).

**Comment by DanHam** [comment]
I understand the issues with regard to the different implementations of systray (or lack thereof) across the various distro's and desktops (Gnome, KDE, Cinnamon) etc. 

However, where the systray icon exists it would be nice if we could close the main window and have Rancher Desktop continue running.

**Perhaps there should be an option that offers to continue running the application in the background when the user presses the X button to close the window.**

This would work well for both distro's/desktops with a systray and those without.

Of course when `rancher-desktop` is run again, it would need to check for an existing process...

**Comment by jsoref** [comment]
This feels related to #243

**Comment by adamkpickering** [comment]
Closing this issue since we have more actionable issues that overlap with it. Please refer to #3144 for more info.
