### ISSUE TITLE
Improve user experience around symlinks for supporting utilities

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#889]
**For bugs, describe what you're seeing**
RD does not recognize the clients apps, such as `nerdctl`, `kubectl`, `helm` ...

**To Reproduce**
Steps to reproduce the behaviour:
1. Open RD
2. Navigate to `Supporting Tools`
3. Tools checkboxes not enabled.

**Result**
Supporting tools not found (not linked).

**Expected behaviour**
Should link supporting tools properly.

**Screenshots**
![Screen Shot 2021-11-01 at 10 08 24 AM](https://user-images.githubusercontent.com/37411123/139703228-4cd8e07f-5260-46cc-bb60-f6229c8bc3e8.png)

**Setup (please complete the following information):**
 - OS: `macOS Monterey`
 - Rancher Desktop version: `0.6.0`
 - Kubernetes version: `1.21.5`

**Comment by jandubois** [comment]
This is working as expected: The user has moved `Rancher Desktop.app` to `$TMPDIR` and ran it from there, creating the symlinks.

The only think we could do is maybe show a warning dialog when the app has not be installed into either `/Applications` or `$HOME/Applications`.

Ok, bonus thought (and maybe we do this already): if a symlink is dangling (points to a file that doesn't exist), we should allow the user to overwrite it. It would not have helped in this situation, as the copy of RD inside the `$TMPDIR` had not be removed yet.

**Comment by jandubois** [comment]
I would like to keep this issue open until we have discussed the 2 suggestions I made above. Once we discard them (or create separate issues to schedule/implement them), we can close this one.

**Comment by ekloc** [comment]
> This is working as expected: The user has moved `Rancher Desktop.app` to `$TMPDIR` and ran it from there, creating the symlinks.

I run into similar issue on OSX Catalina.  On OSX I did't move the app to $TMPDIR.  I run the app from Downloads folder (since I couldn't move the app to Applications folder as I'm not a local admin) which created symlinks to @TMPDIR/T/AppTranslocation/209EA1E3-88D1-45C0-B4C9-0FE74CFA6F38/d/Rancher Desktop.app/Contents/Resources/resources/darwin/bin location.

Worked fine at first but after couple of days I noticed my kim and nerdctl would not work as my symlink was pointing to slightly different folder (@TMPDIR/T/AppTranslocation/220-EA1E3-xxx-..../d/Rancher Desktop.app/Contents/Resources/resources/darwin/bin).   Not sure how it changed but I fixed the issue by deleting the symlink, restarting the RD app and checking the checkmark next to kim and nerdctl which created the symlink correctly.  

Maybe it would make sense to  auto delete old and re-create new symlink  when an existing symlink points to a file that doesn't exist?

**Comment by rkazak** [comment]
I too am having a similar issue.  I have a fresh laptop with Big Sur installed.  I used the '.dmg'   as my install source.

I see the following after starting up Rancher Desktop.

<img width="783" alt="Screen Shot 2021-11-12 at 3 01 54 PM" src="https://user-images.githubusercontent.com/3156268/141593298-00f4b9a2-5612-4e7e-a641-3fcc22fb7c45.png">

So to get around this I added my user account to the wheel group and changed the permissions on the /usr/local/bin directory to 775, giving group wheel write perms into that directory.  This allowed the installation to complete successfully. Also I had other issues on reinstalls but that perms issue did not re-occur.

**Comment by rafadpedrosa** [comment]
I just want to reinforce for the others with the same problem as me that: I had the same issue as @evertonlperes and I did exactly what @ekloc said and It worked perfectly for me. 

I had to remove my symlinks from `/usr/local/bin/` then use the troubleshoot to `reset to the factory` 

😄

**Comment by adamkpickering** [comment]
Closing since the issues with supporting utilities have been fixed, and also because this issue is very out of date.
