### ISSUE TITLE
WSL Version

### ISSUE THREAD

**Issue by qskwood** [rancher-sandbox/rancher-desktop#890]
Which version of WSL is required for Rancher Desktop, 1 or 2?

**Comment by qskwood** [comment]
WSL 2 and nested virtualization conflict on AMD hosts.

The Virtual Machine Platform feature must be toggled (and the machine rebooted) to switch between the two featuresets.

**Comment by mook-as** [comment]
Rancher Desktop requires WSL 2.  I believe this is now documented in the [readme](https://github.com/rancher-sandbox/rancher-desktop/blob/0c3245708401afbe1f45aedf8b5c33612cbb3a18/README.md#get-the-app).

Since WSL 2 is based on Hyper-V, if you're using third-party virtualization solutions (VMWare, VirtualBox, etc.), they need to be updated to support the Virtual Machine Platform changes.  As far as I can tell, the current releases of VirtualBox (6.1.x) support this, in green turtle mode (in the status bar near the bottom right).  I am unaware of any differences with AMD-V — do you have a link to a description of the issue in the relevant bug tracker (or in the case of VMWare, I guess forums because I don't think they have a public bug tracker)?  It's a bit hard to provide more information, since you haven't mentioned which virtualization solution you're using.

**Comment by qskwood** [comment]
Thanks.

I had read that VirtualBox worked. I tested and found it disables the nested virtualization option. I had also read 21H2 may resolve the matter, but found the same.

**Comment by mattfarina** [comment]
Nested virtualization is going to depend on the number of cores you give to a VM and the processor you're using. If give a VM more than 1 core you need to have VT-x (on Intel) or amd-v (on AMD) for nested virtualization to work. I looked up the processor model for my system and then looked up the specs sheet.

Note, the feature can be included in a chip but disabled in the bios. So, if your chip has VT-x or amd-v and it's not working you might need to turn it on.

**Comment by qskwood** [comment]
Nesting works fine without VMP enabled. It does not work with it enabled on AMD hosts.

It's a conflict between the way Microsoft implemented it and the way other vendors implement their hypervisors. It may get fixed, it just isn't a Microsoft priority.

**Comment by qskwood** [comment]
https://github.com/microsoft/WSL/issues/4193#issuecomment-944134483 appears to indicate Windows 11 fixes this problem.
