### ISSUE TITLE
Cannot set traefik cert

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#938]
from https://rancher-users.slack.com/archives/C0200L1N1MM/p1636299069184000

>How can I replace / override the TRAEFIK DEFAULT CERT issuer with an alternate issuer?
I've created a kubernetes tls secret using a self signed certificate, and used it in an ingress manifest. The ingress works perfectly, but the site stills serves the TRAEFIK DEFAULT CERT.

**Comment by goncalossilva** [comment]
I am facing a similar issue in a private project. To be fair, its orchestration that was designed for docker and docker-compose, but the result is the same: Traefik is serving traffic with its default certificate when it should be using a self-signed one (that's the behavior with Docker Desktop, too). The issue seems known, but if not, let me know if I can provide additional information.

**Comment by jandubois** [comment]
I believe this scenario is sufficiently explained in [HTTPS on Kubernetes using Traefik Proxy | Traefik Labs](https://traefik.io/blog/https-on-kubernetes-using-traefik-proxy/#default-certificates).

I don't think there is any need for special support inside Rancher Desktop for configuring this.

**Comment by montogeek** [comment]
I am completely new to this tool, but in this section, how to specify my certificates?
<img width="874" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/1002461/0954a49d-8510-4bd5-afe4-c968be212bda">
