### ISSUE TITLE
Rancher desktop and nerdctl on ubuntu bash doesn't work

### ISSUE THREAD

**Issue by Cpt-Falcon** [rancher-sandbox/rancher-desktop#943]
**For bugs, describe what you're seeing**
Installed rancher desktop on windows with WSL2. Trying to use command line nerdctl on wsl2 ubuntu bash in wsl2 file system. It does not work at all, although works just fine on windows powershell in the windows file system. It is important to run certain things from WSL2 file system for performance reasons. See screenshot the result.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to run nerdctl compose up in ubuntu bash WSL2

**Result**
![image](https://user-images.githubusercontent.com/10540204/141193013-c291aa72-9ef6-4138-be27-92e383a6ce94.png)

Some weird error about /root/environment-files.yml no such file or directory. I'm not running from root. It should use my current path that im running nerdctl from

**Expected behaviour**
compose up runs as expected

**Setup (please complete the following information):**
 - OS: Windows 10 x64
 - Rancher Desktop version: 0.61
 - Kubernetes version: v1.21.6

**Comment by gunamata** [comment]
It looks like this issue is resolved in one of the Rancher Desktop versions released in the past 6 months. For example, I could get the Wordpress example at https://docs.docker.com/samples/wordpress/ working using the command `nerdctl compose up`.

Closing the issue, Please feel free to reopen if you still see problems running `nerdctl compose` with the latest version of Rancher Desktop.

![image](https://user-images.githubusercontent.com/59538726/171692121-fb2d1335-0c58-41da-a728-c14cec0beb9f.png)
