### ISSUE TITLE
[Bug]- K8s HttpError during app start up

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#968]
### Rancher Desktop Version

0.6.1

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3 / 5.3.18-59.27

### What CPU architecture are you using?

x64

### Windows User Only

N/A

### Actual Behavior

During the app start up, the following message pops up: `Error Starting Kubernetes - There was an unknown error starting K8s: HttpError: HTTP request failed`

### Steps to Reproduce

1. Install latest RD release using `*.rpm` package
2. Open RD App
3. Navigate to Troubleshooting and click `Factory Reset` 
4. Should see the error pop up

![Screen Shot 2021-11-16 at 4 40 43 PM](https://user-images.githubusercontent.com/37411123/142077847-18876d12-fe13-4ae2-b231-8adde324b642.png)
 

### Result

![Screen Shot 2021-11-16 at 4 31 25 PM](https://user-images.githubusercontent.com/37411123/142077666-be1e4b8d-c9b3-491c-862e-8fc09f566636.png)

### Expected Behavior

Should load the RD app properly without errors.

### Additional Information

I found a work around to fix this problem nuking the following folders:

```bash
$HOME/.local/share/rancher-desktop/
$HOME/.local/bin/
$HOME/.cache/rancher-desktop/
$HOME/.config/rancher-desktop/
```
After deleting those folders, the app starts properly. Also, I noticed the issue happens when the `Factory Reset` it's performed. 

**Logs**
[http_error_k8s_logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/7550378/http_error_k8s_logs.zip)

**Comment by davidcassany** [comment]
I am struggling to reproduce this issue on my openSUSE Leap 15.3 host using the latest build from `main` branch (`Version: 0.6.0-255-g43ba875` on main screen). @evertonlperes Is it consistently happening to you? Could you test with this latest RPM package?


You can find the latest RPM build from `main` in this [repo](https://download.opensuse.org/repositories/isv:/Rancher:/dev/rpm/). 
Adding such a repo to zypper can be done with:

```bash
sudo zypper ar --refresh https://download.opensuse.org/repositories/isv:/Rancher:/dev/rpm/isv:Rancher:dev.repo
sudo zypper in rancher-desktop
```

This repository is updated from GA to package the latest `main` build.

This is what I did:

I uninstalled any RD I had on my host and cleaned any RD related XDG folder, so started from clean state. I did the cycle several times:

* Launch RD
* Wait RD to load
* Factory Reset (then closes and relaunches again)

I did the cycle several times and only once I saw the issue you reported, which was solved by triggering the `Factory Reset` button again. What I did see few times is that the VM shutdown not always succeeds and when it happens the app does not immediately restarts, it just stays on broken state (even the VM is already stopped and there is no QEMU process around). I got this lima logs:

```
time="2021-11-17T12:23:59+01:00" level=fatal msg="failed to delete instance \"0\": expected status \"Stopped\", got \"Broken\""
2021-11-17T11:23:59.264Z: + limactl delete 0
2021-11-17T11:23:59.264Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
```

Triggering again `Factory Reset` closes the app and relaunches. From these logs to me it looks like there are few issues:

* Lima reports a broken state of the VM after shutdown
* Lima refuses to delete a VM on broken state it (wondering why a broken state is a blocker to delete it, probably I want to delete it because it is broken 😅 )
* RD despite not having any QEMU process around does not proceed with the cleaning and relaunch (IMHO we should be more aggressive here, so remove all linux paths and relaunch even if the graceful stop failed)

Gonna try to investigate it a bit further, probably this is related to the former issue reported here.

**Comment by evertonlperes** [comment]
It seems to be an intermittent issue. I did replicate the issue few times (around 3x) and like you said, hitting `Factory Reset` fixes the issue.
Also, I can confirm the broken state from Lima, it was reproduced on both environment (Linux and macOS) and on Adam's laptop (popOS).

Got the error during first install as you have recommended:

Logs
[http_error_060_rpm_logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/7555973/http_error_060_rpm_logs.zip)

**Comment by evertonlperes** [comment]
I was able to reproduce it on CI as well and here's TLDR of the log:

```bash
cat /home/rancheruser/.local/share/rancher-desktop/logs/background.log 
2021-11-24T21:04:04.320Z: k8s-current-port: 6443
2021-11-24T21:04:10.831Z: Kubernetes was unable to start: HttpError: HTTP request failed
    at Request._callback (/home/rancheruser/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:11738:40)
    at Request.self.callback (/home/rancheruser/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/rancheruser/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/rancheruser/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  response: <ref *1> IncomingMessage {
```

OS: `Ubuntu 20.04`
CPU: `4`
MEM: `8GB`

Full log
[background_ci.log](https://github.com/rancher-sandbox/rancher-desktop/files/7598837/background_ci.log)
[k3s_ci.log](https://github.com/rancher-sandbox/rancher-desktop/files/7598839/k3s_ci.log)
[k8s_ci.log](https://github.com/rancher-sandbox/rancher-desktop/files/7598840/k8s_ci.log)
[lima_error_CI.log](https://github.com/rancher-sandbox/rancher-desktop/files/7598841/lima_error_CI.log)
[lima_serial_ci.log](https://github.com/rancher-sandbox/rancher-desktop/files/7598842/lima_serial_ci.log)
[lima_stderr_ci.log](https://github.com/rancher-sandbox/rancher-desktop/files/7598843/lima_stderr_ci.log)
[lima_stdout_ci.log](https://github.com/rancher-sandbox/rancher-desktop/files/7598844/lima_stdout_ci.log)

**Comment by evertonlperes** [comment]
Fixed by: https://github.com/rancher-sandbox/rancher-desktop/pull/1117
