### ISSUE TITLE
[Bug]- Revisit merging of lima configs: defaults after or before current config?

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#972]
### Rancher Desktop Version

0.6.1

### What operating system are you using?

Other (specify below)

### Operating System / Build Version

All

### What CPU architecture are you using?

x64

### Actual Behavior

See the change in  src/k8s-engine/lima.ts line 415/425

### Steps to Reproduce

needs code analysis

### Result

are current settings lost?  Do we care?

### Expected Behavior

...

**Comment by jandubois** [comment]
@ericpromislow I can't figure out why the merging order should be revisited.

I assume it is a reference to https://github.com/rancher-sandbox/rancher-desktop/commit/e1097f79916ce62dbd6ccce1e1b2a6b2fef404ce, but I can't tell why this should not be correct.

Maybe this doesn't matter anymore anyways because users are not supposed to edit `lima.yaml` manually at all; we have introduced the `override.yaml` mechanism to allow changing settings without them getting overwritten when RD merges changes.

So I'm going to close this as "expired". Feel free to re-open if you think there is still something left to do!

**Comment by ericpromislow** [comment]
It doesn't need to be revisited because we're not merging a file that users are able to change for their own use.
