### ISSUE TITLE
[Question] Manually update nerdctl on Windows

### ISSUE THREAD

**Issue by djfoxer** [rancher-sandbox/rancher-desktop#989]
I try to update nerdctl on Windows manually but it crashed.

Path on Windows: `AppData\Local\Programs\Rancher Desktop\resources\resources\win32\bin`
RD has nerdctl version 0.11 (only 1.8MB)
The latest version is 0.14 (26MB!)

When I swap nerdctl.exe file to 0.14 it crushes at runtime:
> level=fatal msg="cannot access containerd socket \"\\\\\\\\.\\\\pipe\\\\containerd-containerd\": open \\\\.\\pipe\\containerd-containerd: The system cannot find the file specified."

**Comment by mook-as** [comment]
Hi! Yes, the 1.8MB executable is a [wrapper](https://github.com/rancher-sandbox/rancher-desktop/tree/main/src/go/nerdctl-stub) that forwards things to the real (Linux) nerdctl running inside WSL.  The Windows nerdctl binaries you download from upstream would be used for running Windows-native containers instead.

If you'd like to update nerdctl manually, you'll need to update the files inside the `rancher-desktop` WSL distribution (the upstream archive was [extracted](https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/blob/dba0f0b82a21d806911681408b4a5993be47679b/files/build.sh#L51-L60) into `/usr/local/`), and if the command line arguments changed, you'd need to rebuild the stub (remember to run `go generate` first).

I'm closing this issue now because hopefully this answers your question; if you would like more details, please reopen, thanks! (And possibly convert to discussion; there's a link near the bottom right corner of the page.)

**Comment by djfoxer** [comment]
@mook-as Hi! Thank you for your answer. I updated nerdctl on VM but have some issue with building stub. When I run
`npm run generate:nerdctl-stub`
I get error:
```
rror getting help for []: fork/exec /nerdctl: no such file or directory
../nerdctl_commands_generated.go:9:47: expected '}', found 'EOF'
```
and in `nerdctl_commands_generated.go` I get
```

// Code generated by github.com/rancher-sandbox/rancher-desktop/src/go/nerdctl-stub - DO NOT EDIT.

// package main implements a stub for nerdctl
package main

// commands supported by nerdctl; the key here is a space-separated subcommand
// path to reach the given subcommand (where the root command is empty).
var commands = map[string]commandDefinition {
```
What I'm missing?

**Comment by djfoxer** [comment]
@mook-as I just need to use --add-host which is available in higher version so this is why I try to update nerdctl :)

**Comment by mook-as** [comment]
Hi there!
Odd, we just run [`/usr/local/bin/nerdctl`](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.6.1/src/go/nerdctl-stub/generate/main.go#L22) from the [`rancher-desktop` distribution](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.6.1/scripts/windows/generate-nerdctl-stub.ps1#L9); I'm not sure why you're getting issues with the `/nerdctl` (i.e. missing the path completely).

If you just want a specific command, you can try editing [the generated file](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.6.1/src/go/nerdctl-stub/nerdctl_commands_generated.go) directly; that's just not as maintainable, but if you just need it to last until we bump on our end that's probably fine?

**Comment by djfoxer** [comment]
@mook-as  > run [`/usr/local/bin/nerdctl`](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.6.1/src/go/nerdctl-stub/generate/main.go#L22) from the [`rancher-desktop` distribution](https://github.com/rancher-sandbox/rancher-desktop/blob/v0.6.1/scripts/windows/generate-nerdctl-stub.ps1#L9);

Ok, I get it. I run script on Windows (changed `var nerdctl = "/usr/local/bin/nerdctl"` to my path with nerdctl 0.14) so probably this is why I have this error. Do you think it will be possible to create the stub on Windows?

**Comment by mook-as** [comment]
The stub needs to be created on Windows; however, you need to manually go into the `rancher-desktop` WSL distribution and replace `/usr/local/bin/nerdctl` before generating the code, and the building the binary (easiest for that part is just to run `npm run build` at the top level, wait for it to finish, then grab the file out of `resources/win32/bin`).

Note that you _need_ to upgrade `/usr/local/bin/nerdctl` anyway, since that's what `nerdctl-stub` actually calls.

The win32 client (`nerdctl.exe` from upstream) would never be involved.

**Comment by djfoxer** [comment]
Thank you! I will try this way. I already swapped file in WSL distro (it's easy to access it from Windows Explorer, path is simple: `\\wsl$\rancher-desktop\usr\local\bin`)

**Comment by djfoxer** [comment]
Maybe it will be good a idea to try to write the script to update nerdctl cos they are updating it quite fast with bunch of new stuff.
